import { CefrLevel } from '@prisma/client';

export type VocabularySeedWord = [
  string,
  string,
  string,
  string,
  string,
];

export type VocabularySeedSet = {
  slug: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  cefrLevel: CefrLevel;
  topic: string;
  isFeatured: boolean;
  sortOrder: number;
  words: VocabularySeedWord[];
};

export const TECH_VOCABULARY_SETS: VocabularySeedSet[] = [
  {
    slug: 'cong-nghe',
    title: 'Công nghệ',
    description:
      '300+ từ vựng công nghệ thiết yếu: phần cứng, phần mềm, internet, lập trình, AI, bảo mật và hơn thế nữa',
    icon: 'cpu',
    color: 'blue',
    cefrLevel: CefrLevel.A2,
    topic: 'Công nghệ',
    isFeatured: true,
    sortOrder: 5,
    words: [
      ['technology', '/tekˈnɒlədʒi/', 'Công nghệ', 'Technology has changed the way we live and work.', 'Công nghệ đã thay đổi cách chúng ta sống và làm việc.'],
      ['innovation', '/ˌɪnəˈveɪʃn/', 'Sự đổi mới', 'Innovation drives progress in the tech industry.', 'Sự đổi mới thúc đẩy tiến bộ trong ngành công nghệ.'],
      ['invention', '/ɪnˈvenʃn/', 'Phát minh', 'The telephone was an important invention.', 'Điện thoại là một phát minh quan trọng.'],
      ['digital', '/ˈdɪdʒɪtl/', 'Kỹ thuật số', 'We live in a digital age.', 'Chúng ta đang sống trong thời đại số.'],
      ['automation', '/ˌɔːtəˈmeɪʃn/', 'Tự động hóa', 'Automation has replaced many manual jobs.', 'Tự động hóa đã thay thế nhiều công việc thủ công.'],
      ['electronic', '/ɪˌlekˈtrɒnɪk/', 'Điện tử', 'She bought a new electronic device.', 'Cô ấy đã mua một thiết bị điện tử mới.'],
      ['modern', '/ˈmɒdn/', 'Hiện đại', 'Modern technology makes life easier.', 'Công nghệ hiện đại làm cho cuộc sống dễ dàng hơn.'],
      ['advanced', '/ədˈvɑːnst/', 'Tiên tiến', 'This factory uses advanced machinery.', 'Nhà máy này sử dụng máy móc tiên tiến.'],
      ['upgrade', '/ʌpˈgreɪd/', 'Nâng cấp', 'I plan to upgrade my computer next month.', 'Tôi dự định nâng cấp máy tính của mình vào tháng tới.'],
      ['update', '/ʌpˈdeɪt/', 'Cập nhật', 'Please update your app to the latest version.', 'Vui lòng cập nhật ứng dụng của bạn lên phiên bản mới nhất.'],
      ['version', '/ˈvɜːʃn/', 'Phiên bản', 'This is the newest version of the software.', 'Đây là phiên bản mới nhất của phần mềm.'],
      ['feature', '/ˈfiːtʃə(r)/', 'Tính năng', 'The new phone has many useful features.', 'Chiếc điện thoại mới có nhiều tính năng hữu ích.'],
      ['function', '/ˈfʌŋkʃn/', 'Chức năng', 'Each button has a different function.', 'Mỗi nút có một chức năng khác nhau.'],
      ['system', '/ˈsɪstəm/', 'Hệ thống', 'The system crashed this morning.', 'Hệ thống đã bị sập sáng nay.'],
      ['process', '/ˈprəʊses/', 'Quy trình, xử lý', 'The computer needs time to process the data.', 'Máy tính cần thời gian để xử lý dữ liệu.'],
      ['efficiency', '/ɪˈfɪʃnsi/', 'Hiệu quả', 'New tools improved the team\'s efficiency.', 'Các công cụ mới đã cải thiện hiệu suất của đội.'],
      ['prototype', '/ˈprəʊtətaɪp/', 'Nguyên mẫu', 'Engineers built a prototype of the new device.', 'Các kỹ sư đã xây dựng một nguyên mẫu của thiết bị mới.'],
      ['startup', '/ˈstɑːtʌp/', 'Công ty khởi nghiệp', 'She works at a tech startup in Hanoi.', 'Cô ấy làm việc tại một công ty khởi nghiệp công nghệ ở Hà Nội.'],
      ['breakthrough', '/ˈbreɪkθruː/', 'Đột phá', 'Scientists made a breakthrough in battery technology.', 'Các nhà khoa học đã có bước đột phá trong công nghệ pin.'],
      ['trend', '/trend/', 'Xu hướng', 'Wearable devices are a growing trend.', 'Thiết bị đeo được đang trở thành một xu hướng đang phát triển.'],
      ['disruption', '/dɪsˈrʌpʃn/', 'Sự đột phá, gián đoạn', 'This app caused disruption in the taxi industry.', 'Ứng dụng này đã gây ra sự gián đoạn trong ngành taxi.'],
      ['solution', '/səˈluːʃn/', 'Giải pháp', 'The company offers software solutions for schools.', 'Công ty cung cấp giải pháp phần mềm cho các trường học.'],
      ['compatibility', '/kəmˌpætəˈbɪləti/', 'Khả năng tương thích', 'Check the compatibility before installing the software.', 'Kiểm tra tính tương thích trước khi cài đặt phần mềm.'],
      ['interface', '/ˈɪntəfeɪs/', 'Giao diện', 'The app has a simple, user-friendly interface.', 'Ứng dụng có giao diện đơn giản, thân thiện với người dùng.'],
      ['integration', '/ˌɪntɪˈgreɪʃn/', 'Sự tích hợp', 'The integration of AI improved the product.', 'Việc tích hợp AI đã cải thiện sản phẩm.'],
      ['hardware', '/ˈhɑːdweə(r)/', 'Phần cứng', 'The hardware of this laptop is very powerful.', 'Phần cứng của chiếc laptop này rất mạnh mẽ.'],
      ['computer', '/kəmˈpjuːtə(r)/', 'Máy tính', 'I use my computer for work every day.', 'Tôi sử dụng máy tính của mình để làm việc mỗi ngày.'],
      ['laptop', '/ˈlæptɒp/', 'Máy tính xách tay', 'She carries her laptop to school.', 'Cô ấy mang laptop đến trường.'],
      ['desktop', '/ˈdesktɒp/', 'Máy tính để bàn', 'He prefers a desktop for gaming.', 'Anh ấy thích máy tính để bàn cho việc chơi game.'],
      ['monitor', '/ˈmɒnɪtə(r)/', 'Màn hình', 'The monitor displays sharp, clear images.', 'Màn hình hiển thị hình ảnh sắc nét, rõ ràng.'],
      ['keyboard', '/ˈkiːbɔːd/', 'Bàn phím', 'My keyboard has a few broken keys.', 'Bàn phím của tôi có một vài phím bị hỏng.'],
      ['mouse', '/maʊs/', 'Chuột máy tính', 'This wireless mouse is very comfortable.', 'Chuột không dây này rất thoải mái.'],
      ['processor (cpu)', '/ˈprəʊsesə(r)/', 'Bộ vi xử lý', 'A faster processor makes the computer run smoothly.', 'Một bộ vi xử lý nhanh hơn giúp máy tính chạy mượt mà.'],
      ['motherboard', '/ˈmʌðəbɔːd/', 'Bo mạch chủ', 'The technician replaced the damaged motherboard.', 'Kỹ thuật viên đã thay thế bo mạch chủ bị hỏng.'],
      ['memory (ram)', '/ˈmeməri/', 'Bộ nhớ (RAM)', 'More memory helps the computer multitask better.', 'Nhiều bộ nhớ hơn giúp máy tính đa nhiệm tốt hơn.'],
      ['storage', '/ˈstɔːrɪdʒ/', 'Bộ lưu trữ', 'This laptop has 512 GB of storage.', 'Chiếc laptop này có 512 GB dung lượng lưu trữ.'],
      ['hard drive', '/hɑːd draɪv/', 'Ổ cứng', 'The hard drive failed and I lost my files.', 'Ổ cứng đã hỏng và tôi đã mất các tệp của mình.'],
      ['usb drive', '/ˌjuː es ˈbiː draɪv/', 'Ổ USB', 'Save the document to your USB drive.', 'Lưu tài liệu vào ổ USB của bạn.'],
      ['printer', '/ˈprɪntə(r)/', 'Máy in', 'The printer is out of ink again.', 'Máy in lại hết mực rồi.'],
      ['scanner', '/ˈskænə(r)/', 'Máy quét', 'I used a scanner to digitize old photos.', 'Tôi đã sử dụng máy quét để số hóa những bức ảnh cũ.'],
      ['webcam', '/ˈwebkæm/', 'Webcam', 'We use a webcam for video calls.', 'Chúng tôi sử dụng webcam cho các cuộc gọi video.'],
      ['speaker', '/ˈspiːkə(r)/', 'Loa', 'The speaker produces excellent sound quality.', 'Loa phát ra âm thanh chất lượng tuyệt vời.'],
      ['microphone', '/ˈmaɪkrəfəʊn/', 'Micro', 'Please speak closer to the microphone.', 'Xin hãy nói gần micro hơn.'],
      ['charger', '/ˈtʃɑːdʒə(r)/', 'Bộ sạc', 'I forgot to bring my phone charger.', 'Tôi quên mang theo sạc điện thoại.'],
      ['battery', '/ˈbætri/', 'Pin', 'The battery drains quickly when I play games.', 'Pin nhanh hết khi tôi chơi game.'],
      ['cable', '/ˈkeɪbl/', 'Dây cáp', 'Connect the cable to the HDMI port.', 'Kết nối cáp với cổng HDMI.'],
      ['adapter', '/əˈdæptə(r)/', 'Bộ chuyển đổi', 'You need an adapter to charge this device abroad.', 'Bạn cần một bộ chuyển đổi để sạc thiết bị này ở nước ngoài.'],
      ['circuit', '/ˈsɜːkɪt/', 'Mạch điện', 'The engineer designed a new electronic circuit.', 'Kỹ sư đã thiết kế một mạch điện tử mới.'],
      ['chip', '/tʃɪp/', 'Chip', 'This phone uses a very fast chip.', 'Chiếc điện thoại này sử dụng một chip rất nhanh.'],
      ['sensor', '/ˈsensə(r)/', 'Cảm biến', 'The sensor detects motion in the room.', 'Cảm biến phát hiện chuyển động trong phòng.'],
      ['device', '/dɪˈvaɪs/', 'Thiết bị', 'This device can connect to Wi-Fi automatically.', 'Thiết bị này có thể tự động kết nối với Wi-Fi.'],
      ['gadget', '/ˈgædʒɪt/', 'Thiết bị công nghệ nhỏ gọn', 'He loves buying the latest tech gadgets.', 'Anh ấy thích mua những thiết bị công nghệ mới nhất.'],
      ['tablet', '/ˈtæblət/', 'Máy tính bảng', 'She reads books on her tablet.', 'Cô ấy đọc sách trên máy tính bảng của mình.'],
      ['smartwatch', '/ˈsmɑːtwɒtʃ/', 'Đồng hồ thông minh', 'My smartwatch tracks my heart rate.', 'Đồng hồ thông minh của tôi theo dõi nhịp tim của tôi.'],
      ['router', '/ˈruːtə(r)/', 'Bộ định tuyến', 'Restart the router if the internet is slow.', 'Khởi động lại bộ định tuyến nếu internet chậm.'],
      ['software', '/ˈsɒftweə(r)/', 'Phần mềm', 'I need to update the software on my computer.', 'Tôi cần cập nhật phần mềm trên máy tính của mình.'],
      ['application (app)', '/ˌæplɪˈkeɪʃn/', 'Ứng dụng', 'She downloaded a new application on her phone.', 'Cô ấy đã tải xuống một ứng dụng mới trên điện thoại của mình.'],
      ['operating system', '/ˈɒpəreɪtɪŋ ˈsɪstəm/', 'Hệ điều hành', 'Windows is a popular operating system.', 'Windows là một hệ điều hành phổ biến.'],
      ['program', '/ˈprəʊgræm/', 'Chương trình', 'This program helps you edit photos.', 'Chương trình này giúp bạn chỉnh sửa ảnh.'],
      ['install', '/ɪnˈstɔːl/', 'Cài đặt', 'Install the app before you use it.', 'Cài đặt ứng dụng trước khi bạn sử dụng nó.'],
      ['uninstall', '/ˌʌnɪnˈstɔːl/', 'Gỡ cài đặt', 'I uninstalled the app because it was slow.', 'Tôi đã gỡ cài đặt ứng dụng vì nó chậm.'],
      ['user interface (ui)', '/ˈjuːzə(r) ˈɪntəfeɪs/', 'Giao diện người dùng', 'The new UI is much easier to navigate.', 'Giao diện người dùng mới dễ điều hướng hơn nhiều.'],
      ['bug', '/bʌg/', 'Lỗi phần mềm', 'The developers fixed a bug in the update.', 'Các nhà phát triển đã sửa một lỗi trong bản cập nhật.'],
      ['patch', '/pætʃ/', 'Bản vá lỗi', 'A security patch was released yesterday.', 'Một bản vá bảo mật đã được phát hành hôm qua.'],
      ['license', '/ˈlaɪsns/', 'Giấy phép', 'You need a license to use this software.', 'Bạn cần có giấy phép để sử dụng phần mềm này.'],
      ['antivirus', '/ˌæntiˈvaɪrəs/', 'Phần mềm diệt virus', 'Install antivirus software to protect your computer.', 'Cài đặt phần mềm diệt virus để bảo vệ máy tính của bạn.'],
      ['firewall', '/ˈfaɪəwɔːl/', 'Tường lửa', 'The firewall blocks unauthorized access.', 'Tường lửa chặn truy cập trái phép.'],
      ['freeware', '/ˈfriːweə(r)/', 'Phần mềm miễn phí', 'This freeware lets you edit videos for free.', 'Phần mềm miễn phí này cho phép bạn chỉnh sửa video miễn phí.'],
      ['plugin', '/ˈplʌgɪn/', 'Trình bổ trợ', 'I added a plugin to improve the browser\'s speed.', 'Tôi đã thêm một plugin để cải thiện tốc độ trình duyệt.'],
      ['driver', '/ˈdraɪvə(r)/', 'Trình điều khiển', 'You must install the printer driver first.', 'Bạn phải cài đặt trình điều khiển máy in trước.'],
      ['browser', '/ˈbraʊzə(r)/', 'Trình duyệt', 'Chrome is my favorite web browser.', 'Chrome là trình duyệt web yêu thích của tôi.'],
      ['spreadsheet', '/ˈspredʃiːt/', 'Bảng tính', 'She created a spreadsheet to track expenses.', 'Cô ấy đã tạo một bảng tính để theo dõi chi phí.'],
      ['utility', '/juˈtɪləti/', 'Tiện ích', 'This utility cleans up unused files.', 'Tiện ích này dọn dẹp các tệp không sử dụng.'],
      ['emulator', '/ˈemjuleɪtə(r)/', 'Trình giả lập', 'He used an emulator to play old games.', 'Anh ấy đã sử dụng một trình giả lập để chơi các trò chơi cũ.'],
      ['executable file', '/ɪgˈzekjətəbl faɪl/', 'Tệp thực thi', 'Double-click the executable file to run the program.', 'Nhấp đúp vào tệp thực thi để chạy chương trình.'],
      ['shortcut', '/ˈʃɔːtkʌt/', 'Phím tắt / lối tắt', 'I created a shortcut on my desktop.', 'Tôi đã tạo một lối tắt trên màn hình chính.'],
      ['backup', '/ˈbækʌp/', 'Sao lưu', 'Always keep a backup of your important files.', 'Luôn giữ một bản sao lưu cho các tệp quan trọng của bạn.'],
      ['restore', '/rɪˈstɔː(r)/', 'Khôi phục', 'I restored my phone to its factory settings.', 'Tôi đã khôi phục điện thoại về cài đặt gốc.'],
      ['compress', '/kəmˈpres/', 'Nén (dữ liệu)', 'Compress the files before sending them.', 'Nén các tệp trước khi gửi chúng.'],
      ['format', '/ˈfɔːmæt/', 'Định dạng', 'I had to format the disk before using it.', 'Tôi phải định dạng ổ đĩa trước khi sử dụng nó.'],
      ['internet', '/ˈɪntənet/', 'Mạng Internet', 'We use the internet to search for information.', 'Chúng tôi sử dụng internet để tìm kiếm thông tin.'],
      ['network', '/ˈnetwɜːk/', 'Mạng lưới', 'Our office has a secure wireless network.', 'Văn phòng của chúng tôi có mạng không dây an toàn.'],
      ['wi-fi', '/ˈwaɪfaɪ/', 'Wi-Fi', 'The café offers free Wi-Fi to customers.', 'Quán cà phê cung cấp Wi-Fi miễn phí cho khách hàng.'],
      ['website', '/ˈwebsaɪt/', 'Trang web', 'This website has useful learning resources.', 'Trang web này có tài nguyên học tập hữu ích.'],
      ['webpage', '/ˈwebpeɪdʒ/', 'Trang web (đơn lẻ)', 'Click the link to open the webpage.', 'Nhấp vào liên kết để mở trang web.'],
      ['server', '/ˈsɜːvə(r)/', 'Máy chủ', 'The website went down because the server crashed.', 'Trang web đã ngừng hoạt động vì máy chủ bị sập.'],
      ['domain', '/dəˈmeɪn/', 'Tên miền', 'We registered a new domain for our business.', 'Chúng tôi đã đăng ký một miền mới cho doanh nghiệp của mình.'],
      ['url', '/ˌjuː ɑːr ˈel/', 'Địa chỉ web', 'Type the URL into the address bar.', 'Gõ URL vào thanh địa chỉ.'],
      ['bandwidth', '/ˈbændwɪdθ/', 'Băng thông', 'Streaming video uses a lot of bandwidth.', 'Phát video sử dụng rất nhiều băng thông.'],
      ['connection', '/kəˈnekʃn/', 'Kết nối', 'My internet connection is very unstable today.', 'Kết nối internet của tôi hôm nay rất không ổn định.'],
      ['wireless', '/ˈwaɪələs/', 'Không dây', 'This is a wireless keyboard.', 'Đây là một bàn phím không dây.'],
      ['hotspot', '/ˈhɒtspɒt/', 'Điểm phát Wi-Fi', 'I used my phone as a hotspot.', 'Tôi đã sử dụng điện thoại của mình như một điểm phát sóng.'],
      ['broadband', '/ˈbrɔːdbænd/', 'Băng thông rộng', 'We upgraded to a faster broadband connection.', 'Chúng tôi đã nâng cấp lên kết nối băng thông rộng nhanh hơn.'],
      ['modem', '/ˈməʊdem/', 'Modem', 'The technician installed a new modem.', 'Kỹ thuật viên đã lắp đặt một modem mới.'],
      ['ip address', '/ˌaɪ ˈpiː əˌdres/', 'Địa chỉ IP', 'Every device on the network has an IP address.', 'Mỗi thiết bị trên mạng đều có một địa chỉ IP.'],
      ['protocol', '/ˈprəʊtəkɒl/', 'Giao thức', 'HTTP is a common internet protocol.', 'HTTP là một giao thức internet phổ biến.'],
      ['download', '/ˌdaʊnˈləʊd/', 'Tải xuống', 'You can download the app for free.', 'Bạn có thể tải ứng dụng miễn phí.'],
      ['upload', '/ʌpˈləʊd/', 'Tải lên', 'I need to upload these files to the cloud.', 'Tôi cần tải lên những tệp này lên đám mây.'],
      ['streaming', '/ˈstriːmɪŋ/', 'Phát trực tuyến', 'We watched a movie through streaming.', 'Chúng tôi đã xem một bộ phim qua phát trực tuyến.'],
      ['bookmark', '/ˈbʊkmɑːk/', 'Đánh dấu trang', 'I bookmarked the page for later.', 'Tôi đã đánh dấu trang để xem sau.'],
      ['hyperlink', '/ˈhaɪpəlɪŋk/', 'Siêu liên kết', 'Click the hyperlink to visit the site.', 'Nhấn vào liên kết để truy cập trang web.'],
      ['search engine', '/sɜːtʃ ˈendʒɪn/', 'Công cụ tìm kiếm', 'Google is the most popular search engine.', 'Google là công cụ tìm kiếm phổ biến nhất.'],
      ['homepage', '/ˈhəʊmpeɪdʒ/', 'Trang chủ', 'The homepage shows the latest news.', 'Trang chủ hiển thị tin tức mới nhất.'],
      ['cookie', '/ˈkʊki/', 'Cookie (dữ liệu web)', 'The website uses cookies to remember your preferences.', 'Trang web sử dụng cookie để ghi nhớ sở thích của bạn.'],
      ['vpn', '/ˌviː piː ˈen/', 'Mạng riêng ảo', 'She uses a VPN to protect her privacy online.', 'Cô ấy sử dụng VPN để bảo vệ quyền riêng tư trực tuyến.'],
      ['latency', '/ˈleɪtnsi/', 'Độ trễ', 'High latency makes online gaming difficult.', 'Độ trễ cao khiến việc chơi game trực tuyến trở nên khó khăn.'],
      ['ethernet', '/ˈiːθənet/', 'Mạng Ethernet', 'He connected his computer using an Ethernet cable.', 'Anh ấy kết nối máy tính của mình bằng cáp Ethernet.'],
      ['signal', '/ˈsɪgnəl/', 'Tín hiệu', 'The Wi-Fi signal is weak in this room.', 'Tín hiệu Wi-Fi yếu trong phòng này.'],
      ['programming', '/ˈprəʊgræmɪŋ/', 'Lập trình', 'She is learning programming to become a developer.', 'Cô ấy đang học lập trình để trở thành nhà phát triển.'],
      ['code', '/kəʊd/', 'Mã (lập trình)', 'He wrote the code for a new website.', 'Anh ấy đã viết mã cho một trang web mới.'],
      ['coding', '/ˈkəʊdɪŋ/', 'Viết mã', 'Coding requires logical thinking.', 'Lập trình yêu cầu tư duy logic.'],
      ['developer', '/dɪˈveləpə(r)/', 'Nhà phát triển', 'The developer fixed the error quickly.', 'Nhà phát triển đã sửa lỗi nhanh chóng.'],
      ['algorithm', '/ˈælgərɪðəm/', 'Thuật toán', 'The algorithm sorts the data efficiently.', 'Thuật toán sắp xếp dữ liệu một cách hiệu quả.'],
      ['variable', '/ˈveəriəbl/', 'Biến (lập trình)', 'In this line, the variable stores a number.', 'Trong dòng này, biến lưu trữ một số.'],
      ['database', '/ˈdeɪtəbeɪs/', 'Cơ sở dữ liệu', 'The company stores customer information in a database.', 'Công ty lưu trữ thông tin khách hàng trong cơ sở dữ liệu.'],
      ['debug', '/diːˈbʌg/', 'Gỡ lỗi', 'It took hours to debug the program.', 'Mất hàng giờ để gỡ lỗi chương trình.'],
      ['syntax', '/ˈsɪntæks/', 'Cú pháp', 'A syntax error stopped the program from running.', 'Một lỗi cú pháp đã ngăn chương trình chạy.'],
      ['compiler', '/kəmˈpaɪlə(r)/', 'Trình biên dịch', 'The compiler translates code into machine language.', 'Trình biên dịch dịch mã thành ngôn ngữ máy.'],
      ['framework', '/ˈfreɪmwɜːk/', 'Khung phát triển', 'They built the website using a popular framework.', 'Họ đã xây dựng trang web bằng một framework phổ biến.'],
      ['library', '/ˈlaɪbrəri/', 'Thư viện (mã nguồn)', 'This library makes it easier to handle images.', 'Thư viện này giúp dễ dàng xử lý hình ảnh.'],
      ['script', '/skrɪpt/', 'Đoạn mã lệnh', 'I wrote a script to automate the task.', 'Tôi đã viết một kịch bản để tự động hóa nhiệm vụ.'],
      ['source code', '/sɔːs kəʊd/', 'Mã nguồn', 'The source code is available on GitHub.', 'Mã nguồn có sẵn trên GitHub.'],
      ['repository', '/rɪˈpɒzətri/', 'Kho lưu trữ mã', 'He pushed the changes to the repository.', 'Anh ấy đã đẩy các thay đổi lên kho lưu trữ.'],
      ['version control', '/ˈvɜːʃn kənˈtrəʊl/', 'Quản lý phiên bản', 'Git is a common version control system.', 'Git là một hệ thống quản lý phiên bản phổ biến.'],
      ['testing', '/ˈtestɪŋ/', 'Kiểm thử', 'Testing helps find bugs before release.', 'Kiểm thử giúp phát hiện lỗi trước khi phát hành.'],
      ['deployment', '/dɪˈplɔɪmənt/', 'Triển khai', 'The deployment of the new app went smoothly.', 'Việc triển khai ứng dụng mới diễn ra suôn sẻ.'],
      ['api', '/ˌeɪ piː ˈaɪ/', 'Giao diện lập trình ứng dụng', 'The app uses an API to get weather data.', 'Ứng dụng sử dụng API để lấy dữ liệu thời tiết.'],
      ['loop', '/luːp/', 'Vòng lặp', 'The loop repeats the action ten times.', 'Vòng lặp lặp lại hành động mười lần.'],
      ['array', '/əˈreɪ/', 'Mảng (dữ liệu)', 'The array stores a list of numbers.', 'Mảng lưu trữ danh sách các số.'],
      ['object-oriented', '/ˈɒbdʒɪkt ˈɔːriəntɪd/', 'Hướng đối tượng', 'Java is an object-oriented programming language.', 'Java là một ngôn ngữ lập trình hướng đối tượng.'],
      ['query', '/ˈkwɪəri/', 'Truy vấn', 'He wrote a query to find all active users.', 'Anh ấy đã viết một truy vấn để tìm tất cả người dùng đang hoạt động.'],
      ['backend', '/ˈbækend/', 'Phần phụ trợ', 'She works on the backend of the website.', 'Cô ấy làm việc ở phần backend của trang web.'],
      ['frontend', '/ˈfrʌntend/', 'Phần giao diện người dùng', 'The frontend team designed the new layout.', 'Nhóm frontend đã thiết kế giao diện mới.'],
      ['full stack', '/fʊl stæk/', 'Toàn diện (lập trình)', 'He is a full stack developer.', 'Anh ấy là một lập trình viên full stack.'],
      ['open source', '/ˈəʊpən sɔːs/', 'Mã nguồn mở', 'Linux is a well-known open source system.', 'Linux là một hệ thống mã nguồn mở nổi tiếng.'],
      ['command line', '/kəˈmɑːnd laɪn/', 'Dòng lệnh', 'She typed the command into the command line.', 'Cô ấy đã gõ lệnh vào dòng lệnh.'],
      ['ide', '/ˌaɪ diː ˈiː/', 'Môi trường phát triển tích hợp', 'Programmers often write code in an IDE.', 'Các lập trình viên thường viết mã trong một IDE.'],
      ['artificial intelligence', '/ˌɑːtɪˈfɪʃl ɪnˈtelɪdʒəns/', 'Trí tuệ nhân tạo', 'Artificial intelligence is being used in many industries.', 'Trí tuệ nhân tạo đang được sử dụng trong nhiều ngành công nghiệp.'],
      ['machine learning', '/məˈʃiːn ˈlɜːnɪŋ/', 'Học máy', 'Machine learning helps computers learn from data.', 'Học máy giúp máy tính học từ dữ liệu.'],
      ['deep learning', '/diːp ˈlɜːnɪŋ/', 'Học sâu', 'Deep learning improved image recognition accuracy.', 'Học sâu cải thiện độ chính xác của nhận diện hình ảnh.'],
      ['neural network', '/ˈnjʊərəl ˈnetwɜːk/', 'Mạng nơ-ron', 'The neural network was trained on thousands of images.', 'Mạng nơ-ron đã được đào tạo trên hàng nghìn hình ảnh.'],
      ['data', '/ˈdeɪtə/', 'Dữ liệu', 'The company collects data from its users.', 'Công ty thu thập dữ liệu từ người dùng của mình.'],
      ['big data', '/bɪg ˈdeɪtə/', 'Dữ liệu lớn', 'Big data helps businesses understand customer behavior.', 'Dữ liệu lớn giúp doanh nghiệp hiểu hành vi của khách hàng.'],
      ['data mining', '/ˈdeɪtə ˈmaɪnɪŋ/', 'Khai thác dữ liệu', 'Data mining reveals hidden patterns in information.', 'Khai thác dữ liệu tiết lộ các mẫu ẩn trong thông tin.'],
      ['data analysis', '/ˈdeɪtə əˈnæləsɪs/', 'Phân tích dữ liệu', 'Data analysis helped the team make better decisions.', 'Phân tích dữ liệu đã giúp nhóm đưa ra quyết định tốt hơn.'],
      ['dataset', '/ˈdeɪtəset/', 'Bộ dữ liệu', 'The researchers used a large dataset for the study.', 'Các nhà nghiên cứu đã sử dụng một tập dữ liệu lớn cho nghiên cứu.'],
      ['chatbot', '/ˈtʃætbɒt/', 'Trợ lý trò chuyện ảo', 'The chatbot answers customer questions instantly.', 'Chatbot trả lời câu hỏi của khách hàng ngay lập tức.'],
      ['prediction', '/prɪˈdɪkʃn/', 'Dự đoán', 'The model made an accurate prediction of sales.', 'Mô hình đã đưa ra dự đoán chính xác về doanh số.'],
      ['model', '/ˈmɒdl/', 'Mô hình', 'They trained a model to detect fraud.', 'Họ đã đào tạo một mô hình để phát hiện gian lận.'],
      ['training data', '/ˈtreɪnɪŋ ˈdeɪtə/', 'Dữ liệu huấn luyện', 'More training data improves the model\'s accuracy.', 'Dữ liệu đào tạo nhiều hơn cải thiện độ chính xác của mô hình.'],
      ['bias', '/ˈbaɪəs/', 'Thiên vị (thuật toán)', 'Researchers try to reduce bias in AI systems.', 'Các nhà nghiên cứu cố gắng giảm thiểu thiên lệch trong các hệ thống AI.'],
      ['pattern recognition', '/ˈpætn ˌrekəgˈnɪʃn/', 'Nhận dạng mẫu', 'Pattern recognition is used in fraud detection.', 'Nhận diện mẫu được sử dụng trong phát hiện gian lận.'],
      ['natural language processing', '/ˈnætʃrəl ˈlæŋgwɪdʒ ˈprəʊsesɪŋ/', 'Xử lý ngôn ngữ tự nhiên', 'Natural language processing lets computers understand text.', 'Xử lý ngôn ngữ tự nhiên cho phép máy tính hiểu văn bản.'],
      ['speech recognition', '/spiːtʃ ˌrekəgˈnɪʃn/', 'Nhận dạng giọng nói', 'Speech recognition allows you to control devices by voice.', 'Nhận diện giọng nói cho phép bạn điều khiển thiết bị bằng giọng nói.'],
      ['facial recognition', '/ˈfeɪʃl ˌrekəgˈnɪʃn/', 'Nhận dạng khuôn mặt', 'Facial recognition unlocks the phone automatically.', 'Nhận diện khuôn mặt mở khóa điện thoại tự động.'],
      ['analytics', '/ˌænəˈlɪtɪks/', 'Phân tích dữ liệu', 'The team uses analytics to track website traffic.', 'Nhóm sử dụng phân tích để theo dõi lưu lượng truy cập website.'],
      ['data science', '/ˈdeɪtə ˈsaɪəns/', 'Khoa học dữ liệu', 'Data science combines statistics and programming.', 'Khoa học dữ liệu kết hợp thống kê và lập trình.'],
      ['data visualization', '/ˈdeɪtə ˌvɪʒuəlaɪˈzeɪʃn/', 'Trực quan hóa dữ liệu', 'Data visualization makes complex numbers easy to understand.', 'Trực quan hóa dữ liệu giúp các con số phức tạp dễ hiểu hơn.'],
      ['predictive analytics', '/prɪˈdɪktɪv ˌænəˈlɪtɪks/', 'Phân tích dự đoán', 'Predictive analytics forecasts future customer demand.', 'Phân tích dự đoán dự báo nhu cầu của khách hàng trong tương lai.'],
      ['data privacy', '/ˈdeɪtə ˈprɪvəsi/', 'Quyền riêng tư dữ liệu', 'Data privacy laws protect users\' personal information.', 'Luật bảo mật dữ liệu bảo vệ thông tin cá nhân của người dùng.'],
      ['data breach', '/ˈdeɪtə briːtʃ/', 'Vi phạm dữ liệu', 'The company suffered a serious data breach.', 'Công ty đã gặp phải một vụ rò rỉ dữ liệu nghiêm trọng.'],
      ['algorithmic', '/ˌælgəˈrɪðmɪk/', 'Thuộc về thuật toán', 'The app uses algorithmic recommendations.', 'Ứng dụng sử dụng các gợi ý theo thuật toán.'],
      ['computer vision', '/kəmˈpjuːtə(r) ˈvɪʒn/', 'Thị giác máy tính', 'Computer vision helps self-driving cars see the road.', 'Thị giác máy tính giúp xe tự lái nhìn thấy đường.'],
      ['robotics engineer', '/rəʊˈbɒtɪks ˌendʒɪˈnɪə(r)/', 'Kỹ sư robot học', 'A robotics engineer designed the new AI robot.', 'Một kỹ sư robot đã thiết kế con robot AI mới.'],
      ['generative ai', '/ˈdʒenərətɪv ˌeɪ ˈaɪ/', 'Trí tuệ nhân tạo tạo sinh', 'Generative AI can create text, images, and music.', 'AI sinh tạo có thể tạo ra văn bản, hình ảnh và âm nhạc.'],
      ['turing test', '/ˈtjʊərɪŋ test/', 'Phép thử Turing', 'The chatbot passed a simple Turing test.', 'Chatbot đã vượt qua một bài kiểm tra Turing đơn giản.'],
      ['cybersecurity', '/ˌsaɪbəsɪˈkjʊərəti/', 'An ninh mạng', 'Cybersecurity is essential to protect against hacking.', 'An ninh mạng là rất quan trọng để bảo vệ chống lại việc hack.'],
      ['hacker', '/ˈhækə(r)/', 'Tin tặc', 'A hacker tried to break into the company\'s system.', 'Một hacker đã cố gắng xâm nhập vào hệ thống của công ty.'],
      ['hacking', '/ˈhækɪŋ/', 'Hành vi xâm nhập trái phép', 'Hacking is a serious crime in most countries.', 'Hack là một tội phạm nghiêm trọng ở hầu hết các quốc gia.'],
      ['virus', '/ˈvaɪrəs/', 'Virus (máy tính)', 'The virus infected hundreds of computers.', 'Virus đã lây nhiễm hàng trăm máy tính.'],
      ['malware', '/ˈmælweə(r)/', 'Phần mềm độc hại', 'This link may contain malware, so don\'t click it.', 'Liên kết này có thể chứa phần mềm độc hại, vì vậy đừng nhấp vào nó.'],
      ['spyware', '/ˈspaɪweə(r)/', 'Phần mềm gián điệp', 'Spyware secretly collects your personal information.', 'Phần mềm gián điệp thu thập bí mật thông tin cá nhân của bạn.'],
      ['ransomware', '/ˈrænsəmweə(r)/', 'Phần mềm tống tiền', 'Ransomware locked all the files on her computer.', 'Phần mềm tống tiền đã khóa tất cả các tệp trên máy tính của cô ấy.'],
      ['phishing', '/ˈfɪʃɪŋ/', 'Lừa đảo trực tuyến', 'Don\'t click links in phishing emails.', 'Đừng nhấp vào các liên kết trong email lừa đảo.'],
      ['encryption', '/ɪnˈkrɪpʃn/', 'Mã hóa', 'Encryption keeps your messages private and secure.', 'Mã hóa giữ cho tin nhắn của bạn riêng tư và an toàn.'],
      ['password', '/ˈpɑːswɜːd/', 'Mật khẩu', 'Please enter your password to log in.', 'Vui lòng nhập mật khẩu của bạn để đăng nhập.'],
      ['authentication', '/ɔːˌθentɪˈkeɪʃn/', 'Xác thực', 'Authentication confirms your identity before login.', 'Xác thực xác nhận danh tính của bạn trước khi đăng nhập.'],
      ['data leak', '/ˈdeɪtə liːk/', 'Rò rỉ dữ liệu', 'The data leak exposed thousands of email addresses.', 'Rò rỉ dữ liệu đã phơi bày hàng ngàn địa chỉ email.'],
      ['two-factor authentication', '/tuː ˈfæktə(r) ɔːˌθentɪˈkeɪʃn/', 'Xác thực hai yếu tố', 'Two-factor authentication adds an extra layer of security.', 'Xác thực hai yếu tố thêm một lớp bảo mật bổ sung.'],
      ['cyberattack', '/ˈsaɪbərətæk/', 'Tấn công mạng', 'The bank suffered a major cyberattack last year.', 'Ngân hàng đã chịu một cuộc tấn công mạng lớn vào năm ngoái.'],
      ['vulnerability', '/ˌvʌlnərəˈbɪləti/', 'Lỗ hổng bảo mật', 'Developers fixed a security vulnerability in the app.', 'Các nhà phát triển đã khắc phục một lỗ hổng bảo mật trong ứng dụng.'],
      ['trojan horse', '/ˈtrəʊdʒən hɔːs/', 'Virus Trojan', 'The Trojan horse disguised itself as a normal file.', 'Ngựa thành Troy đã ngụy trang thành một tệp bình thường.'],
      ['spam', '/spæm/', 'Thư rác', 'My inbox is full of spam emails.', 'Hộp thư đến của tôi đầy email rác.'],
      ['identity theft', '/aɪˈdentəti θeft/', 'Đánh cắp danh tính', 'Identity theft can cause serious financial damage.', 'Trộm danh tính có thể gây thiệt hại tài chính nghiêm trọng.'],
      ['secure', '/sɪˈkjʊə(r)/', 'Bảo mật, an toàn', 'Make sure your Wi-Fi network is secure.', 'Hãy chắc chắn rằng mạng Wi-Fi của bạn được bảo mật.'],
      ['breach', '/briːtʃ/', 'Sự xâm phạm', 'The security breach affected millions of users.', 'Lỗ hổng bảo mật đã ảnh hưởng đến hàng triệu người dùng.'],
      ['biometric', '/ˌbaɪəʊˈmetrɪk/', 'Sinh trắc học', 'Biometric login uses your fingerprint or face.', 'Đăng nhập sinh trắc học sử dụng dấu vân tay hoặc khuôn mặt của bạn.'],
      ['data encryption', '/ˈdeɪtə ɪnˈkrɪpʃn/', 'Mã hóa dữ liệu', 'Data encryption protects information from hackers.', 'Mã hóa dữ liệu bảo vệ thông tin khỏi tin tặc.'],
      ['firewall protection', '/ˈfaɪəwɔːl prəˈtekʃn/', 'Bảo vệ bằng tường lửa', 'Firewall protection stops unauthorized network access.', 'Bảo vệ tường lửa ngăn chặn truy cập mạng trái phép.'],
      ['cybercrime', '/ˈsaɪbəkraɪm/', 'Tội phạm mạng', 'Cybercrime has increased rapidly in recent years.', 'Tội phạm mạng đã gia tăng nhanh chóng trong những năm gần đây.'],
      ['cloud', '/klaʊd/', 'Đám mây (lưu trữ)', 'We save our photos to the cloud.', 'Chúng tôi lưu ảnh của mình lên đám mây.'],
      ['cloud storage', '/klaʊd ˈstɔːrɪdʒ/', 'Lưu trữ đám mây', 'Cloud storage lets you access files from anywhere.', 'Lưu trữ đám mây cho phép bạn truy cập tệp từ bất kỳ đâu.'],
      ['cloud computing', '/klaʊd kəmˈpjuːtɪŋ/', 'Điện toán đám mây', 'Cloud computing allows businesses to store data online.', 'Điện toán đám mây cho phép các doanh nghiệp lưu trữ dữ liệu trực tuyến.'],
      ['server farm', '/ˈsɜːvə(r) fɑːm/', 'Cụm máy chủ', 'The company built a huge server farm.', 'Công ty đã xây dựng một trang trại máy chủ khổng lồ.'],
      ['data center', '/ˈdeɪtə ˈsentə(r)/', 'Trung tâm dữ liệu', 'The data center houses thousands of servers.', 'Trung tâm dữ liệu chứa hàng ngàn máy chủ.'],
      ['synchronize (sync)', '/ˈsɪŋkrənaɪz/', 'Đồng bộ hóa', 'My phone will sync with the cloud automatically.', 'Điện thoại của tôi sẽ tự động đồng bộ với đám mây.'],
      ['file sharing', '/faɪl ˈʃeərɪŋ/', 'Chia sẻ tệp', 'File sharing makes teamwork much easier.', 'Chia sẻ tệp làm cho công việc nhóm dễ dàng hơn nhiều.'],
      ['virtual machine', '/ˈvɜːtʃuəl məˈʃiːn/', 'Máy ảo', 'He runs a virtual machine to test new software.', 'Anh ấy chạy một máy ảo để thử nghiệm phần mềm mới.'],
      ['saas (software as a service)', '/es eɪ ˈes/', 'Phần mềm dưới dạng dịch vụ', 'Many companies now use SaaS products instead of installed software.', 'Nhiều công ty hiện nay sử dụng sản phẩm SaaS thay vì phần mềm cài đặt.'],
      ['storage capacity', '/ˈstɔːrɪdʒ kəˈpæsəti/', 'Dung lượng lưu trữ', 'Check the storage capacity before buying a new phone.', 'Kiểm tra dung lượng lưu trữ trước khi mua điện thoại mới.'],
      ['remote access', '/rɪˈməʊt ˈækses/', 'Truy cập từ xa', 'Remote access lets employees work from home.', 'Truy cập từ xa cho phép nhân viên làm việc từ xa.'],
      ['migration', '/maɪˈgreɪʃn/', 'Di chuyển dữ liệu', 'The company completed its data migration to the cloud.', 'Công ty đã hoàn tất việc di chuyển dữ liệu lên đám mây.'],
      ['scalability', '/ˌskeɪləˈbɪləti/', 'Khả năng mở rộng', 'Cloud services offer great scalability for growing businesses.', 'Dịch vụ đám mây cung cấp khả năng mở rộng tuyệt vời cho các doanh nghiệp đang phát triển.'],
      ['hosting', '/ˈhəʊstɪŋ/', 'Lưu trữ web', 'We chose a reliable web hosting provider.', 'Chúng tôi đã chọn một nhà cung cấp dịch vụ lưu trữ web đáng tin cậy.'],
      ['uptime', '/ˈʌptaɪm/', 'Thời gian hoạt động', 'The server has 99.9% uptime.', 'Máy chủ có thời gian hoạt động 99,9%.'],
      ['downtime', '/ˈdaʊntaɪm/', 'Thời gian ngừng hoạt động', 'The website had two hours of downtime yesterday.', 'Trang web đã bị ngừng hoạt động hai giờ hôm qua.'],
      ['redundancy', '/rɪˈdʌndənsi/', 'Dự phòng', 'Redundancy ensures the system stays online during failures.', 'Tính năng dự phòng đảm bảo hệ thống vẫn hoạt động trong trường hợp xảy ra sự cố.'],
      ['cloud service', '/klaʊd ˈsɜːvɪs/', 'Dịch vụ đám mây', 'We use a cloud service to back up our files.', 'Chúng tôi sử dụng dịch vụ đám mây để sao lưu các tệp của mình.'],
      ['data storage', '/ˈdeɪtə ˈstɔːrɪdʒ/', 'Lưu trữ dữ liệu', 'Data storage costs have decreased over the years.', 'Chi phí lưu trữ dữ liệu đã giảm trong những năm qua.'],
      ['smartphone', '/ˈsmɑːtfəʊn/', 'Điện thoại thông minh', 'He uses his smartphone to check emails.', 'Anh ấy sử dụng điện thoại thông minh của mình để kiểm tra email.'],
      ['mobile app', '/ˈməʊbaɪl æp/', 'Ứng dụng di động', 'I downloaded a mobile app for online banking.', 'Tôi đã tải xuống một ứng dụng di động cho ngân hàng trực tuyến.'],
      ['touchscreen', '/ˈtʌtʃskriːn/', 'Màn hình cảm ứng', 'The touchscreen responds quickly to taps.', 'Màn hình cảm ứng phản hồi nhanh chóng với các cú chạm.'],
      ['notification', '/ˌnəʊtɪfɪˈkeɪʃn/', 'Thông báo', 'I received a notification about the new update.', 'Tôi đã nhận được thông báo về bản cập nhật mới.'],
      ['sim card', '/sɪm kɑːd/', 'Thẻ SIM', 'Insert the SIM card to activate your phone.', 'Chèn thẻ SIM để kích hoạt điện thoại của bạn.'],
      ['camera', '/ˈkæmərə/', 'Máy ảnh', 'This phone has an excellent camera.', 'Điện thoại này có camera xuất sắc.'],
      ['battery life', '/ˈbætri laɪf/', 'Thời lượng pin', 'The battery life of this phone is impressive.', 'Thời gian sử dụng pin của điện thoại này rất ấn tượng.'],
      ['gps', '/ˌdʒiː piː ˈes/', 'Hệ thống định vị toàn cầu', 'GPS helps you find the fastest route.', 'GPS giúp bạn tìm ra lộ trình nhanh nhất.'],
      ['app store', '/æp stɔː(r)/', 'Cửa hàng ứng dụng', 'You can download games from the app store.', 'Bạn có thể tải xuống trò chơi từ cửa hàng ứng dụng.'],
      ['text message', '/tekst ˈmesɪdʒ/', 'Tin nhắn văn bản', 'She sent me a text message this morning.', 'Cô ấy đã gửi cho tôi một tin nhắn sáng nay.'],
      ['wireless charging', '/ˈwaɪələs ˈtʃɑːdʒɪŋ/', 'Sạc không dây', 'This phone supports wireless charging.', 'Chiếc điện thoại này hỗ trợ sạc không dây.'],
      ['screen resolution', '/skriːn ˌrezəˈluːʃn/', 'Độ phân giải màn hình', 'High screen resolution makes images look sharper.', 'Độ phân giải màn hình cao làm cho hình ảnh sắc nét hơn.'],
      ['fingerprint scanner', '/ˈfɪŋgəprɪnt ˈskænə(r)/', 'Máy quét vân tay', 'Use the fingerprint scanner to unlock your phone.', 'Sử dụng máy quét vân tay để mở khóa điện thoại của bạn.'],
      ['mobile data', '/ˈməʊbaɪl ˈdeɪtə/', 'Dữ liệu di động', 'I turned off mobile data to save my plan.', 'Tôi đã tắt dữ liệu di động để tiết kiệm gói cước của mình.'],
      ['portable', '/ˈpɔːtəbl/', 'Di động, có thể mang theo', 'This portable charger is very convenient for travel.', 'Cục sạc di động này rất tiện lợi cho việc du lịch.'],
      ['voice assistant', '/vɔɪs əˈsɪstənt/', 'Trợ lý giọng nói', 'I asked the voice assistant to set an alarm.', 'Tôi đã nhờ trợ lý giọng nói đặt một báo thức.'],
      ['bluetooth', '/ˈbluːtuːθ/', 'Bluetooth', 'Connect your headphones via Bluetooth.', 'Kết nối tai nghe của bạn qua Bluetooth.'],
      ['airplane mode', '/ˈeəpleɪn məʊd/', 'Chế độ máy bay', 'Turn on airplane mode during the flight.', 'Bật chế độ máy bay trong suốt chuyến bay.'],
      ['social media', '/ˈsəʊʃl ˈmiːdiə/', 'Mạng xã hội', 'Many people spend hours on social media every day.', 'Nhiều người dành hàng giờ trên mạng xã hội mỗi ngày.'],
      ['platform', '/ˈplætfɔːm/', 'Nền tảng', 'Instagram is a popular photo-sharing platform.', 'Instagram là một nền tảng chia sẻ ảnh phổ biến.'],
      ['blog', '/blɒg/', 'Nhật ký trực tuyến', 'She writes a travel blog in her free time.', 'Cô ấy viết một blog du lịch trong thời gian rảnh.'],
      ['post', '/pəʊst/', 'Bài đăng', 'He shared a new post about his trip.', 'Anh ấy đã chia sẻ một bài đăng mới về chuyến đi của mình.'],
      ['follower', '/ˈfɒləʊə(r)/', 'Người theo dõi', 'The influencer has millions of followers.', 'Người có ảnh hưởng này có hàng triệu người theo dõi.'],
      ['hashtag', '/ˈhæʃtæg/', 'Thẻ gắn từ khóa', 'Add a hashtag to reach more people.', 'Thêm một hashtag để tiếp cận nhiều người hơn.'],
      ['feed', '/fiːd/', 'Bảng tin', 'I scrolled through my feed this morning.', 'Tôi đã cuộn qua dòng thời gian của mình sáng nay.'],
      ['profile', '/ˈprəʊfaɪl/', 'Hồ sơ cá nhân', 'Update your profile picture on the app.', 'Cập nhật ảnh đại diện của bạn trên ứng dụng.'],
      ['content', '/ˈkɒntent/', 'Nội dung', 'She creates content for a tech YouTube channel.', 'Cô ấy tạo nội dung cho một kênh YouTube về công nghệ.'],
      ['influencer', '/ˈɪnfluənsə(r)/', 'Người có sức ảnh hưởng', 'The brand worked with an influencer to promote the product.', 'Thương hiệu đã hợp tác với một người có ảnh hưởng để quảng bá sản phẩm.'],
      ['livestream', '/ˈlaɪvstriːm/', 'Phát trực tiếp', 'We watched the concert through a livestream.', 'Chúng tôi đã xem buổi hòa nhạc qua livestream.'],
      ['comment', '/ˈkɒment/', 'Bình luận', 'He left a positive comment on my post.', 'Anh ấy đã để lại một bình luận tích cực trên bài đăng của tôi.'],
      ['share', '/ʃeə(r)/', 'Chia sẻ', 'Please share this article with your friends.', 'Xin hãy chia sẻ bài viết này với bạn bè của bạn.'],
      ['viral', '/ˈvaɪrəl/', 'Lan truyền nhanh', 'The video went viral within a few hours.', 'Video đã trở nên viral chỉ trong vài giờ.'],
      ['e-commerce', '/ˌiː ˈkɒmɜːs/', 'Thương mại điện tử', 'E-commerce has grown rapidly in recent years.', 'Thương mại điện tử đã phát triển nhanh chóng trong những năm gần đây.'],
      ['online shopping', '/ˈɒnlaɪn ˈʃɒpɪŋ/', 'Mua sắm trực tuyến', 'Online shopping is convenient and saves time.', 'Mua sắm trực tuyến rất tiện lợi và tiết kiệm thời gian.'],
      ['digital marketing', '/ˈdɪdʒɪtl ˈmɑːkɪtɪŋ/', 'Tiếp thị kỹ thuật số', 'The company invests heavily in digital marketing.', 'Công ty đầu tư mạnh vào tiếp thị kỹ thuật số.'],
      ['seo', '/ˌes iː ˈəʊ/', 'Tối ưu hóa công cụ tìm kiếm', 'Good SEO helps your website rank higher on Google.', 'SEO tốt giúp website của bạn xếp hạng cao hơn trên Google.'],
      ['web design', '/web dɪˈzaɪn/', 'Thiết kế web', 'She studies web design at university.', 'Cô ấy học thiết kế web tại trường đại học.'],
      ['video game', '/ˈvɪdiəʊ geɪm/', 'Trò chơi điện tử', 'He plays video games every weekend.', 'Anh ấy chơi game mỗi cuối tuần.'],
      ['console', '/ˈkɒnsəʊl/', 'Máy chơi game', 'She bought a new gaming console.', 'Cô ấy đã mua một máy chơi game mới.'],
      ['graphics', '/ˈgræfɪks/', 'Đồ họa', 'The graphics in this game are amazing.', 'Đồ họa trong trò chơi này thật tuyệt vời.'],
      ['animation', '/ˌænɪˈmeɪʃn/', 'Hoạt hình', 'The film uses 3D animation.', 'Bộ phim sử dụng hoạt hình 3D.'],
      ['virtual reality', '/ˈvɜːtʃuəl riˈæləti/', 'Thực tế ảo', 'Virtual reality is popular in the gaming industry.', 'Thực tế ảo đang trở nên phổ biến trong ngành công nghiệp game.'],
      ['augmented reality', '/ɔːgˈmentɪd riˈæləti/', 'Thực tế tăng cường', 'The app uses augmented reality to show furniture in your room.', 'Ứng dụng sử dụng thực tế tăng cường để hiển thị đồ nội thất trong phòng của bạn.'],
      ['multiplayer', '/ˈmʌltipleɪə(r)/', 'Nhiều người chơi', 'This is a multiplayer online game.', 'Đây là một trò chơi trực tuyến nhiều người chơi.'],
      ['streaming platform', '/ˈstriːmɪŋ ˈplætfɔːm/', 'Nền tảng phát trực tuyến', 'Netflix is a popular streaming platform.', 'Netflix là một nền tảng phát trực tuyến phổ biến.'],
      ['resolution', '/ˌrezəˈluːʃn/', 'Độ phân giải', 'The TV supports 4K resolution.', 'TV hỗ trợ độ phân giải 4K.'],
      ['headset', '/ˈhedset/', 'Tai nghe (VR/nghe nhìn)', 'He wore a VR headset to play the game.', 'Anh ấy đeo kính VR để chơi trò chơi.'],
      ['simulation', '/ˌsɪmjuˈleɪʃn/', 'Mô phỏng', 'Pilots train using flight simulation software.', 'Phi công được đào tạo bằng phần mềm mô phỏng bay.'],
      ['avatar', '/ˈævətɑː(r)/', 'Nhân vật đại diện', 'She created a colorful avatar for the game.', 'Cô ấy đã tạo một hình đại diện đầy màu sắc cho trò chơi.'],
      ['joystick', '/ˈdʒɔɪstɪk/', 'Cần điều khiển', 'He controls the game with a joystick.', 'Anh ấy điều khiển trò chơi bằng một cần điều khiển.'],
      ['frame rate', '/freɪm reɪt/', 'Tốc độ khung hình', 'A high frame rate makes the game feel smoother.', 'Tốc độ khung hình cao làm cho trò chơi cảm giác mượt mà hơn.'],
      ['esports', '/ˈiːspɔːts/', 'Thể thao điện tử', 'Esports tournaments attract millions of viewers.', 'Các giải đấu thể thao điện tử thu hút hàng triệu người xem.'],
      ['robotics', '/rəʊˈbɒtɪks/', 'Robot học', 'She studies robotics at university.', 'Cô ấy học robot tại trường đại học.'],
      ['robot', '/ˈrəʊbɒt/', 'Người máy', 'The robot can perform simple tasks automatically.', 'Robot có thể thực hiện các nhiệm vụ đơn giản một cách tự động.'],
      ['internet of things (iot)', '/ˈɪntənet əv θɪŋz/', 'Internet vạn vật', 'IoT connects everyday devices to the internet.', 'IoT kết nối các thiết bị hàng ngày với internet.'],
      ['blockchain', '/ˈblɒktʃeɪn/', 'Chuỗi khối', 'Blockchain technology supports many cryptocurrencies.', 'Công nghệ blockchain hỗ trợ nhiều loại tiền điện tử.'],
      ['cryptocurrency', '/ˌkrɪptəʊˈkʌrənsi/', 'Tiền điện tử', 'Cryptocurrency prices can change very quickly.', 'Giá tiền điện tử có thể thay đổi rất nhanh.'],
      ['bitcoin', '/ˈbɪtkɔɪn/', 'Bitcoin', 'He invested some money in Bitcoin last year.', 'Anh ấy đã đầu tư một số tiền vào Bitcoin năm ngoái.'],
      ['nanotechnology', '/ˌnænəʊtekˈnɒlədʒi/', 'Công nghệ nano', 'Nanotechnology is used in modern medicine.', 'Công nghệ nano được sử dụng trong y học hiện đại.'],
      ['biotechnology', '/ˌbaɪəʊtekˈnɒlədʒi/', 'Công nghệ sinh học', 'Biotechnology helps develop new vaccines.', 'Công nghệ sinh học giúp phát triển các loại vắc xin mới.'],
      ['3d printing', '/ˌθriː ˈdiː ˈprɪntɪŋ/', 'In 3D', '3D printing can create complex physical objects.', 'In 3D có thể tạo ra các vật thể vật lý phức tạp.'],
      ['drone', '/drəʊn/', 'Máy bay không người lái', 'The drone captured stunning aerial photos.', 'Máy bay không người lái đã chụp được những bức ảnh trên không tuyệt đẹp.'],
      ['wearable technology', '/ˈweərəbl tekˈnɒlədʒi/', 'Công nghệ đeo được', 'Wearable technology tracks your health data.', 'Công nghệ đeo được theo dõi dữ liệu sức khỏe của bạn.'],
      ['smart home', '/smɑːt həʊm/', 'Nhà thông minh', 'Their smart home can be controlled by voice.', 'Ngôi nhà thông minh của họ có thể được điều khiển bằng giọng nói.'],
      ['autonomous vehicle', '/ɔːˈtɒnəməs ˈviːəkl/', 'Xe tự lái', 'The company is testing an autonomous vehicle.', 'Công ty đang thử nghiệm một phương tiện tự hành.'],
      ['quantum computing', '/ˈkwɒntəm kəmˈpjuːtɪŋ/', 'Điện toán lượng tử', 'Quantum computing could solve complex problems faster.', 'Máy tính lượng tử có thể giải quyết các vấn đề phức tạp nhanh hơn.'],
      ['semiconductor', '/ˌsemikənˈdʌktə(r)/', 'Chất bán dẫn', 'Semiconductors are essential for making computer chips.', 'Bán dẫn là thiết yếu để sản xuất chip máy tính.'],
      ['digital twin', '/ˈdɪdʒɪtl twɪn/', 'Bản sao kỹ thuật số', 'Engineers use a digital twin to test the design.', 'Kỹ sư sử dụng bản sao kỹ thuật số để kiểm tra thiết kế.'],
      ['edge computing', '/edʒ kəmˈpjuːtɪŋ/', 'Điện toán biên', 'Edge computing processes data closer to its source.', 'Điện toán biên xử lý dữ liệu gần với nguồn gốc của nó hơn.'],
      ['metaverse', '/ˈmetəvɜːs/', 'Vũ trụ ảo', 'Companies are investing heavily in the metaverse.', 'Các công ty đang đầu tư mạnh vào metaverse.'],
      ['automation technology', '/ˌɔːtəˈmeɪʃn tekˈnɒlədʒi/', 'Công nghệ tự động hóa', 'Automation technology has transformed manufacturing.', 'Công nghệ tự động hóa đã biến đổi ngành sản xuất.'],
      ['sustainable technology', '/səˈsteɪnəbl tekˈnɒlədʒi/', 'Công nghệ bền vững', 'Sustainable technology reduces environmental damage.', 'Công nghệ bền vững giảm thiểu thiệt hại cho môi trường.'],
      ['renewable energy tech', '/rɪˈnjuːəbl ˈenədʒi tek/', 'Công nghệ năng lượng tái tạo', 'Renewable energy tech includes solar and wind power.', 'Công nghệ năng lượng tái tạo bao gồm năng lượng mặt trời và gió.'],
      ['satellite', '/ˈsætəlaɪt/', 'Vệ tinh', 'The satellite provides internet access to remote areas.', 'Vệ tinh cung cấp truy cập internet cho các khu vực xa xôi.'],
      ['space technology', '/speɪs tekˈnɒlədʒi/', 'Công nghệ vũ trụ', 'Space technology has advanced rapidly in recent decades.', 'Công nghệ không gian đã phát triển nhanh chóng trong những thập kỷ gần đây.'],
      ['exoskeleton', '/ˌeksəʊˈskelɪtn/', 'Bộ xương ngoài hỗ trợ', 'The exoskeleton helps workers lift heavy objects.', 'Khung xương ngoài giúp công nhân nâng các vật nặng.'],
      ['holography', '/hɒˈlɒgrəfi/', 'Kỹ thuật ảnh ba chiều', 'Holography could change how we watch movies.', 'Holography có thể thay đổi cách chúng ta xem phim.'],
      ['it support', '/ˌaɪ ˈtiː səˈpɔːt/', 'Hỗ trợ công nghệ thông tin', 'Contact IT support if your computer stops working.', 'Liên hệ với bộ phận hỗ trợ IT nếu máy tính của bạn ngừng hoạt động.'],
      ['technician', '/tekˈnɪʃn/', 'Kỹ thuật viên', 'The technician repaired the broken printer.', 'Kỹ thuật viên đã sửa chữa máy in bị hỏng.'],
      ['engineer', '/ˌendʒɪˈnɪə(r)/', 'Kỹ sư', 'She works as a software engineer.', 'Cô ấy làm việc như một kỹ sư phần mềm.'],
      ['project manager', '/ˈprɒdʒekt ˈmænɪdʒə(r)/', 'Quản lý dự án', 'The project manager organized the whole team.', 'Quản lý dự án đã tổ chức toàn bộ đội ngũ.'],
      ['user', '/ˈjuːzə(r)/', 'Người dùng', 'The app has over one million users.', 'Ứng dụng có hơn một triệu người dùng.'],
      ['client', '/ˈklaɪənt/', 'Khách hàng / máy khách', 'The client requested a new feature.', 'Khách hàng đã yêu cầu một tính năng mới.'],
      ['vendor', '/ˈvendə(r)/', 'Nhà cung cấp', 'We chose a reliable software vendor.', 'Chúng tôi đã chọn một nhà cung cấp phần mềm đáng tin cậy.'],
      ['subscription', '/səbˈskrɪpʃn/', 'Đăng ký thuê bao', 'I pay a monthly subscription for this service.', 'Tôi trả một khoản phí hàng tháng cho dịch vụ này.'],
      ['maintenance', '/ˈmeɪntənəns/', 'Bảo trì', 'The system is under maintenance right now.', 'Hệ thống hiện đang bảo trì.'],
      ['troubleshooting', '/ˈtrʌblʃuːtɪŋ/', 'Khắc phục sự cố', 'Troubleshooting helped us find the network problem.', 'Việc khắc phục sự cố đã giúp chúng tôi tìm ra vấn đề mạng.'],
    ],
  },
];
