import { CefrLevel } from '@prisma/client';
import type { VocabularySeedSet } from './vocabulary-tech-sets';

export const DAILY_VOCABULARY_SET: VocabularySeedSet = {
  slug: 'giao-tiep-hang-ngay',
  title: 'Giao tiếp hằng ngày',
  description:
    '500 từ vựng giao tiếp thiết yếu: chào hỏi, gia đình, thời gian, cảm xúc, nhà cửa, ăn uống, công việc và hội thoại hằng ngày',
  icon: 'message-circle',
  color: 'purple',
  cefrLevel: CefrLevel.A1,
  topic: 'Cuộc sống',
  isFeatured: true,
  sortOrder: 2,
  words: [
      ['hello', '/həˈləʊ/', 'xin chào', 'Hello, how are you today?', 'Xin chào, hôm nay bạn khỏe không?'],
      ['hi', '/haɪ/', 'chào (thân mật)', 'Hi! Long time no see.', 'Chào! Lâu rồi không gặp.'],
      ['good morning', '/ɡʊd ˈmɔːnɪŋ/', 'chào buổi sáng', 'Good morning, everyone!', 'Chào buổi sáng, mọi người!'],
      ['good afternoon', '/ɡʊd ˌɑːftəˈnuːn/', 'chào buổi chiều', 'Good afternoon, sir.', 'Chào buổi chiều, thưa ông.'],
      ['good evening', '/ɡʊd ˈiːvnɪŋ/', 'chào buổi tối', 'Good evening, ladies and gentlemen.', 'Chào buổi tối, quý ông quý bà.'],
      ['good night', '/ɡʊd naɪt/', 'chúc ngủ ngon', 'Good night, sleep well.', 'Chúc ngủ ngon, ngủ ngon nhé.'],
      ['goodbye', '/ˌɡʊdˈbaɪ/', 'tạm biệt', 'Goodbye, see you tomorrow.', 'Tạm biệt, hẹn gặp lại ngày mai.'],
      ['see you later', '/siː juː ˈleɪtə/', 'hẹn gặp lại', 'See you later, take care.', 'Hẹn gặp lại, bảo trọng nhé.'],
      ['how are you', '/haʊ ɑː juː/', 'bạn khỏe không', 'How are you doing today?', 'Hôm nay bạn thế nào?'],
      ['fine', '/faɪn/', 'khỏe, ổn', 'I\'m fine, thank you.', 'Tôi khỏe, cảm ơn bạn.'],
      ['thank you', '/ˈθæŋk juː/', 'cảm ơn', 'Thank you for your help.', 'Cảm ơn bạn đã giúp đỡ.'],
      ['thanks', '/θæŋks/', 'cảm ơn (thân mật)', 'Thanks a lot!', 'Cảm ơn nhiều!'],
      ['you\'re welcome', '/jʊə ˈwelkəm/', 'không có gì', 'You\'re welcome, anytime.', 'Không có gì, lúc nào cũng được.'],
      ['please', '/pliːz/', 'làm ơn, xin vui lòng', 'Please close the door.', 'Làm ơn đóng cửa lại.'],
      ['sorry', '/ˈsɒri/', 'xin lỗi', 'I\'m sorry for being late.', 'Xin lỗi vì tôi đến muộn.'],
      ['excuse me', '/ɪkˈskjuːz miː/', 'xin lỗi (gây chú ý)', 'Excuse me, where is the bathroom?', 'Xin lỗi, phòng vệ sinh ở đâu?'],
      ['nice to meet you', '/naɪs tuː miːt juː/', 'rất vui được gặp bạn', 'Nice to meet you, I\'m John.', 'Rất vui được gặp bạn, tôi là John.'],
      ['how\'s it going', '/haʊz ɪt ˈɡəʊɪŋ/', 'dạo này thế nào', 'Hey, how\'s it going?', 'Này, mọi chuyện thế nào rồi?'],
      ['what\'s up', '/wɒts ʌp/', 'có gì mới không', 'What\'s up, man?', 'Có gì mới không, bạn?'],
      ['take care', '/teɪk keə/', 'giữ gìn sức khỏe', 'Take care and stay safe.', 'Bảo trọng và giữ an toàn nhé.'],
      ['congratulations', '/kənˌɡrætʃuˈleɪʃnz/', 'chúc mừng', 'Congratulations on your new job!', 'Chúc mừng bạn có công việc mới!'],
      ['welcome', '/ˈwelkəm/', 'chào mừng', 'Welcome to our home.', 'Chào mừng đến nhà chúng tôi.'],
      ['introduce', '/ˌɪntrəˈdjuːs/', 'giới thiệu', 'Let me introduce my friend.', 'Để tôi giới thiệu bạn của tôi.'],
      ['name', '/neɪm/', 'tên', 'What\'s your name?', 'Bạn tên là gì?'],
      ['age', '/eɪdʒ/', 'tuổi', 'May I ask your age?', 'Tôi có thể hỏi tuổi của bạn không?'],
      ['address', '/əˈdres/', 'địa chỉ', 'Can you give me your address?', 'Bạn có thể cho tôi địa chỉ của bạn không?'],
      ['phone number', '/fəʊn ˈnʌmbə/', 'số điện thoại', 'What\'s your phone number?', 'Số điện thoại của bạn là gì?'],
      ['email', '/ˈiːmeɪl/', 'thư điện tử', 'Please send me an email.', 'Làm ơn gửi email cho tôi.'],
      ['conversation', '/ˌkɒnvəˈseɪʃn/', 'cuộc trò chuyện', 'We had a long conversation.', 'Chúng tôi đã có một cuộc trò chuyện dài.'],
      ['talk', '/tɔːk/', 'nói chuyện', 'Can we talk for a minute?', 'Chúng ta có thể nói chuyện một phút được không?'],
      ['speak', '/spiːk/', 'nói', 'Do you speak English?', 'Bạn có nói tiếng Anh không?'],
      ['say', '/seɪ/', 'nói (điều gì)', 'What did you say?', 'Bạn vừa nói gì?'],
      ['tell', '/tel/', 'kể, cho biết', 'Tell me about your day.', 'Kể cho tôi về ngày hôm nay của bạn đi.'],
      ['ask', '/ɑːsk/', 'hỏi', 'Can I ask you a question?', 'Tôi có thể hỏi bạn một câu hỏi không?'],
      ['answer', '/ˈɑːnsə/', 'trả lời', 'Please answer my question.', 'Xin hãy trả lời câu hỏi của tôi.'],
      ['explain', '/ɪkˈspleɪn/', 'giải thích', 'Can you explain this to me?', 'Bạn có thể giải thích điều này cho tôi không?'],
      ['understand', '/ˌʌndəˈstænd/', 'hiểu', 'I don\'t understand.', 'Tôi không hiểu.'],
      ['repeat', '/rɪˈpiːt/', 'lặp lại', 'Could you repeat that, please?', 'Bạn có thể nhắc lại được không?'],
      ['listen', '/ˈlɪsn/', 'lắng nghe', 'Listen carefully to the instructions.', 'Hãy lắng nghe kỹ hướng dẫn.'],
      ['mean', '/miːn/', 'có nghĩa là', 'What does this word mean?', 'Từ này nghĩa là gì?'],
      ['agree', '/əˈɡriː/', 'đồng ý', 'I agree with you.', 'Tôi đồng ý với bạn.'],
      ['disagree', '/ˌdɪsəˈɡriː/', 'không đồng ý', 'I disagree with that opinion.', 'Tôi không đồng ý với ý kiến đó.'],
      ['opinion', '/əˈpɪnjən/', 'ý kiến', 'What\'s your opinion on this?', 'Bạn nghĩ sao về việc này?'],
      ['suggest', '/səˈdʒest/', 'đề nghị', 'I suggest we leave early.', 'Tôi đề nghị chúng ta đi sớm.'],
      ['invite', '/ɪnˈvaɪt/', 'mời', 'I\'d like to invite you to dinner.', 'Tôi muốn mời bạn đi ăn tối.'],
      ['accept', '/əkˈsept/', 'chấp nhận', 'She accepted the invitation.', 'Cô ấy đã nhận lời mời.'],
      ['refuse', '/rɪˈfjuːz/', 'từ chối', 'He refused to answer.', 'Anh ấy từ chối trả lời.'],
      ['promise', '/ˈprɒmɪs/', 'hứa', 'I promise to call you.', 'Tôi hứa sẽ gọi cho bạn.'],
      ['apologize', '/əˈpɒlədʒaɪz/', 'xin lỗi', 'I want to apologize for my mistake.', 'Tôi muốn xin lỗi vì lỗi của mình.'],
      ['compliment', '/ˈkɒmplɪmənt/', 'lời khen', 'She gave me a nice compliment.', 'Cô ấy đã khen tôi rất dễ thương.'],
      ['family', '/ˈfæməli/', 'gia đình', 'I love spending time with my family.', 'Tôi thích dành thời gian với gia đình.'],
      ['parents', '/ˈpeərənts/', 'cha mẹ', 'My parents live in the countryside.', 'Bố mẹ tôi sống ở nông thôn.'],
      ['father', '/ˈfɑːðə/', 'cha, bố', 'My father works as a teacher.', 'Bố tôi làm giáo viên.'],
      ['mother', '/ˈmʌðə/', 'mẹ', 'My mother cooks dinner every night.', 'Mẹ tôi nấu cơm tối mỗi tối.'],
      ['son', '/sʌn/', 'con trai', 'Their son is studying abroad.', 'Con trai họ đang học ở nước ngoài.'],
      ['daughter', '/ˈdɔːtə/', 'con gái', 'Her daughter is only five years old.', 'Con gái cô ấy mới chỉ năm tuổi.'],
      ['brother', '/ˈbrʌðə/', 'anh, em trai', 'My brother is older than me.', 'Anh trai tôi lớn hơn tôi.'],
      ['sister', '/ˈsɪstə/', 'chị, em gái', 'My sister lives in another city.', 'Chị gái tôi sống ở một thành phố khác.'],
      ['husband', '/ˈhʌzbənd/', 'chồng', 'Her husband works in a bank.', 'Chồng cô ấy làm việc ở ngân hàng.'],
      ['wife', '/waɪf/', 'vợ', 'His wife is a doctor.', 'Vợ anh ấy là bác sĩ.'],
      ['grandfather', '/ˈɡrænfɑːðə/', 'ông', 'My grandfather tells great stories.', 'Ông tôi kể chuyện rất hay.'],
      ['grandmother', '/ˈɡrænmʌðə/', 'bà', 'My grandmother makes delicious cakes.', 'Bà tôi làm bánh rất ngon.'],
      ['uncle', '/ˈʌŋkl/', 'chú, bác, cậu', 'My uncle visits us every summer.', 'Chú tôi đến thăm chúng tôi mỗi mùa hè.'],
      ['aunt', '/ɑːnt/', 'cô, dì, thím', 'My aunt lives next door.', 'Dì tôi sống ngay cạnh nhà.'],
      ['cousin', '/ˈkʌzn/', 'anh chị em họ', 'I have many cousins.', 'Tôi có nhiều anh chị em họ.'],
      ['friend', '/frend/', 'bạn', 'She is my best friend.', 'Cô ấy là bạn thân nhất của tôi.'],
      ['neighbor', '/ˈneɪbə/', 'hàng xóm', 'Our neighbor is very kind.', 'Người hàng xóm của chúng tôi rất tốt bụng.'],
      ['colleague', '/ˈkɒliːɡ/', 'đồng nghiệp', 'I met my colleague at the cafe.', 'Tôi gặp đồng nghiệp ở quán cà phê.'],
      ['boyfriend', '/ˈbɔɪfrend/', 'bạn trai', 'She introduced her boyfriend to us.', 'Cô ấy giới thiệu bạn trai với chúng tôi.'],
      ['girlfriend', '/ˈɡɜːlfrend/', 'bạn gái', 'He brought his girlfriend to the party.', 'Anh ấy đưa bạn gái đến buổi tiệc.'],
      ['married', '/ˈmærid/', 'đã kết hôn', 'They got married last year.', 'Họ kết hôn năm ngoái.'],
      ['single', '/ˈsɪŋɡl/', 'độc thân', 'He is still single.', 'Anh ấy vẫn còn độc thân.'],
      ['relationship', '/rɪˈleɪʃnʃɪp/', 'mối quan hệ', 'They have a strong relationship.', 'Họ có mối quan hệ bền vững.'],
      ['relative', '/ˈrelətɪv/', 'họ hàng', 'Many relatives came to the wedding.', 'Nhiều người thân đã đến đám cưới.'],
      ['baby', '/ˈbeɪbi/', 'em bé', 'The baby is sleeping now.', 'Em bé đang ngủ.'],
      ['child', '/tʃaɪld/', 'đứa trẻ', 'Every child deserves love.', 'Mọi đứa trẻ đều xứng đáng được yêu thương.'],
      ['adult', '/ˈædʌlt/', 'người lớn', 'This movie is for adults only.', 'Bộ phim này chỉ dành cho người lớn.'],
      ['teenager', '/ˈtiːneɪdʒə/', 'thanh thiếu niên', 'Teenagers often use social media.', 'Thanh thiếu niên thường dùng mạng xã hội.'],
      ['elderly', '/ˈeldəli/', 'người lớn tuổi', 'We should respect the elderly.', 'Chúng ta nên tôn trọng người già.'],
      ['love', '/lʌv/', 'yêu, tình yêu', 'I love my family very much.', 'Tôi rất yêu gia đình mình.'],
      ['care', '/keə/', 'quan tâm, chăm sóc', 'She cares about her friends.', 'Cô ấy quan tâm đến bạn bè.'],
      ['trust', '/trʌst/', 'tin tưởng', 'I trust you completely.', 'Tôi hoàn toàn tin tưởng bạn.'],
      ['support', '/səˈpɔːt/', 'ủng hộ, hỗ trợ', 'My family supports my decisions.', 'Gia đình tôi ủng hộ quyết định của tôi.'],
      ['miss', '/mɪs/', 'nhớ (ai đó)', 'I miss my hometown.', 'Tôi nhớ quê hương.'],
      ['visit', '/ˈvɪzɪt/', 'thăm', 'We visit our grandparents every weekend.', 'Chúng tôi thăm ông bà mỗi cuối tuần.'],
      ['hug', '/hʌɡ/', 'ôm', 'She gave her mother a big hug.', 'Cô ấy ôm mẹ thật chặt.'],
      ['kiss', '/kɪs/', 'hôn', 'He kissed his daughter goodnight.', 'Anh ấy hôn con gái chúc ngủ ngon.'],
      ['argue', '/ˈɑːɡjuː/', 'cãi nhau', 'Siblings sometimes argue over small things.', 'Anh chị em đôi khi cãi nhau vì chuyện nhỏ.'],
      ['forgive', '/fəˈɡɪv/', 'tha thứ', 'I forgive you for the mistake.', 'Tôi tha thứ cho bạn về lỗi đó.'],
      ['remember', '/rɪˈmembə/', 'nhớ, ghi nhớ', 'I remember my childhood clearly.', 'Tôi nhớ rõ tuổi thơ của mình.'],
      ['forget', '/fəˈɡet/', 'quên', 'Don\'t forget to call your mom.', 'Đừng quên gọi cho mẹ nhé.'],
      ['reunion', '/riˈjuːniən/', 'cuộc đoàn tụ', 'We had a family reunion last month.', 'Chúng tôi có buổi họp mặt gia đình tháng trước.'],
      ['tradition', '/trəˈdɪʃn/', 'truyền thống', 'Our family has many traditions.', 'Gia đình chúng tôi có nhiều truyền thống.'],
      ['celebrate', '/ˈselɪbreɪt/', 'ăn mừng, tổ chức', 'We celebrate birthdays every year.', 'Chúng tôi tổ chức sinh nhật mỗi năm.'],
      ['gift', '/ɡɪft/', 'quà tặng', 'She gave her friend a nice gift.', 'Cô ấy tặng bạn một món quà đẹp.'],
      ['surprise', '/səˈpraɪz/', 'bất ngờ', 'They planned a surprise party.', 'Họ đã lên kế hoạch một buổi tiệc bất ngờ.'],
      ['wedding', '/ˈwedɪŋ/', 'đám cưới', 'The wedding was beautiful.', 'Đám cưới rất đẹp.'],
      ['anniversary', '/ˌænɪˈvɜːsəri/', 'ngày kỷ niệm', 'Today is our wedding anniversary.', 'Hôm nay là ngày kỷ niệm cưới của chúng tôi.'],
      ['divorce', '/dɪˈvɔːs/', 'ly hôn', 'They decided to get a divorce.', 'Họ quyết định ly hôn.'],
      ['household', '/ˈhaʊshəʊld/', 'hộ gia đình', 'Every household has different rules.', 'Mỗi gia đình có những quy tắc khác nhau.'],
      ['happy', '/ˈhæpi/', 'vui vẻ', 'I feel happy today.', 'Hôm nay tôi cảm thấy vui.'],
      ['sad', '/sæd/', 'buồn', 'She looks sad this morning.', 'Sáng nay cô ấy trông buồn.'],
      ['angry', '/ˈæŋɡri/', 'tức giận', 'He was angry about the delay.', 'Anh ấy giận vì bị trì hoãn.'],
      ['excited', '/ɪkˈsaɪtɪd/', 'hào hứng', 'We are excited about the trip.', 'Chúng tôi rất hào hứng về chuyến đi.'],
      ['nervous', '/ˈnɜːvəs/', 'lo lắng', 'I feel nervous before the exam.', 'Tôi thấy lo lắng trước kỳ thi.'],
      ['scared', '/skeəd/', 'sợ hãi', 'The child was scared of the dark.', 'Đứa trẻ sợ bóng tối.'],
      ['tired', '/ˈtaɪəd/', 'mệt mỏi', 'I\'m too tired to go out tonight.', 'Tôi mệt quá nên không đi ra ngoài tối nay.'],
      ['bored', '/bɔːd/', 'chán', 'The students looked bored during class.', 'Các học sinh trông chán trong giờ học.'],
      ['surprised', '/səˈpraɪzd/', 'ngạc nhiên', 'I was surprised by the news.', 'Tôi ngạc nhiên vì tin tức đó.'],
      ['worried', '/ˈwʌrid/', 'lo lắng', 'She\'s worried about her exam results.', 'Cô ấy lo lắng về kết quả thi.'],
      ['confused', '/kənˈfjuːzd/', 'bối rối', 'I\'m confused about the instructions.', 'Tôi bối rối về hướng dẫn.'],
      ['proud', '/praʊd/', 'tự hào', 'Her parents are proud of her.', 'Bố mẹ cô ấy tự hào về cô ấy.'],
      ['embarrassed', '/ɪmˈbærəst/', 'xấu hổ', 'He felt embarrassed after the mistake.', 'Anh ấy thấy xấu hổ sau khi mắc lỗi.'],
      ['jealous', '/ˈdʒeləs/', 'ghen tị', 'She felt jealous of her sister.', 'Cô ấy ghen với chị gái.'],
      ['lonely', '/ˈləʊnli/', 'cô đơn', 'He feels lonely living far from home.', 'Anh ấy thấy cô đơn khi sống xa nhà.'],
      ['relieved', '/rɪˈliːvd/', 'nhẹ nhõm', 'I was relieved to hear the good news.', 'Tôi nhẹ nhõm khi nghe tin tốt.'],
      ['disappointed', '/ˌdɪsəˈpɔɪntɪd/', 'thất vọng', 'She was disappointed with the results.', 'Cô ấy thất vọng về kết quả.'],
      ['calm', '/kɑːm/', 'bình tĩnh', 'Please stay calm during the emergency.', 'Xin hãy giữ bình tĩnh trong tình huống khẩn cấp.'],
      ['curious', '/ˈkjʊəriəs/', 'tò mò', 'The children are curious about everything.', 'Trẻ em tò mò về mọi thứ.'],
      ['grateful', '/ˈɡreɪtfl/', 'biết ơn', 'I\'m grateful for your help.', 'Tôi biết ơn vì sự giúp đỡ của bạn.'],
      ['confident', '/ˈkɒnfɪdənt/', 'tự tin', 'She spoke with confidence.', 'Cô ấy nói chuyện rất tự tin.'],
      ['shy', '/ʃaɪ/', 'nhút nhát', 'He is too shy to speak in public.', 'Anh ấy quá nhút nhát để nói trước đám đông.'],
      ['comfortable', '/ˈkʌmftəbl/', 'thoải mái', 'I feel comfortable in this chair.', 'Tôi thấy thoải mái trên chiếc ghế này.'],
      ['uncomfortable', '/ʌnˈkʌmftəbl/', 'không thoải mái', 'The seat was very uncomfortable.', 'Chỗ ngồi rất khó chịu.'],
      ['exhausted', '/ɪɡˈzɔːstɪd/', 'kiệt sức', 'I\'m exhausted after work.', 'Tôi kiệt sức sau giờ làm.'],
      ['stressed', '/strest/', 'căng thẳng', 'He is stressed about deadlines.', 'Anh ấy căng thẳng vì các hạn chót.'],
      ['relaxed', '/rɪˈlækst/', 'thư giãn', 'She feels relaxed on vacation.', 'Cô ấy thấy thư giãn khi đi nghỉ.'],
      ['hopeful', '/ˈhəʊpfl/', 'đầy hy vọng', 'We are hopeful for the future.', 'Chúng tôi hy vọng vào tương lai.'],
      ['frustrated', '/frʌˈstreɪtɪd/', 'bực bội', 'I\'m frustrated with the slow internet.', 'Tôi bực mình vì mạng chậm.'],
      ['satisfied', '/ˈsætɪsfaɪd/', 'hài lòng', 'The customer was satisfied with the service.', 'Khách hàng hài lòng với dịch vụ.'],
      ['anxious', '/ˈæŋkʃəs/', 'lo âu', 'She feels anxious before flights.', 'Cô ấy lo âu trước khi bay.'],
      ['cheerful', '/ˈtʃɪəfl/', 'vui tươi', 'He always has a cheerful smile.', 'Anh ấy luôn có nụ cười vui vẻ.'],
      ['moody', '/ˈmuːdi/', 'thất thường (tâm trạng)', 'Teenagers can be moody sometimes.', 'Thanh thiếu niên đôi khi hay thay đổi tâm trạng.'],
      ['sympathetic', '/ˌsɪmpəˈθetɪk/', 'thông cảm', 'She was sympathetic to my problem.', 'Cô ấy thông cảm với vấn đề của tôi.'],
      ['emotion', '/ɪˈməʊʃn/', 'cảm xúc', 'It\'s normal to show emotion.', 'Thể hiện cảm xúc là điều bình thường.'],
      ['feeling', '/ˈfiːlɪŋ/', 'cảm giác', 'I have a good feeling about this.', 'Tôi có cảm giác tốt về việc này.'],
      ['mood', '/muːd/', 'tâm trạng', 'I\'m not in the mood to talk.', 'Tôi không có tâm trạng để nói chuyện.'],
      ['cry', '/kraɪ/', 'khóc', 'The baby started to cry.', 'Em bé bắt đầu khóc.'],
      ['laugh', '/lɑːf/', 'cười', 'We laughed at his joke.', 'Chúng tôi cười vì câu đùa của anh ấy.'],
      ['smile', '/smaɪl/', 'mỉm cười', 'She smiled at me warmly.', 'Cô ấy mỉm cười với tôi thật ấm áp.'],
      ['shout', '/ʃaʊt/', 'la hét', 'Don\'t shout, I can hear you.', 'Đừng hét lên, tôi nghe thấy bạn rồi.'],
      ['whisper', '/ˈwɪspə/', 'thì thầm', 'She whispered the secret to me.', 'Cô ấy thì thầm bí mật với tôi.'],
      ['complain', '/kəmˈpleɪn/', 'than phiền', 'He complained about the noise.', 'Anh ấy phàn nàn về tiếng ồn.'],
      ['encourage', '/ɪnˈkʌrɪdʒ/', 'động viên', 'My teacher encourages me to try harder.', 'Thầy giáo khuyến khích tôi cố gắng hơn.'],
      ['comfort', '/ˈkʌmfət/', 'an ủi', 'She comforted her crying friend.', 'Cô ấy an ủi người bạn đang khóc.'],
      ['calm down', '/kɑːm daʊn/', 'bình tĩnh lại', 'Please calm down and explain.', 'Xin hãy bình tĩnh lại và giải thích.'],
      ['cheer up', '/tʃɪər ʌp/', 'vui lên', 'Cheer up, everything will be fine.', 'Vui lên đi, mọi chuyện sẽ ổn thôi.'],
      ['get upset', '/ɡet ʌpˈset/', 'buồn bực', 'Don\'t get upset over small things.', 'Đừng buồn vì những chuyện nhỏ.'],
      ['feel down', '/fiːl daʊn/', 'cảm thấy chán nản', 'I feel down today for no reason.', 'Hôm nay tôi thấy buồn mà chẳng có lý do.'],
      ['mixed feelings', '/mɪkst ˈfiːlɪŋz/', 'cảm xúc lẫn lộn', 'I have mixed feelings about moving abroad.', 'Tôi có cảm xúc lẫn lộn về việc ra nước ngoài.'],
      ['wake up', '/weɪk ʌp/', 'thức dậy', 'I wake up at 6 AM every day.', 'Tôi thức dậy lúc 6 giờ sáng mỗi ngày.'],
      ['get up', '/ɡet ʌp/', 'dậy (khỏi giường)', 'He gets up early to exercise.', 'Anh ấy dậy sớm để tập thể dục.'],
      ['brush teeth', '/brʌʃ tiːθ/', 'đánh răng', 'Remember to brush your teeth.', 'Nhớ đánh răng nhé.'],
      ['wash face', '/wɒʃ feɪs/', 'rửa mặt', 'She washes her face every morning.', 'Cô ấy rửa mặt mỗi sáng.'],
      ['take a shower', '/teɪk ə ˈʃaʊə/', 'tắm', 'I take a shower before breakfast.', 'Tôi tắm trước khi ăn sáng.'],
      ['get dressed', '/ɡet drest/', 'mặc quần áo', 'He got dressed quickly for work.', 'Anh ấy mặc đồ nhanh để đi làm.'],
      ['have breakfast', '/hæv ˈbrekfəst/', 'ăn sáng', 'We have breakfast together.', 'Chúng tôi ăn sáng cùng nhau.'],
      ['go to work', '/ɡəʊ tuː wɜːk/', 'đi làm', 'She goes to work by bus.', 'Cô ấy đi làm bằng xe buýt.'],
      ['go to school', '/ɡəʊ tuː skuːl/', 'đi học', 'Children go to school in the morning.', 'Trẻ em đi học vào buổi sáng.'],
      ['have lunch', '/hæv lʌntʃ/', 'ăn trưa', 'We have lunch at noon.', 'Chúng tôi ăn trưa lúc giữa trưa.'],
      ['take a break', '/teɪk ə breɪk/', 'nghỉ giải lao', 'Let\'s take a break for ten minutes.', 'Hãy nghỉ mười phút đi.'],
      ['finish work', '/ˈfɪnɪʃ wɜːk/', 'kết thúc công việc', 'I finish work at 5 PM.', 'Tôi tan làm lúc 5 giờ chiều.'],
      ['go home', '/ɡəʊ həʊm/', 'về nhà', 'We go home after school.', 'Chúng tôi về nhà sau giờ học.'],
      ['cook dinner', '/kʊk ˈdɪnə/', 'nấu bữa tối', 'My mom cooks dinner every evening.', 'Mẹ tôi nấu cơm tối mỗi tối.'],
      ['have dinner', '/hæv ˈdɪnə/', 'ăn tối', 'We have dinner as a family.', 'Chúng tôi ăn tối cùng gia đình.'],
      ['watch TV', '/wɒtʃ tiː ˈviː/', 'xem tivi', 'We watch TV after dinner.', 'Chúng tôi xem TV sau bữa tối.'],
      ['read a book', '/riːd ə bʊk/', 'đọc sách', 'I read a book before bed.', 'Tôi đọc sách trước khi ngủ.'],
      ['do homework', '/duː ˈhəʊmwɜːk/', 'làm bài tập', 'The kids do homework in the evening.', 'Bọn trẻ làm bài tập vào buổi tối.'],
      ['clean the house', '/kliːn ðə haʊs/', 'dọn nhà', 'We clean the house on weekends.', 'Chúng tôi dọn nhà vào cuối tuần.'],
      ['do laundry', '/duː ˈlɔːndri/', 'giặt đồ', 'She does laundry twice a week.', 'Cô ấy giặt đồ hai lần một tuần.'],
      ['wash dishes', '/wɒʃ ˈdɪʃɪz/', 'rửa bát', 'I wash the dishes after dinner.', 'Tôi rửa bát sau bữa tối.'],
      ['take out trash', '/teɪk aʊt træʃ/', 'đổ rác', 'Please take out the trash tonight.', 'Tối nay hãy đổ rác nhé.'],
      ['go shopping', '/ɡəʊ ˈʃɒpɪŋ/', 'đi mua sắm', 'We go shopping every Saturday.', 'Chúng tôi đi mua sắm mỗi thứ Bảy.'],
      ['exercise', '/ˈeksəsaɪz/', 'tập thể dục', 'I exercise every morning.', 'Tôi tập thể dục mỗi sáng.'],
      ['go for a walk', '/ɡəʊ fər ə wɔːk/', 'đi dạo', 'We go for a walk after dinner.', 'Chúng tôi đi dạo sau bữa tối.'],
      ['take a nap', '/teɪk ə næp/', 'ngủ trưa', 'I usually take a nap on weekends.', 'Cuối tuần tôi thường ngủ trưa.'],
      ['go to bed', '/ɡəʊ tuː bed/', 'đi ngủ', 'I go to bed at 10 PM.', 'Tôi đi ngủ lúc 10 giờ tối.'],
      ['set an alarm', '/set ən əˈlɑːm/', 'đặt báo thức', 'I set an alarm for 6 AM.', 'Tôi đặt báo thức lúc 6 giờ sáng.'],
      ['lock the door', '/lɒk ðə dɔː/', 'khóa cửa', 'Don\'t forget to lock the door.', 'Đừng quên khóa cửa.'],
      ['turn on', '/tɜːn ɒn/', 'bật (thiết bị)', 'Turn on the lights, please.', 'Bật đèn lên đi.'],
      ['turn off', '/tɜːn ɒf/', 'tắt (thiết bị)', 'Turn off the TV before sleeping.', 'Tắt TV trước khi ngủ.'],
      ['charge phone', '/tʃɑːdʒ fəʊn/', 'sạc điện thoại', 'I charge my phone overnight.', 'Tôi sạc điện thoại qua đêm.'],
      ['check email', '/tʃek ˈiːmeɪl/', 'kiểm tra email', 'I check my email every morning.', 'Tôi kiểm tra email mỗi sáng.'],
      ['commute', '/kəˈmjuːt/', 'đi lại (đi làm/học)', 'My commute takes 30 minutes.', 'Việc đi lại của tôi mất 30 phút.'],
      ['make the bed', '/meɪk ðə bed/', 'dọn giường', 'She makes the bed every morning.', 'Cô ấy trải giường mỗi sáng.'],
      ['iron clothes', '/ˈaɪən kləʊðz/', 'ủi quần áo', 'He irons his shirt before work.', 'Anh ấy ủi áo trước khi đi làm.'],
      ['water plants', '/ˈwɔːtə plɑːnts/', 'tưới cây', 'I water the plants every evening.', 'Tôi tưới cây mỗi tối.'],
      ['feed the pet', '/fiːd ðə pet/', 'cho thú cưng ăn', 'Please feed the pet before you leave.', 'Hãy cho thú cưng ăn trước khi bạn đi.'],
      ['run errands', '/rʌn ˈerəndz/', 'đi làm việc vặt', 'I need to run some errands today.', 'Hôm nay tôi cần làm vài việc vặt.'],
      ['pay bills', '/peɪ bɪlz/', 'trả hóa đơn', 'We pay bills online now.', 'Bây giờ chúng tôi thanh toán hóa đơn trực tuyến.'],
      ['plan the day', '/plæn ðə deɪ/', 'lên kế hoạch trong ngày', 'I plan my day every morning.', 'Tôi lên kế hoạch cho ngày mỗi sáng.'],
      ['relax', '/rɪˈlæks/', 'nghỉ ngơi', 'I relax by listening to music.', 'Tôi thư giãn bằng cách nghe nhạc.'],
      ['tidy up', '/ˈtaɪdi ʌp/', 'dọn dẹp gọn gàng', 'Let\'s tidy up the room.', 'Hãy dọn dẹp căn phòng đi.'],
      ['cook breakfast', '/kʊk ˈbrekfəst/', 'nấu bữa sáng', 'He cooks breakfast every Sunday.', 'Anh ấy nấu bữa sáng mỗi Chủ nhật.'],
      ['pack a bag', '/pæk ə bæɡ/', 'đóng gói túi', 'I packed my bag for school.', 'Tôi xếp đồ vào túi để đi học.'],
      ['leave home', '/liːv həʊm/', 'rời khỏi nhà', 'I leave home at 7 AM.', 'Tôi rời nhà lúc 7 giờ sáng.'],
      ['arrive home', '/əˈraɪv həʊm/', 'về đến nhà', 'I arrive home around 6 PM.', 'Tôi về nhà khoảng 6 giờ chiều.'],
      ['stretch', '/stretʃ/', 'giãn cơ, vươn vai', 'I stretch every morning after waking up.', 'Tôi giãn cơ mỗi sáng sau khi thức dậy.'],
      ['yawn', '/jɔːn/', 'ngáp', 'He yawned during the meeting.', 'Anh ấy ngáp trong buổi họp.'],
      ['daily routine', '/ˈdeɪli ruːˈtiːn/', 'thói quen hàng ngày', 'Everyone has a different daily routine.', 'Mỗi người có thói quen hàng ngày khác nhau.'],
      ['house', '/haʊs/', 'ngôi nhà', 'We bought a new house.', 'Chúng tôi mua một ngôi nhà mới.'],
      ['apartment', '/əˈpɑːtmənt/', 'căn hộ', 'She lives in a small apartment.', 'Cô ấy sống trong một căn hộ nhỏ.'],
      ['room', '/ruːm/', 'căn phòng', 'This room is very bright.', 'Căn phòng này rất sáng.'],
      ['bedroom', '/ˈbedruːm/', 'phòng ngủ', 'My bedroom is upstairs.', 'Phòng ngủ của tôi ở trên lầu.'],
      ['bathroom', '/ˈbɑːθruːm/', 'phòng tắm', 'The bathroom is being cleaned.', 'Phòng tắm đang được dọn dẹp.'],
      ['kitchen', '/ˈkɪtʃɪn/', 'nhà bếp', 'She is cooking in the kitchen.', 'Cô ấy đang nấu ăn trong bếp.'],
      ['living room', '/ˈlɪvɪŋ ruːm/', 'phòng khách', 'We watch TV in the living room.', 'Chúng tôi xem TV ở phòng khách.'],
      ['dining room', '/ˈdaɪnɪŋ ruːm/', 'phòng ăn', 'The family eats in the dining room.', 'Gia đình ăn ở phòng ăn.'],
      ['garden', '/ˈɡɑːdn/', 'khu vườn', 'We grow vegetables in the garden.', 'Chúng tôi trồng rau trong vườn.'],
      ['balcony', '/ˈbælkəni/', 'ban công', 'I like to sit on the balcony.', 'Tôi thích ngồi ở ban công.'],
      ['furniture', '/ˈfɜːnɪtʃə/', 'nội thất', 'We bought new furniture last week.', 'Tuần trước chúng tôi mua đồ nội thất mới.'],
      ['table', '/ˈteɪbl/', 'cái bàn', 'Put the plates on the table.', 'Đặt đĩa lên bàn.'],
      ['chair', '/tʃeə/', 'cái ghế', 'Please sit on this chair.', 'Xin hãy ngồi ghế này.'],
      ['bed', '/bed/', 'giường', 'The bed is very comfortable.', 'Giường rất thoải mái.'],
      ['sofa', '/ˈsəʊfə/', 'ghế sofa', 'We relax on the sofa in the evening.', 'Buổi tối chúng tôi thư giãn trên ghế sofa.'],
      ['wardrobe', '/ˈwɔːdrəʊb/', 'tủ quần áo', 'My clothes are in the wardrobe.', 'Quần áo của tôi ở trong tủ.'],
      ['mirror', '/ˈmɪrə/', 'gương', 'She looked in the mirror.', 'Cô ấy nhìn vào gương.'],
      ['lamp', '/læmp/', 'đèn bàn', 'Turn on the lamp, it\'s dark.', 'Bật đèn bàn lên, trời tối rồi.'],
      ['curtain', '/ˈkɜːtn/', 'rèm cửa', 'Close the curtain, please.', 'Kéo rèm lại đi.'],
      ['window', '/ˈwɪndəʊ/', 'cửa sổ', 'Open the window for fresh air.', 'Mở cửa sổ để lấy không khí trong lành.'],
      ['door', '/dɔː/', 'cửa ra vào', 'Please shut the door quietly.', 'Xin hãy đóng cửa nhẹ nhàng.'],
      ['key', '/kiː/', 'chìa khóa', 'I lost my house key.', 'Tôi làm mất chìa khóa nhà.'],
      ['refrigerator', '/rɪˈfrɪdʒəreɪtə/', 'tủ lạnh', 'Put the milk in the refrigerator.', 'Cho sữa vào tủ lạnh.'],
      ['stove', '/stəʊv/', 'bếp nấu', 'She turned on the stove.', 'Cô ấy bật bếp lên.'],
      ['microwave', '/ˈmaɪkrəweɪv/', 'lò vi sóng', 'Heat the food in the microwave.', 'Hâm nóng thức ăn trong lò vi sóng.'],
      ['washing machine', '/ˈwɒʃɪŋ məˈʃiːn/', 'máy giặt', 'The washing machine is broken.', 'Máy giặt bị hỏng.'],
      ['air conditioner', '/eə kənˈdɪʃənə/', 'máy điều hòa', 'Turn on the air conditioner, it\'s hot.', 'Bật điều hòa lên, trời nóng quá.'],
      ['fan', '/fæn/', 'quạt', 'The fan helps cool the room.', 'Quạt giúp làm mát phòng.'],
      ['broom', '/bruːm/', 'cây chổi', 'Use the broom to sweep the floor.', 'Dùng chổi để quét sàn.'],
      ['vacuum cleaner', '/ˈvækjuːm ˈkliːnə/', 'máy hút bụi', 'I use a vacuum cleaner every week.', 'Tôi dùng máy hút bụi mỗi tuần.'],
      ['towel', '/ˈtaʊəl/', 'khăn tắm', 'Hang the towel on the hook.', 'Treo khăn lên móc.'],
      ['pillow', '/ˈpɪləʊ/', 'gối', 'I sleep with two pillows.', 'Tôi ngủ với hai cái gối.'],
      ['blanket', '/ˈblæŋkɪt/', 'chăn', 'It\'s cold, bring me a blanket.', 'Trời lạnh, lấy cho tôi cái chăn.'],
      ['sheet', '/ʃiːt/', 'ga giường', 'Change the bed sheets weekly.', 'Thay ga giường mỗi tuần.'],
      ['sink', '/sɪŋk/', 'bồn rửa', 'Wash your hands in the sink.', 'Rửa tay ở bồn rửa.'],
      ['toilet', '/ˈtɔɪlɪt/', 'nhà vệ sinh', 'Where is the toilet?', 'Nhà vệ sinh ở đâu?'],
      ['shower', '/ˈʃaʊə/', 'vòi hoa sen', 'The shower is not working.', 'Vòi sen không hoạt động.'],
      ['staircase', '/ˈsteəkeɪs/', 'cầu thang', 'Walk carefully on the staircase.', 'Đi cẩn thận trên cầu thang.'],
      ['roof', '/ruːf/', 'mái nhà', 'The roof needs repair.', 'Mái nhà cần sửa.'],
      ['wall', '/wɔːl/', 'tường', 'We painted the wall blue.', 'Chúng tôi sơn tường màu xanh.'],
      ['floor', '/flɔː/', 'sàn nhà', 'The floor is very clean.', 'Sàn nhà rất sạch.'],
      ['ceiling', '/ˈsiːlɪŋ/', 'trần nhà', 'The ceiling is quite high.', 'Trần nhà khá cao.'],
      ['yard', '/jɑːd/', 'sân', 'The kids play in the yard.', 'Bọn trẻ chơi ngoài sân.'],
      ['fence', '/fens/', 'hàng rào', 'There\'s a fence around the garden.', 'Có hàng rào quanh khu vườn.'],
      ['mailbox', '/ˈmeɪlbɒks/', 'hộp thư', 'Check the mailbox for letters.', 'Kiểm tra hộp thư xem có thư không.'],
      ['doorbell', '/ˈdɔːbel/', 'chuông cửa', 'Someone rang the doorbell.', 'Có ai bấm chuông cửa.'],
      ['light switch', '/laɪt swɪtʃ/', 'công tắc đèn', 'The light switch is next to the door.', 'Công tắc đèn ở cạnh cửa.'],
      ['socket', '/ˈsɒkɪt/', 'ổ cắm điện', 'Plug the charger into the socket.', 'Cắm sạc vào ổ điện.'],
      ['rent', '/rent/', 'tiền thuê nhà', 'We pay rent every month.', 'Chúng tôi trả tiền thuê nhà mỗi tháng.'],
      ['neighborhood', '/ˈneɪbəhʊd/', 'khu phố, khu dân cư', 'This is a quiet neighborhood.', 'Đây là một khu phố yên tĩnh.'],
      ['food', '/fuːd/', 'thức ăn', 'The food here is delicious.', 'Đồ ăn ở đây rất ngon.'],
      ['meal', '/miːl/', 'bữa ăn', 'We eat three meals a day.', 'Chúng tôi ăn ba bữa mỗi ngày.'],
      ['breakfast', '/ˈbrekfəst/', 'bữa sáng', 'I usually skip breakfast.', 'Tôi thường bỏ bữa sáng.'],
      ['lunch', '/lʌntʃ/', 'bữa trưa', 'Let\'s have lunch together.', 'Hãy ăn trưa cùng nhau đi.'],
      ['dinner', '/ˈdɪnə/', 'bữa tối', 'Dinner is ready.', 'Bữa tối đã sẵn sàng.'],
      ['snack', '/snæk/', 'bữa ăn nhẹ', 'I had a snack in the afternoon.', 'Tôi ăn nhẹ vào buổi chiều.'],
      ['rice', '/raɪs/', 'cơm, gạo', 'Rice is a staple food in Vietnam.', 'Cơm là món ăn chính ở Việt Nam.'],
      ['bread', '/bred/', 'bánh mì', 'She buys fresh bread every morning.', 'Cô ấy mua bánh mì tươi mỗi sáng.'],
      ['noodles', '/ˈnuːdlz/', 'mì', 'We had noodles for lunch.', 'Chúng tôi ăn mì cho bữa trưa.'],
      ['meat', '/miːt/', 'thịt', 'He doesn\'t eat meat.', 'Anh ấy không ăn thịt.'],
      ['chicken', '/ˈtʃɪkɪn/', 'thịt gà', 'We cooked chicken for dinner.', 'Chúng tôi nấu gà cho bữa tối.'],
      ['beef', '/biːf/', 'thịt bò', 'She ordered a beef steak.', 'Cô ấy gọi một miếng bít tết bò.'],
      ['pork', '/pɔːk/', 'thịt heo', 'Pork is common in Vietnamese dishes.', 'Thịt heo phổ biến trong món ăn Việt.'],
      ['fish', '/fɪʃ/', 'cá', 'We had grilled fish for dinner.', 'Chúng tôi ăn cá nướng cho bữa tối.'],
      ['egg', '/eɡ/', 'trứng', 'I eat an egg every morning.', 'Tôi ăn một quả trứng mỗi sáng.'],
      ['vegetable', '/ˈvedʒtəbl/', 'rau củ', 'Eat more vegetables for good health.', 'Hãy ăn nhiều rau hơn để khỏe mạnh.'],
      ['fruit', '/fruːt/', 'trái cây', 'Fresh fruit is healthy for you.', 'Trái cây tươi tốt cho sức khỏe.'],
      ['milk', '/mɪlk/', 'sữa', 'Children should drink milk daily.', 'Trẻ em nên uống sữa mỗi ngày.'],
      ['water', '/ˈwɔːtə/', 'nước', 'Drink plenty of water every day.', 'Hãy uống nhiều nước mỗi ngày.'],
      ['coffee', '/ˈkɒfi/', 'cà phê', 'I drink coffee every morning.', 'Tôi uống cà phê mỗi sáng.'],
      ['tea', '/tiː/', 'trà', 'She prefers tea over coffee.', 'Cô ấy thích trà hơn cà phê.'],
      ['juice', '/dʒuːs/', 'nước ép', 'Fresh orange juice is delicious.', 'Nước cam tươi rất ngon.'],
      ['sugar', '/ˈʃʊɡə/', 'đường', 'Add a little sugar to the tea.', 'Thêm một chút đường vào trà.'],
      ['salt', '/sɔːlt/', 'muối', 'This soup needs more salt.', 'Món súp này cần thêm muối.'],
      ['pepper', '/ˈpepə/', 'tiêu', 'Add some pepper for extra flavor.', 'Thêm chút tiêu để tăng hương vị.'],
      ['oil', '/ɔɪl/', 'dầu ăn', 'Heat some oil in the pan.', 'Đun nóng một ít dầu trong chảo.'],
      ['soup', '/suːp/', 'súp, canh', 'The soup tastes really good.', 'Món súp ngon thật.'],
      ['sauce', '/sɔːs/', 'nước sốt', 'Dip the fries in the sauce.', 'Chấm khoai tây chiên vào sốt.'],
      ['dessert', '/dɪˈzɜːt/', 'món tráng miệng', 'We had ice cream for dessert.', 'Chúng tôi ăn kem làm món tráng miệng.'],
      ['snack bar', '/snæk bɑː/', 'quầy đồ ăn nhẹ', 'There\'s a snack bar near the office.', 'Có một quán ăn nhẹ gần văn phòng.'],
      ['cook', '/kʊk/', 'nấu ăn', 'My father loves to cook.', 'Bố tôi rất thích nấu ăn.'],
      ['bake', '/beɪk/', 'nướng (bánh)', 'She baked a cake for the party.', 'Cô ấy nướng bánh cho buổi tiệc.'],
      ['fry', '/fraɪ/', 'chiên', 'He fried some eggs for breakfast.', 'Anh ấy chiên trứng cho bữa sáng.'],
      ['boil', '/bɔɪl/', 'luộc', 'Boil the water before adding the noodles.', 'Đun sôi nước trước khi cho mì vào.'],
      ['grill', '/ɡrɪl/', 'nướng (vỉ)', 'We grilled some fish for dinner.', 'Chúng tôi nướng cá cho bữa tối.'],
      ['taste', '/teɪst/', 'nếm, vị', 'Can I taste your food?', 'Tôi có thể nếm đồ ăn của bạn không?'],
      ['delicious', '/dɪˈlɪʃəs/', 'ngon', 'This cake is delicious.', 'Chiếc bánh này rất ngon.'],
      ['sweet', '/swiːt/', 'ngọt', 'The mango is very sweet.', 'Quả xoài rất ngọt.'],
      ['sour', '/ˈsaʊə/', 'chua', 'The lemon tastes sour.', 'Quả chanh có vị chua.'],
      ['bitter', '/ˈbɪtə/', 'đắng', 'Black coffee can taste bitter.', 'Cà phê đen có thể có vị đắng.'],
      ['salty', '/ˈsɔːlti/', 'mặn', 'The soup is too salty.', 'Món súp mặn quá.'],
      ['spicy', '/ˈspaɪsi/', 'cay', 'I love spicy food.', 'Tôi thích đồ ăn cay.'],
      ['hungry', '/ˈhʌŋɡri/', 'đói', 'I\'m hungry, let\'s eat.', 'Tôi đói rồi, chúng ta ăn đi.'],
      ['thirsty', '/ˈθɜːsti/', 'khát', 'I\'m thirsty, may I have some water?', 'Tôi khát, cho tôi xin ít nước được không?'],
      ['full', '/fʊl/', 'no', 'I\'m full, I can\'t eat anymore.', 'Tôi no rồi, không ăn thêm được nữa.'],
      ['diet', '/ˈdaɪət/', 'chế độ ăn', 'She is on a healthy diet.', 'Cô ấy đang theo chế độ ăn lành mạnh.'],
      ['recipe', '/ˈresəpi/', 'công thức nấu ăn', 'I found a new recipe online.', 'Tôi tìm thấy một công thức mới trên mạng.'],
      ['ingredient', '/ɪnˈɡriːdiənt/', 'nguyên liệu', 'Flour is the main ingredient.', 'Bột mì là nguyên liệu chính.'],
      ['leftovers', '/ˈleftəʊvəz/', 'đồ ăn thừa', 'We ate the leftovers for lunch.', 'Chúng tôi ăn đồ thừa cho bữa trưa.'],
      ['order food', '/ˈɔːdə fuːd/', 'đặt đồ ăn', 'We ordered food online tonight.', 'Tối nay chúng tôi đặt đồ ăn trực tuyến.'],
      ['work', '/wɜːk/', 'công việc, làm việc', 'I go to work every weekday.', 'Tôi đi làm mỗi ngày trong tuần.'],
      ['job', '/dʒɒb/', 'công việc', 'She has a good job.', 'Cô ấy có một công việc tốt.'],
      ['office', '/ˈɒfɪs/', 'văn phòng', 'My office is downtown.', 'Văn phòng tôi ở trung tâm thành phố.'],
      ['boss', '/bɒs/', 'sếp', 'My boss is very strict.', 'Sếp tôi rất nghiêm khắc.'],
      ['employee', '/ɪmˈplɔɪiː/', 'nhân viên', 'The company has 50 employees.', 'Công ty có 50 nhân viên.'],
      ['employer', '/ɪmˈplɔɪə/', 'chủ lao động', 'The employer offers good benefits.', 'Người sử dụng lao động cung cấp phúc lợi tốt.'],
      ['meeting', '/ˈmiːtɪŋ/', 'cuộc họp', 'We have a meeting at 9 AM.', 'Chúng tôi có cuộc họp lúc 9 giờ sáng.'],
      ['deadline', '/ˈdedlaɪn/', 'hạn chót', 'The deadline is next Friday.', 'Hạn chót là thứ Sáu tuần sau.'],
      ['project', '/ˈprɒdʒekt/', 'dự án', 'We finished the project on time.', 'Chúng tôi hoàn thành dự án đúng hạn.'],
      ['task', '/tɑːsk/', 'nhiệm vụ', 'I have many tasks to finish today.', 'Hôm nay tôi có nhiều việc phải làm xong.'],
      ['salary', '/ˈsæləri/', 'lương', 'Her salary increased this year.', 'Lương của cô ấy tăng năm nay.'],
      ['promotion', '/prəˈməʊʃn/', 'thăng chức', 'He got a promotion last month.', 'Anh ấy được thăng chức tháng trước.'],
      ['resign', '/rɪˈzaɪn/', 'từ chức', 'She decided to resign from her job.', 'Cô ấy quyết định từ chức.'],
      ['interview', '/ˈɪntəvjuː/', 'phỏng vấn', 'I have a job interview tomorrow.', 'Ngày mai tôi có buổi phỏng vấn việc làm.'],
      ['resume', '/ˈrezjuːmeɪ/', 'sơ yếu lý lịch', 'Please send me your resume.', 'Xin hãy gửi sơ yếu lý lịch cho tôi.'],
      ['client', '/ˈklaɪənt/', 'khách hàng', 'We are meeting a client today.', 'Hôm nay chúng tôi gặp khách hàng.'],
      ['contract', '/ˈkɒntrækt/', 'hợp đồng', 'We signed the contract yesterday.', 'Hôm qua chúng tôi ký hợp đồng.'],
      ['schedule', '/ˈʃedjuːl/', 'lịch trình', 'Check your schedule for tomorrow.', 'Kiểm tra lịch của bạn cho ngày mai.'],
      ['presentation', '/ˌpreznˈteɪʃn/', 'bài thuyết trình', 'I have a presentation this afternoon.', 'Chiều nay tôi có buổi thuyết trình.'],
      ['report', '/rɪˈpɔːt/', 'báo cáo', 'Please submit the report by Friday.', 'Xin hãy nộp báo cáo trước thứ Sáu.'],
      ['document', '/ˈdɒkjumənt/', 'tài liệu', 'Sign this document, please.', 'Xin hãy ký tài liệu này.'],
      ['printer', '/ˈprɪntə/', 'máy in', 'The printer is out of paper.', 'Máy in hết giấy rồi.'],
      ['computer', '/kəmˈpjuːtə/', 'máy tính', 'I work on my computer all day.', 'Tôi làm việc trên máy tính cả ngày.'],
      ['internet', '/ˈɪntənet/', 'mạng internet', 'The internet connection is slow today.', 'Hôm nay kết nối internet chậm.'],
      ['overtime', '/ˈəʊvətaɪm/', 'làm thêm giờ', 'I worked overtime last night.', 'Tối qua tôi làm thêm giờ.'],
      ['break', '/breɪk/', 'giờ nghỉ', 'We have a 15-minute break.', 'Chúng tôi có giờ nghỉ 15 phút.'],
      ['vacation', '/vəˈkeɪʃn/', 'kỳ nghỉ', 'I\'m planning a vacation next month.', 'Tôi đang lên kế hoạch nghỉ phép tháng sau.'],
      ['absent', '/ˈæbsənt/', 'vắng mặt', 'He was absent from work today.', 'Hôm nay anh ấy vắng mặt ở chỗ làm.'],
      ['school', '/skuːl/', 'trường học', 'Children go to school every day.', 'Trẻ em đi học mỗi ngày.'],
      ['student', '/ˈstjuːdnt/', 'học sinh, sinh viên', 'She is a good student.', 'Cô ấy là một học sinh giỏi.'],
      ['teacher', '/ˈtiːtʃə/', 'giáo viên', 'Our teacher is very patient.', 'Giáo viên của chúng tôi rất kiên nhẫn.'],
      ['class', '/klɑːs/', 'lớp học', 'The class starts at 8 AM.', 'Lớp học bắt đầu lúc 8 giờ sáng.'],
      ['lesson', '/ˈlesn/', 'bài học', 'Today\'s lesson is about grammar.', 'Bài học hôm nay là về ngữ pháp.'],
      ['homework', '/ˈhəʊmwɜːk/', 'bài tập về nhà', 'I finished my homework early.', 'Tôi làm xong bài tập sớm.'],
      ['exam', '/ɪɡˈzæm/', 'kỳ thi', 'The final exam is next week.', 'Kỳ thi cuối kỳ là tuần sau.'],
      ['grade', '/ɡreɪd/', 'điểm số', 'She got a good grade on her test.', 'Cô ấy được điểm tốt trong bài kiểm tra.'],
      ['subject', '/ˈsʌbdʒɪkt/', 'môn học', 'Math is my favorite subject.', 'Toán là môn học yêu thích của tôi.'],
      ['university', '/ˌjuːnɪˈvɜːsəti/', 'trường đại học', 'He studies at a famous university.', 'Anh ấy học ở một trường đại học nổi tiếng.'],
      ['degree', '/dɪˈɡriː/', 'bằng cấp', 'She has a degree in business.', 'Cô ấy có bằng về kinh doanh.'],
      ['graduate', '/ˈɡrædʒueɪt/', 'tốt nghiệp', 'I will graduate next year.', 'Tôi sẽ tốt nghiệp năm sau.'],
      ['classmate', '/ˈklɑːsmeɪt/', 'bạn cùng lớp', 'My classmates are very friendly.', 'Bạn cùng lớp của tôi rất thân thiện.'],
      ['lecture', '/ˈlektʃə/', 'bài giảng', 'The lecture lasted two hours.', 'Bài giảng kéo dài hai giờ.'],
      ['library', '/ˈlaɪbrəri/', 'thư viện', 'I study in the library after class.', 'Tôi học ở thư viện sau giờ học.'],
      ['textbook', '/ˈtekstbʊk/', 'sách giáo khoa', 'Bring your textbook to class.', 'Mang sách giáo khoa đến lớp nhé.'],
      ['scholarship', '/ˈskɒləʃɪp/', 'học bổng', 'She won a scholarship to study abroad.', 'Cô ấy nhận được học bổng để du học.'],
      ['career', '/kəˈrɪə/', 'sự nghiệp', 'He wants to build a career in IT.', 'Anh ấy muốn xây dựng sự nghiệp trong ngành CNTT.'],
      ['skill', '/skɪl/', 'kỹ năng', 'Communication is an important skill.', 'Giao tiếp là một kỹ năng quan trọng.'],
      ['experience', '/ɪkˈspɪəriəns/', 'kinh nghiệm', 'She has five years of experience.', 'Cô ấy có năm năm kinh nghiệm.'],
      ['time', '/taɪm/', 'thời gian', 'What time is it now?', 'Bây giờ là mấy giờ?'],
      ['today', '/təˈdeɪ/', 'hôm nay', 'What are your plans today?', 'Hôm nay bạn có kế hoạch gì?'],
      ['tomorrow', '/təˈmɒrəʊ/', 'ngày mai', 'See you tomorrow.', 'Hẹn gặp lại ngày mai.'],
      ['yesterday', '/ˈjestədeɪ/', 'hôm qua', 'I met her yesterday.', 'Tôi gặp cô ấy hôm qua.'],
      ['now', '/naʊ/', 'bây giờ', 'I need to leave now.', 'Bây giờ tôi cần đi rồi.'],
      ['later', '/ˈleɪtə/', 'sau đó, lát nữa', 'I\'ll call you later.', 'Tôi sẽ gọi bạn sau.'],
      ['soon', '/suːn/', 'sớm thôi', 'The bus will arrive soon.', 'Xe buýt sẽ đến sớm thôi.'],
      ['early', '/ˈɜːli/', 'sớm', 'I woke up early today.', 'Hôm nay tôi dậy sớm.'],
      ['late', '/leɪt/', 'trễ, muộn', 'Sorry, I\'m running late.', 'Xin lỗi, tôi đang đến muộn.'],
      ['morning', '/ˈmɔːnɪŋ/', 'buổi sáng', 'I exercise every morning.', 'Tôi tập thể dục mỗi sáng.'],
      ['afternoon', '/ˌɑːftəˈnuːn/', 'buổi chiều', 'We\'ll meet in the afternoon.', 'Chúng ta sẽ gặp nhau vào buổi chiều.'],
      ['evening', '/ˈiːvnɪŋ/', 'buổi tối', 'I relax in the evening.', 'Tôi thư giãn vào buổi tối.'],
      ['night', '/naɪt/', 'ban đêm', 'It\'s very quiet at night.', 'Ban đêm rất yên tĩnh.'],
      ['week', '/wiːk/', 'tuần', 'I have a busy week ahead.', 'Tuần tới tôi sẽ rất bận.'],
      ['weekend', '/ˌwiːkˈend/', 'cuối tuần', 'What are you doing this weekend?', 'Cuối tuần này bạn làm gì?'],
      ['weekday', '/ˈwiːkdeɪ/', 'ngày trong tuần', 'I work on weekdays.', 'Tôi làm việc vào các ngày trong tuần.'],
      ['month', '/mʌnθ/', 'tháng', 'This month has 30 days.', 'Tháng này có 30 ngày.'],
      ['year', '/jɪə/', 'năm', 'This year has been great so far.', 'Năm nay đến giờ vẫn rất tuyệt.'],
      ['hour', '/ˈaʊə/', 'giờ', 'The meeting lasted one hour.', 'Cuộc họp kéo dài một giờ.'],
      ['minute', '/ˈmɪnɪt/', 'phút', 'Wait a minute, please.', 'Xin chờ một phút.'],
      ['second', '/ˈsekənd/', 'giây', 'It only takes a few seconds.', 'Chỉ mất vài giây thôi.'],
      ['calendar', '/ˈkælɪndə/', 'lịch', 'Mark the date on your calendar.', 'Đánh dấu ngày đó trên lịch của bạn.'],
      ['appointment', '/əˈpɔɪntmənt/', 'cuộc hẹn', 'I have a doctor\'s appointment today.', 'Hôm nay tôi có lịch hẹn với bác sĩ.'],
      ['timetable', '/ˈtaɪmteɪbl/', 'thời gian biểu', 'Check the timetable for train times.', 'Xem thời gian biểu để biết giờ tàu.'],
      ['postpone', '/pəˈspəʊn/', 'hoãn lại', 'We postponed the meeting to next week.', 'Chúng tôi hoãn cuộc họp sang tuần sau.'],
      ['punctual', '/ˈpʌŋktʃuəl/', 'đúng giờ', 'He is always punctual.', 'Anh ấy luôn đúng giờ.'],
      ['delay', '/dɪˈleɪ/', 'trì hoãn', 'The flight was delayed by an hour.', 'Chuyến bay bị hoãn một giờ.'],
      ['hurry', '/ˈhʌri/', 'vội vàng', 'Hurry up, we\'re going to be late.', 'Nhanh lên, chúng ta sắp muộn rồi.'],
      ['wait', '/weɪt/', 'chờ đợi', 'Please wait here for a moment.', 'Xin hãy đợi đây một chút.'],
      ['on time', '/ɒn taɪm/', 'đúng giờ', 'The train arrived on time.', 'Tàu đến đúng giờ.'],
      ['in advance', '/ɪn ədˈvɑːns/', 'trước (thời hạn)', 'Book your ticket in advance.', 'Hãy đặt vé trước.'],
      ['recently', '/ˈriːsntli/', 'gần đây', 'I recently moved to a new city.', 'Gần đây tôi chuyển đến một thành phố mới.'],
      ['usually', '/ˈjuːʒuəli/', 'thường thường', 'I usually wake up at 6 AM.', 'Tôi thường thức dậy lúc 6 giờ sáng.'],
      ['sometimes', '/ˈsʌmtaɪmz/', 'đôi khi', 'Sometimes I work from home.', 'Đôi khi tôi làm việc ở nhà.'],
      ['always', '/ˈɔːlweɪz/', 'luôn luôn', 'She always arrives early.', 'Cô ấy luôn đến sớm.'],
      ['never', '/ˈnevə/', 'không bao giờ', 'He never lies.', 'Anh ấy không bao giờ nói dối.'],
      ['often', '/ˈɒfn/', 'thường xuyên', 'We often go out for dinner.', 'Chúng tôi thường đi ăn tối ngoài.'],
      ['rarely', '/ˈreəli/', 'hiếm khi', 'I rarely watch TV.', 'Tôi ít khi xem TV.'],
      ['every day', '/ˈevri deɪ/', 'mỗi ngày', 'I read every day.', 'Tôi đọc sách mỗi ngày.'],
      ['once', '/wʌns/', 'một lần', 'I visited Paris once.', 'Tôi đã đến Paris một lần.'],
      ['twice', '/twaɪs/', 'hai lần', 'I exercise twice a week.', 'Tôi tập thể dục hai lần một tuần.'],
      ['daily', '/ˈdeɪli/', 'hàng ngày', 'This is my daily habit.', 'Đây là thói quen hàng ngày của tôi.'],
      ['weekly', '/ˈwiːkli/', 'hàng tuần', 'We have a weekly meeting.', 'Chúng tôi có cuộc họp hàng tuần.'],
      ['monthly', '/ˈmʌnθli/', 'hàng tháng', 'He pays rent monthly.', 'Anh ấy trả tiền thuê nhà hàng tháng.'],
      ['annually', '/ˈænjuəli/', 'hàng năm', 'The event happens annually.', 'Sự kiện diễn ra hàng năm.'],
      ['past', '/pɑːst/', 'quá khứ', 'Let\'s not dwell on the past.', 'Đừng mãi nghĩ về quá khứ.'],
      ['present', '/ˈpreznt/', 'hiện tại', 'Focus on the present moment.', 'Hãy tập trung vào khoảnh khắc hiện tại.'],
      ['future', '/ˈfjuːtʃə/', 'tương lai', 'I\'m excited about the future.', 'Tôi hào hứng về tương lai.'],
      ['duration', '/djʊˈreɪʃn/', 'khoảng thời gian', 'The duration of the flight is 3 hours.', 'Thời gian bay là 3 giờ.'],
      ['moment', '/ˈməʊmənt/', 'khoảnh khắc', 'Wait a moment, please.', 'Xin chờ một chút.'],
      ['phone', '/fəʊn/', 'điện thoại', 'I forgot my phone at home.', 'Tôi quên điện thoại ở nhà.'],
      ['smartphone', '/ˈsmɑːtfəʊn/', 'điện thoại thông minh', 'Everyone has a smartphone nowadays.', 'Ngày nay mọi người đều có điện thoại thông minh.'],
      ['call', '/kɔːl/', 'gọi điện', 'I\'ll call you tonight.', 'Tối nay tôi sẽ gọi bạn.'],
      ['text', '/tekst/', 'nhắn tin', 'Text me when you arrive.', 'Nhắn tin cho tôi khi bạn đến.'],
      ['message', '/ˈmesɪdʒ/', 'tin nhắn', 'I sent you a message earlier.', 'Tôi đã gửi tin nhắn cho bạn lúc nãy.'],
      ['wifi', '/ˈwaɪfaɪ/', 'wifi', 'What\'s the wifi password?', 'Mật khẩu wifi là gì?'],
      ['app', '/æp/', 'ứng dụng', 'I downloaded a new app.', 'Tôi tải một ứng dụng mới.'],
      ['social media', '/ˈsəʊʃl ˈmiːdiə/', 'mạng xã hội', 'She spends a lot of time on social media.', 'Cô ấy dành nhiều thời gian trên mạng xã hội.'],
      ['video call', '/ˈvɪdiəʊ kɔːl/', 'gọi video', 'We had a video call yesterday.', 'Hôm qua chúng tôi gọi video.'],
      ['laptop', '/ˈlæptɒp/', 'máy tính xách tay', 'I bought a new laptop.', 'Tôi mua một chiếc laptop mới.'],
      ['screen', '/skriːn/', 'màn hình', 'The screen is cracked.', 'Màn hình bị nứt.'],
      ['keyboard', '/ˈkiːbɔːd/', 'bàn phím', 'This keyboard is very comfortable.', 'Bàn phím này rất thoải mái.'],
      ['mouse', '/maʊs/', 'chuột (máy tính)', 'My mouse stopped working.', 'Chuột của tôi ngừng hoạt động.'],
      ['charger', '/ˈtʃɑːdʒə/', 'bộ sạc', 'Can I borrow your charger?', 'Tôi có thể mượn bộ sạc của bạn không?'],
      ['battery', '/ˈbætəri/', 'pin', 'My phone battery is low.', 'Pin điện thoại tôi sắp hết.'],
      ['update', '/ʌpˈdeɪt/', 'cập nhật', 'Please update the app.', 'Xin hãy cập nhật ứng dụng.'],
      ['download', '/ˌdaʊnˈləʊd/', 'tải xuống', 'I downloaded the file.', 'Tôi đã tải tệp xuống.'],
      ['upload', '/ʌpˈləʊd/', 'tải lên', 'She uploaded the photos online.', 'Cô ấy tải ảnh lên mạng.'],
      ['password', '/ˈpɑːswɜːd/', 'mật khẩu', 'I forgot my password.', 'Tôi quên mật khẩu.'],
      ['account', '/əˈkaʊnt/', 'tài khoản', 'I created a new account.', 'Tôi tạo một tài khoản mới.'],
      ['website', '/ˈwebsaɪt/', 'trang web', 'Check the website for details.', 'Xem trang web để biết chi tiết.'],
      ['search', '/sɜːtʃ/', 'tìm kiếm', 'I searched for the information online.', 'Tôi tìm thông tin trên mạng.'],
      ['click', '/klɪk/', 'nhấp chuột', 'Click the button to continue.', 'Nhấn nút để tiếp tục.'],
      ['camera', '/ˈkæmərə/', 'máy ảnh', 'The phone camera takes great photos.', 'Camera điện thoại chụp ảnh rất đẹp.'],
      ['photo', '/ˈfəʊtəʊ/', 'ảnh', 'She took a photo of the sunset.', 'Cô ấy chụp ảnh hoàng hôn.'],
      ['video', '/ˈvɪdiəʊ/', 'video', 'We watched a funny video.', 'Chúng tôi xem một video hài hước.'],
      ['contact', '/ˈkɒntækt/', 'liên hệ', 'Please add me to your contacts.', 'Xin hãy thêm tôi vào danh bạ của bạn.'],
      ['reply', '/rɪˈplaɪ/', 'trả lời', 'Please reply to my message.', 'Xin hãy trả lời tin nhắn của tôi.'],
      ['share', '/ʃeə/', 'chia sẻ', 'She shared the news with everyone.', 'Cô ấy chia sẻ tin tức với mọi người.'],
      ['post', '/pəʊst/', 'đăng bài', 'He posted a new photo online.', 'Anh ấy đăng một bức ảnh mới lên mạng.'],
      ['comment', '/ˈkɒment/', 'bình luận', 'I left a comment on her post.', 'Tôi để lại bình luận trên bài đăng của cô ấy.'],
      ['like', '/laɪk/', 'thích (nút like)', 'I liked your photo.', 'Tôi thích ảnh của bạn.'],
      ['follow', '/ˈfɒləʊ/', 'theo dõi', 'I follow her on social media.', 'Tôi theo dõi cô ấy trên mạng xã hội.'],
      ['subscribe', '/səbˈskraɪb/', 'đăng ký (kênh)', 'Subscribe to the channel for updates.', 'Đăng ký kênh để nhận cập nhật.'],
      ['notification', '/ˌnəʊtɪfɪˈkeɪʃn/', 'thông báo', 'I got a notification from the app.', 'Tôi nhận được thông báo từ ứng dụng.'],
      ['signal', '/ˈsɪɡnəl/', 'tín hiệu', 'The phone signal is weak here.', 'Tín hiệu điện thoại ở đây yếu.'],
      ['device', '/dɪˈvaɪs/', 'thiết bị', 'This device is very useful.', 'Thiết bị này rất hữu ích.'],
      ['connect', '/kəˈnekt/', 'kết nối', 'Connect your phone to the wifi.', 'Kết nối điện thoại của bạn với wifi.'],
      ['disconnect', '/ˌdɪskəˈnekt/', 'ngắt kết nối', 'The call disconnected suddenly.', 'Cuộc gọi đột ngột bị ngắt.'],
      ['install', '/ɪnˈstɔːl/', 'cài đặt', 'I installed a new app.', 'Tôi cài một ứng dụng mới.'],
      ['software', '/ˈsɒftweə/', 'phần mềm', 'The software needs an update.', 'Phần mềm cần được cập nhật.'],
      ['file', '/faɪl/', 'tệp tin', 'I sent you the file by email.', 'Tôi gửi tệp cho bạn qua email.'],
      ['attach', '/əˈtætʃ/', 'đính kèm', 'Please attach the document to your email.', 'Xin hãy đính kèm tài liệu vào email của bạn.'],
      ['link', '/lɪŋk/', 'liên kết', 'Click on this link for more info.', 'Nhấn vào liên kết này để biết thêm thông tin.'],
      ['online', '/ˈɒnlaɪn/', 'trực tuyến', 'I study English online.', 'Tôi học tiếng Anh trực tuyến.'],
      ['offline', '/ˈɒflaɪn/', 'ngoại tuyến', 'The app works offline too.', 'Ứng dụng cũng hoạt động khi ngoại tuyến.'],
      ['voicemail', '/ˈvɔɪsmeɪl/', 'hộp thư thoại', 'Leave a message on my voicemail.', 'Để lại tin nhắn trong hộp thư thoại của tôi.'],
      ['ring', '/rɪŋ/', 'đổ chuông', 'My phone rang during the meeting.', 'Điện thoại tôi reo trong buổi họp.'],
      ['missed call', '/mɪst kɔːl/', 'cuộc gọi nhỡ', 'You have three missed calls.', 'Bạn có ba cuộc gọi nhỡ.'],
      ['good', '/ɡʊd/', 'tốt', 'That\'s a good idea.', 'Đó là một ý tưởng hay.'],
      ['bad', '/bæd/', 'tệ, xấu', 'The weather is bad today.', 'Hôm nay thời tiết xấu.'],
      ['big', '/bɪɡ/', 'to, lớn', 'They live in a big house.', 'Họ sống trong một ngôi nhà lớn.'],
      ['small', '/smɔːl/', 'nhỏ', 'She has a small dog.', 'Cô ấy có một con chó nhỏ.'],
      ['new', '/njuː/', 'mới', 'I bought a new bag.', 'Tôi mua một cái túi mới.'],
      ['old', '/əʊld/', 'cũ, già', 'This is an old building.', 'Đây là một tòa nhà cũ.'],
      ['easy', '/ˈiːzi/', 'dễ', 'The test was easy.', 'Bài kiểm tra rất dễ.'],
      ['difficult', '/ˈdɪfɪkəlt/', 'khó', 'This question is difficult.', 'Câu hỏi này khó.'],
      ['important', '/ɪmˈpɔːtnt/', 'quan trọng', 'Health is very important.', 'Sức khỏe rất quan trọng.'],
      ['interesting', '/ˈɪntrəstɪŋ/', 'thú vị', 'This book is very interesting.', 'Cuốn sách này rất thú vị.'],
      ['boring', '/ˈbɔːrɪŋ/', 'nhàm chán', 'The movie was quite boring.', 'Bộ phim khá nhàm chán.'],
      ['beautiful', '/ˈbjuːtɪfl/', 'đẹp', 'The view is beautiful.', 'Quang cảnh rất đẹp.'],
      ['ugly', '/ˈʌɡli/', 'xấu xí', 'I think that painting is ugly.', 'Tôi nghĩ bức tranh đó xấu.'],
      ['fast', '/fɑːst/', 'nhanh', 'He runs very fast.', 'Anh ấy chạy rất nhanh.'],
      ['slow', '/sləʊ/', 'chậm', 'The traffic is very slow today.', 'Hôm nay giao thông rất chậm.'],
      ['strong', '/strɒŋ/', 'mạnh, khỏe', 'He is very strong.', 'Anh ấy rất khỏe.'],
      ['weak', '/wiːk/', 'yếu', 'I feel weak after being sick.', 'Tôi thấy yếu sau khi ốm.'],
      ['rich', '/rɪtʃ/', 'giàu', 'They are a rich family.', 'Họ là một gia đình giàu có.'],
      ['poor', '/pɔː/', 'nghèo', 'The charity helps poor families.', 'Tổ chức từ thiện giúp các gia đình nghèo.'],
      ['clean', '/kliːn/', 'sạch sẽ', 'Keep your room clean.', 'Giữ phòng của bạn sạch sẽ.'],
      ['dirty', '/ˈdɜːti/', 'bẩn', 'His shoes are very dirty.', 'Giày của anh ấy rất bẩn.'],
      ['quiet', '/ˈkwaɪət/', 'yên tĩnh', 'The library is very quiet.', 'Thư viện rất yên tĩnh.'],
      ['loud', '/laʊd/', 'ồn ào', 'The music is too loud.', 'Nhạc to quá.'],
      ['kind', '/kaɪnd/', 'tốt bụng', 'She is a kind person.', 'Cô ấy là một người tốt bụng.'],
      ['rude', '/ruːd/', 'thô lỗ', 'It\'s rude to interrupt someone.', 'Ngắt lời người khác là bất lịch sự.'],
      ['polite', '/pəˈlaɪt/', 'lịch sự', 'He is always polite to strangers.', 'Anh ấy luôn lịch sự với người lạ.'],
      ['honest', '/ˈɒnɪst/', 'trung thực', 'You should always be honest.', 'Bạn nên luôn trung thực.'],
      ['lazy', '/ˈleɪzi/', 'lười biếng', 'Don\'t be lazy, finish your work.', 'Đừng lười biếng, hãy làm xong việc đi.'],
      ['hardworking', '/ˈhɑːdwɜːkɪŋ/', 'chăm chỉ', 'She is a hardworking student.', 'Cô ấy là một học sinh chăm chỉ.'],
      ['friendly', '/ˈfrendli/', 'thân thiện', 'The staff here are very friendly.', 'Nhân viên ở đây rất thân thiện.'],
      ['helpful', '/ˈhelpfl/', 'hữu ích, sẵn lòng giúp', 'Thank you, you\'ve been very helpful.', 'Cảm ơn, bạn đã rất hữu ích.'],
      ['careful', '/ˈkeəfl/', 'cẩn thận', 'Be careful when crossing the street.', 'Hãy cẩn thận khi sang đường.'],
      ['careless', '/ˈkeələs/', 'bất cẩn', 'He made a careless mistake.', 'Anh ấy mắc một lỗi do bất cẩn.'],
      ['brave', '/breɪv/', 'dũng cảm', 'The firefighter was very brave.', 'Người lính cứu hỏa rất dũng cảm.'],
      ['patient', '/ˈpeɪʃnt/', 'kiên nhẫn', 'You need to be patient with children.', 'Bạn cần kiên nhẫn với trẻ em.'],
      ['certainly', '/ˈsɜːtnli/', 'chắc chắn', 'Certainly, I\'ll help you with that.', 'Chắc chắn rồi, tôi sẽ giúp bạn việc đó.'],
      ['probably', '/ˈprɒbəbli/', 'có lẽ', 'It will probably rain today.', 'Hôm nay có lẽ sẽ mưa.'],
      ['actually', '/ˈæktʃuəli/', 'thực ra', 'Actually, I think you\'re right.', 'Thực ra, tôi nghĩ bạn đúng.'],
      ['quickly', '/ˈkwɪkli/', 'nhanh chóng', 'Please finish this quickly.', 'Xin hãy hoàn thành việc này nhanh chóng.'],
      ['slowly', '/ˈsləʊli/', 'chậm rãi', 'He walked slowly to the door.', 'Anh ấy đi chậm về phía cửa.'],
      ['suddenly', '/ˈsʌdənli/', 'đột nhiên', 'Suddenly, it started to rain.', 'Đột nhiên trời bắt đầu mưa.'],
      ['finally', '/ˈfaɪnəli/', 'cuối cùng', 'Finally, we arrived home.', 'Cuối cùng chúng tôi cũng về đến nhà.'],
      ['maybe', '/ˈmeɪbi/', 'có thể', 'Maybe we can meet tomorrow.', 'Có lẽ chúng ta có thể gặp nhau ngày mai.'],
      ['of course', '/əv kɔːs/', 'tất nhiên', 'Of course, I\'ll come to your party.', 'Tất nhiên, tôi sẽ đến buổi tiệc của bạn.'],
      ['by the way', '/baɪ ðə weɪ/', 'nhân tiện', 'By the way, did you call her?', 'Nhân tiện, bạn đã gọi cô ấy chưa?'],
      ['no problem', '/nəʊ ˈprɒbləm/', 'không vấn đề gì', 'No problem, I\'m happy to help.', 'Không sao, tôi vui lòng giúp đỡ.'],
      ['it depends', '/ɪt dɪˈpendz/', 'còn tùy', 'It depends on the weather.', 'Điều đó phụ thuộc vào thời tiết.'],
      ['I guess', '/aɪ ɡes/', 'tôi đoán là', 'I guess we should leave now.', 'Tôi đoán chúng ta nên đi ngay bây giờ.'],
      ['as far as I know', '/əz fɑːr əz aɪ nəʊ/', 'theo tôi biết', 'As far as I know, the shop closes at 9.', 'Theo tôi biết, cửa hàng đóng cửa lúc 9 giờ.'],
      ['that\'s right', '/ðæts raɪt/', 'đúng vậy', 'That\'s right, you understand correctly.', 'Đúng rồi, bạn hiểu đúng rồi.'],
      ['I\'m not sure', '/aɪm nɒt ʃʊə/', 'tôi không chắc', 'I\'m not sure if the store is open.', 'Tôi không chắc cửa hàng có mở không.'],
      ['let me think', '/let miː θɪŋk/', 'để tôi suy nghĩ', 'Let me think about it for a moment.', 'Để tôi nghĩ về việc đó một chút.'],
      ['make sense', '/meɪk sens/', 'hợp lý, dễ hiểu', 'Does this explanation make sense to you?', 'Giải thích này có hợp lý với bạn không?'],
  ],
};
