import { CefrLevel } from '@prisma/client';
import type { VocabularySeedSet } from './vocabulary-tech-sets';

export const MOVIE_VOCABULARY_SET: VocabularySeedSet = {
  slug: 'phim-anh-giai-tri',
  title: 'Phim ảnh & Giải trí',
  description:
    '200 từ vựng phim ảnh và giải trí: thể loại, đoàn làm phim, cốt truyện, diễn xuất, truyền hình, âm nhạc và đánh giá',
  icon: 'clapperboard',
  color: 'pink',
  cefrLevel: CefrLevel.B1,
  topic: 'Giải trí',
  isFeatured: false,
  sortOrder: 4,
  words: [
      ['action', '/ˈækʃn/', 'hành động', 'The action movie kept me on the edge of my seat.', 'Bộ phim hành động khiến tôi hồi hộp đến mức ngồi không yên.'],
      ['comedy', '/ˈkɒmədi/', 'hài kịch', 'We watched a comedy to cheer ourselves up.', 'Chúng tôi xem một bộ phim hài để khuây khỏa tinh thần.'],
      ['drama', '/ˈdrɑːmə/', 'chính kịch / Phim tâm lý', 'The drama explores a family\'s struggles.', 'Bộ chính kịch khai thác những khó khăn của một gia đình.'],
      ['horror', '/ˈhɒrər/', 'kinh dị', 'I love horror movies, especially at Halloween.', 'Tôi rất thích phim kinh dị, đặc biệt vào dịp Halloween.'],
      ['thriller', '/ˈθrɪlər/', 'giật gân / Ly kỳ', 'The thriller kept us guessing until the end.', 'Bộ phim giật gân khiến chúng tôi đoán mãi đến tận cuối phim.'],
      ['romance', '/rəʊˈmæns/', 'lãng mạn', 'She enjoys watching romance films on weekends.', 'Cô ấy thích xem phim lãng mạn vào cuối tuần.'],
      ['science fiction (sci-fi)', '/ˌsaɪəns ˈfɪkʃn/', 'khoa học viễn tưởng', 'The sci-fi film is set on a distant planet.', 'Bộ phim khoa học viễn tưởng lấy bối cảnh trên một hành tinh xa xôi.'],
      ['fantasy', '/ˈfæntəsi/', 'giả tưởng', 'The fantasy movie features dragons and wizards.', 'Bộ phim giả tưởng có những con rồng và phù thủy.'],
      ['animation', '/ˌænɪˈmeɪʃn/', 'phim hoạt hình', 'Kids love animation films with colorful characters.', 'Trẻ em rất thích phim hoạt hình với những nhân vật đầy màu sắc.'],
      ['documentary', '/ˌdɒkjuˈmentri/', 'phim tài liệu', 'The documentary reveals the truth about climate change.', 'Bộ phim tài liệu hé lộ sự thật về biến đổi khí hậu.'],
      ['mystery', '/ˈmɪstri/', 'bí ẩn', 'The mystery movie has a surprising culprit.', 'Bộ phim bí ẩn có một thủ phạm bất ngờ.'],
      ['adventure', '/ədˈventʃər/', 'phiêu lưu', 'The adventure film takes place in the jungle.', 'Bộ phim phiêu lưu diễn ra trong khu rừng nhiệt đới.'],
      ['musical', '/ˈmjuːzɪkl/', 'nhạc kịch', 'The musical combines singing and dancing.', 'Bộ nhạc kịch kết hợp cả hát và nhảy.'],
      ['war film', '/wɔːr fɪlm/', 'phim chiến tranh', 'The war film depicts the horrors of battle.', 'Bộ phim chiến tranh khắc họa những nỗi kinh hoàng của trận chiến.'],
      ['western', '/ˈwestərn/', 'phim viễn Tây', 'The western is set in the Old American West.', 'Bộ phim viễn Tây lấy bối cảnh miền Tây nước Mỹ thời xưa.'],
      ['crime', '/kraɪm/', 'tội phạm', 'The crime movie follows a detective solving a murder.', 'Bộ phim tội phạm theo chân một thám tử phá án mạng.'],
      ['biopic', '/ˈbaɪəʊpɪk/', 'phim tiểu sử', 'The biopic tells the life story of a famous singer.', 'Bộ phim tiểu sử kể câu chuyện cuộc đời của một ca sĩ nổi tiếng.'],
      ['historical film', '/hɪˈstɒrɪkl fɪlm/', 'phim lịch sử', 'The historical film recreates events from the war.', 'Bộ phim lịch sử tái hiện những sự kiện từ cuộc chiến tranh.'],
      ['superhero movie', '/ˈsuːpərhɪərəʊ ˈmuːvi/', 'phim siêu anh hùng', 'Kids adore superhero movies with amazing powers.', 'Trẻ em rất mê phim siêu anh hùng với những siêu năng lực tuyệt vời.'],
      ['parody', '/ˈpærədi/', 'phim nhại / châm biếm', 'The parody makes fun of famous movie clichés.', 'Bộ phim nhại chế giễu những khuôn mẫu quen thuộc trong phim nổi tiếng.'],
      ['director', '/dəˈrektər/', 'đạo diễn', 'The director gave clear instructions to the actors.', 'Đạo diễn đưa ra những chỉ dẫn rõ ràng cho các diễn viên.'],
      ['producer', '/prəˈdjuːsər/', 'nhà sản xuất', 'The producer financed the entire film.', 'Nhà sản xuất đã tài trợ toàn bộ bộ phim.'],
      ['screenwriter', '/ˈskriːnraɪtər/', 'biên kịch', 'The screenwriter wrote an emotional script.', 'Biên kịch đã viết một kịch bản đầy cảm xúc.'],
      ['actor', '/ˈæktər/', 'diễn viên nam', 'The actor performed his role brilliantly.', 'Diễn viên nam thể hiện vai diễn của mình xuất sắc.'],
      ['actress', '/ˈæktrəs/', 'diễn viên nữ', 'The actress won an award for her role.', 'Diễn viên nữ đã giành được một giải thưởng cho vai diễn của mình.'],
      ['cast', '/kɑːst/', 'dàn diễn viên', 'The film has a talented cast.', 'Bộ phim có một dàn diễn viên tài năng.'],
      ['crew', '/kruː/', 'đoàn làm phim', 'The crew worked hard behind the scenes.', 'Đoàn làm phim đã làm việc rất chăm chỉ phía sau hậu trường.'],
      ['cinematographer', '/ˌsɪnəməˈtɒɡrəfər/', 'đạo diễn hình ảnh', 'The cinematographer captured stunning landscapes.', 'Đạo diễn hình ảnh đã ghi lại những khung cảnh thiên nhiên tuyệt đẹp.'],
      ['editor', '/ˈedɪtər/', 'người dựng phim', 'The editor cut the footage into a coherent story.', 'Người dựng phim đã cắt các thước phim thành một câu chuyện mạch lạc.'],
      ['composer', '/kəmˈpəʊzər/', 'nhà soạn nhạc', 'The composer wrote the film\'s original score.', 'Nhà soạn nhạc đã viết nhạc nền gốc cho bộ phim.'],
      ['costume designer', '/ˈkɒstjuːm dɪˈzaɪnər/', 'nhà thiết kế trang phục', 'The costume designer created stunning outfits.', 'Nhà thiết kế trang phục đã tạo ra những bộ trang phục tuyệt đẹp.'],
      ['makeup artist', '/ˈmeɪkʌp ˈɑːtɪst/', 'chuyên viên trang điểm', 'The makeup artist transformed the actor into a monster.', 'Chuyên viên trang điểm đã biến diễn viên thành một quái vật.'],
      ['stunt double', '/stʌnt ˈdʌbl/', 'diễn viên đóng thế', 'The stunt double performed the dangerous car chase.', 'Diễn viên đóng thế đã thực hiện cảnh đuổi xe nguy hiểm.'],
      ['extra', '/ˈekstrə/', 'diễn viên quần chúng', 'Hundreds of extras appeared in the battle scene.', 'Hàng trăm diễn viên quần chúng xuất hiện trong cảnh chiến đấu.'],
      ['casting director', '/ˈkɑːstɪŋ dəˈrektər/', 'đạo diễn tuyển vai', 'The casting director chose the perfect actors.', 'Đạo diễn tuyển vai đã chọn những diễn viên hoàn hảo.'],
      ['set designer', '/set dɪˈzaɪnər/', 'nhà thiết kế bối cảnh', 'The set designer built a realistic medieval village.', 'Nhà thiết kế bối cảnh đã dựng một ngôi làng thời trung cổ rất chân thực.'],
      ['sound engineer', '/saʊnd ˌendʒɪˈnɪər/', 'kỹ sư âm thanh', 'The sound engineer mixed the dialogue and music.', 'Kỹ sư âm thanh đã hòa trộn lời thoại và nhạc.'],
      ['visual effects (vfx) artist', '/ˈvɪʒuəl ɪˈfekts ˈɑːtɪst/', 'chuyên viên kỹ xảo hình ảnh', 'The VFX artist created realistic explosions.', 'Chuyên viên kỹ xảo hình ảnh đã tạo ra những vụ nổ chân thực.'],
      ['executive producer', '/ɪɡˈzekjətɪv prəˈdjuːsər/', 'nhà sản xuất điều hành', 'The executive producer oversaw the whole project.', 'Nhà sản xuất điều hành đã giám sát toàn bộ dự án.'],
      ['assistant director', '/əˈsɪstənt dəˈrektər/', 'trợ lý đạo diễn', 'The assistant director managed the daily schedule.', 'Trợ lý đạo diễn đã quản lý lịch trình hàng ngày.'],
      ['script', '/skrɪpt/', 'kịch bản', 'The actors memorized the script.', 'Các diễn viên đã thuộc lòng kịch bản.'],
      ['screenplay', '/ˈskriːnpleɪ/', 'kịch bản phim', 'The screenplay won an award for best writing.', 'Kịch bản phim đã đoạt giải viết hay nhất.'],
      ['storyboard', '/ˈstɔːriːbɔːd/', 'bảng phân cảnh', 'The director sketched a storyboard before filming.', 'Đạo diễn đã phác thảo bảng phân cảnh trước khi quay.'],
      ['shooting', '/ˈʃuːtɪŋ/', 'quay phim', 'Shooting began in the early morning.', 'Việc quay phim bắt đầu vào sáng sớm.'],
      ['filming', '/ˈfɪlmɪŋ/', 'việc quay phim', 'Filming took place in three countries.', 'Việc quay phim diễn ra ở ba quốc gia.'],
      ['production', '/prəˈdʌkʃn/', 'sản xuất (phim)', 'The production cost millions of dollars.', 'Việc sản xuất đã tốn hàng triệu đô la.'],
      ['post-production', '/pəʊst prəˈdʌkʃn/', 'hậu kỳ', 'Post-production includes editing and sound mixing.', 'Hậu kỳ bao gồm dựng phim và hòa âm.'],
      ['pre-production', '/priː prəˈdʌkʃn/', 'tiền kỳ', 'Pre-production involves planning and casting.', 'Tiền kỳ bao gồm việc lập kế hoạch và tuyển vai.'],
      ['rehearsal', '/rɪˈhɜːsl/', 'buổi diễn tập', 'The actors had a rehearsal before the real shoot.', 'Các diễn viên đã có một buổi diễn tập trước khi quay thật.'],
      ['take', '/teɪk/', 'lần quay', 'They needed ten takes to get the scene right.', 'Họ cần mười lần quay để làm đúng cảnh đó.'],
      ['scene', '/siːn/', 'cảnh quay', 'The final scene made everyone cry.', 'Cảnh cuối khiến mọi người khóc.'],
      ['shot', '/ʃɒt/', 'cú máy quay', 'The opening shot shows a beautiful sunset.', 'Cú máy mở đầu cho thấy một cảnh hoàng hôn tuyệt đẹp.'],
      ['close-up', '/ˈkləʊs ʌp/', 'cận cảnh', 'The close-up revealed the actor\'s emotions.', 'Cận cảnh đã lộ rõ cảm xúc của diễn viên.'],
      ['wide shot', '/waɪd ʃɒt/', 'toàn cảnh', 'The wide shot captured the whole city.', 'Toàn cảnh đã ghi lại cả thành phố.'],
      ['camera angle', '/ˈkæmərə ˈæŋɡl/', 'góc máy quay', 'The camera angle made the building look huge.', 'Góc máy quay khiến tòa nhà trông thật khổng lồ.'],
      ['special effects', '/ˈspeʃl ɪˈfekts/', 'hiệu ứng đặc biệt', 'The special effects made the dragon look real.', 'Hiệu ứng đặc biệt khiến con rồng trông như thật.'],
      ['cgi', '/ˌsiː dʒiː ˈaɪ/', 'kỹ xảo máy tính', 'CGI created the entire fantasy world.', 'CGI đã tạo ra toàn bộ thế giới giả tưởng.'],
      ['soundtrack', '/ˈsaʊndtræk/', 'nhạc phim', 'The soundtrack became popular worldwide.', 'Nhạc phim đã trở nên phổ biến trên toàn thế giới.'],
      ['dubbing', '/ˈdʌbɪŋ/', 'lồng tiếng', 'The film\'s dubbing was done in Vietnamese.', 'Phần lồng tiếng của bộ phim được làm bằng tiếng Việt.'],
      ['subtitle', '/ˈsʌbtaɪtl/', 'phụ đề', 'I watched the movie with English subtitles.', 'Tôi xem phim với phụ đề tiếng Anh.'],
      ['box office', '/bɒks ˈɒfɪs/', 'doanh thu phòng vé', 'The movie was a huge box office success.', 'Bộ phim đã thành công lớn về doanh thu phòng vé.'],
      ['premiere', '/prɪˈmɪər/', 'buổi công chiếu', 'Celebrities attended the film\'s premiere.', 'Các ngôi sao đã tham dự buổi công chiếu của bộ phim.'],
      ['blockbuster', '/ˈblɒkbʌstər/', 'bom tấn', 'The summer blockbuster broke box office records.', 'Bộ phim bom tấn mùa hè đã phá kỷ lục phòng vé.'],
      ['trailer', '/ˈtreɪlər/', 'đoạn giới thiệu phim', 'The trailer got millions of views online.', 'Đoạn trailer đã nhận được hàng triệu lượt xem trực tuyến.'],
      ['screening', '/ˈskriːnɪŋ/', 'buổi chiếu phim', 'There will be a special screening tonight.', 'Tối nay sẽ có một buổi chiếu đặc biệt.'],
      ['cinema', '/ˈsɪnəmə/', 'rạp chiếu phim', 'We went to the cinema last weekend.', 'Chúng tôi đã đến rạp chiếu phim vào cuối tuần trước.'],
      ['ticket', '/ˈtɪkɪt/', 'vé', 'I bought two tickets for the new film.', 'Tôi đã mua hai vé cho bộ phim mới.'],
      ['seat', '/siːt/', 'ghế ngồi', 'We chose seats in the middle row.', 'Chúng tôi chọn ghế ngồi ở hàng giữa.'],
      ['popcorn', '/ˈpɒpkɔːn/', 'bắp rang bơ', 'Popcorn is a classic movie snack.', 'Bắp rang bơ là món ăn vặt kinh điển khi xem phim.'],
      ['aisle', '/aɪl/', 'lối đi giữa các hàng ghế', 'He walked down the aisle to find his seat.', 'Anh ấy đi dọc lối đi để tìm ghế của mình.'],
      ['screen', '/skriːn/', 'màn hình chiếu', 'The film looked amazing on the big screen.', 'Bộ phim trông tuyệt vời trên màn hình lớn.'],
      ['projector', '/prəˈdʒektər/', 'máy chiếu', 'The projector displayed the movie clearly.', 'Máy chiếu đã chiếu bộ phim một cách rõ nét.'],
      ['matinee', '/ˈmætɪneɪ/', 'suất chiếu ban ngày', 'We watched a matinee to save money.', 'Chúng tôi xem suất chiếu ban ngày để tiết kiệm tiền.'],
      ['sequel', '/ˈsiːkwəl/', 'phần tiếp theo', 'The sequel was even better than the first film.', 'Phần tiếp theo còn hay hơn cả bộ phim đầu tiên.'],
      ['prequel', '/ˈpriːkwəl/', 'phần tiền truyện', 'The prequel explains the villain\'s backstory.', 'Phần tiền truyện giải thích câu chuyện quá khứ của kẻ phản diện.'],
      ['remake', '/ˈriːmeɪk/', 'phiên bản làm lại', 'The remake modernized the classic story.', 'Phiên bản làm lại đã hiện đại hóa câu chuyện kinh điển.'],
      ['spin-off', '/ˈspɪn ɒf/', 'phim ngoại truyện', 'The TV series is a spin-off of the movie.', 'Bộ phim truyền hình dài tập là một phần ngoại truyện của bộ phim.'],
      ['franchise', '/ˈfræntʃaɪz/', 'loạt phim / thương hiệu phim', 'The superhero franchise has ten movies.', 'Loạt phim siêu anh hùng này có mười bộ phim.'],
      ['film rating', '/fɪlm ˈreɪtɪŋ/', 'xếp hạng độ tuổi phim', 'The film rating warns about violent content.', 'Xếp hạng độ tuổi phim cảnh báo về nội dung bạo lực.'],
      ['release date', '/rɪˈliːs deɪt/', 'ngày phát hành', 'The release date was postponed to next year.', 'Ngày phát hành đã bị hoãn đến năm sau.'],
      ['plot', '/plɒt/', 'cốt truyện', 'The plot twist surprised every viewer.', 'Tình tiết bất ngờ trong cốt truyện khiến mọi khán giả bất ngờ.'],
      ['character', '/ˈkærəktər/', 'nhân vật', 'Each character has a unique personality.', 'Mỗi nhân vật đều có một tính cách riêng.'],
      ['protagonist', '/prəˈtæɡənɪst/', 'nhân vật chính', 'The protagonist must save the world.', 'Nhân vật chính phải cứu thế giới.'],
      ['antagonist', '/ænˈtæɡənɪst/', 'nhân vật phản diện', 'The antagonist plots against the hero.', 'Nhân vật phản diện âm mưu chống lại người hùng.'],
      ['villain', '/ˈvɪlən/', 'kẻ ác', 'The villain has a tragic backstory.', 'Kẻ ác có một quá khứ đầy bi kịch.'],
      ['hero', '/ˈhɪərəʊ/', 'người hùng', 'The hero rescues the city from destruction.', 'Người hùng giải cứu thành phố khỏi sự hủy diệt.'],
      ['climax', '/ˈklaɪmæks/', 'cao trào', 'The climax happens during the final battle.', 'Cao trào diễn ra trong trận chiến cuối cùng.'],
      ['twist', '/twɪst/', 'tình tiết bất ngờ', 'Nobody expected that twist ending.', 'Không ai ngờ được cái kết bất ngờ đó.'],
      ['ending', '/ˈendɪŋ/', 'đoạn kết', 'The movie has a happy ending.', 'Bộ phim có một cái kết hạnh phúc.'],
      ['flashback', '/ˈflæʃbæk/', 'cảnh hồi tưởng', 'The flashback reveals the character\'s childhood.', 'Cảnh hồi tưởng hé lộ tuổi thơ của nhân vật.'],
      ['narrator', '/nəˈreɪtər/', 'người kể chuyện', 'The narrator explains the story\'s background.', 'Người kể chuyện giải thích bối cảnh của câu chuyện.'],
      ['dialogue', '/ˈdaɪəlɒɡ/', 'lời thoại', 'The dialogue felt natural and realistic.', 'Lời thoại nghe rất tự nhiên và chân thực.'],
      ['setting', '/ˈsetɪŋ/', 'bối cảnh', 'The setting is a small town in the 1950s.', 'Bối cảnh là một thị trấn nhỏ vào những năm 1950.'],
      ['theme', '/θiːm/', 'chủ đề / thông điệp', 'The film\'s theme is about forgiveness.', 'Chủ đề của bộ phim nói về sự tha thứ.'],
      ['conflict', '/ˈkɒnflɪkt/', 'xung đột', 'The conflict between the two brothers drives the plot.', 'Xung đột giữa hai anh em thúc đẩy cốt truyện.'],
      ['cliffhanger', '/ˈklɪfhæŋər/', 'tình huống treo lửng', 'The episode ended with a shocking cliffhanger.', 'Tập phim kết thúc bằng một tình huống treo lửng gây sốc.'],
      ['subplot', '/ˈsʌbplɒt/', 'cốt truyện phụ', 'The subplot focuses on a secondary romance.', 'Cốt truyện phụ tập trung vào một mối tình lãng mạn thứ yếu.'],
      ['foreshadowing', '/fɔːˈʃædəʊɪŋ/', 'sự báo trước (tình tiết)', 'The foreshadowing hints at the character\'s death.', 'Sự báo trước tình tiết gợi ý về cái chết của nhân vật.'],
      ['genre', '/ˈʒɒnrə/', 'thể loại', 'Horror is my favorite genre.', 'Kinh dị là thể loại yêu thích của tôi.'],
      ['adaptation', '/ˌædæpˈteɪʃn/', 'bản chuyển thể', 'The film is an adaptation of a famous novel.', 'Bộ phim là bản chuyển thể từ một cuốn tiểu thuyết nổi tiếng.'],
      ['television series', '/ˈtelɪvɪʒn ˈsɪəriːz/', 'phim truyền hình dài tập', 'The television series has five seasons.', 'Bộ phim truyền hình dài tập có năm mùa.'],
      ['episode', '/ˈepɪsəʊd/', 'tập phim', 'I watched the latest episode last night.', 'Tôi đã xem tập mới nhất tối hôm qua.'],
      ['season', '/ˈsiːzn/', 'mùa (phim)', 'The show was renewed for another season.', 'Chương trình đã được gia hạn thêm một mùa nữa.'],
      ['streaming service', '/ˈstriːmɪŋ ˈsɜːvɪs/', 'dịch vụ xem trực tuyến', 'Netflix is a popular streaming service.', 'Netflix là một dịch vụ xem trực tuyến phổ biến.'],
      ['binge-watch', '/bɪndʒ wɒtʃ/', 'xem một mạch nhiều tập', 'We binge-watched the whole series in a weekend.', 'Chúng tôi đã xem một mạch cả bộ phim trong một cuối tuần.'],
      ['channel', '/ˈtʃænl/', 'kênh (truyền hình)', 'She changed the channel to watch the news.', 'Cô ấy đổi kênh để xem tin tức.'],
      ['broadcast', '/ˈbrɔːdkɑːst/', 'phát sóng', 'The event was broadcast live worldwide.', 'Sự kiện đã được phát sóng trực tiếp trên toàn thế giới.'],
      ['live show', '/laɪv ʃəʊ/', 'chương trình trực tiếp', 'The live show had millions of viewers.', 'Chương trình trực tiếp đã có hàng triệu người xem.'],
      ['reality show', '/riˈæləti ʃəʊ/', 'chương trình thực tế', 'The reality show follows contestants competing for a prize.', 'Chương trình thực tế theo chân các thí sinh thi đấu để giành giải thưởng.'],
      ['sitcom', '/ˈsɪtkɒm/', 'phim hài tình huống', 'The sitcom is known for its funny dialogue.', 'Phim hài tình huống nổi tiếng với những lời thoại vui nhộn.'],
      ['soap opera', '/səʊp ˈɒprə/', 'phim tình cảm nhiều tập', 'My grandmother loves watching soap operas.', 'Bà của tôi rất thích xem phim tình cảm nhiều tập.'],
      ['talk show', '/tɔːk ʃəʊ/', 'chương trình trò chuyện', 'The celebrity was interviewed on a talk show.', 'Người nổi tiếng đã được phỏng vấn trên một chương trình trò chuyện.'],
      ['game show', '/ɡeɪm ʃəʊ/', 'chương trình trò chơi truyền hình', 'Contestants win prizes on the game show.', 'Các thí sinh giành giải thưởng trên chương trình trò chơi truyền hình.'],
      ['rerun', '/ˈriːrʌn/', 'phát lại', 'I caught a rerun of my favorite episode.', 'Tôi đã bắt được một lần phát lại tập phim yêu thích của mình.'],
      ['pilot episode', '/ˈpaɪlət ˈepɪsəʊd/', 'tập thí điểm', 'The pilot episode introduces the main characters.', 'Tập thí điểm giới thiệu các nhân vật chính.'],
      ['cable tv', '/ˈkeɪbl tiː viː/', 'truyền hình cáp', 'We subscribed to cable TV for more channels.', 'Chúng tôi đã đăng ký truyền hình cáp để có thêm nhiều kênh.'],
      ['subscription', '/səbˈskrɪpʃn/', 'gói đăng ký (dịch vụ)', 'The subscription costs ten dollars a month.', 'Gói đăng ký có giá mười đô la một tháng.'],
      ['on-demand', '/ɒn dɪˈmɑːnd/', 'xem theo yêu cầu', 'You can watch movies on-demand anytime.', 'Bạn có thể xem phim theo yêu cầu bất cứ lúc nào.'],
      ['airing', '/ˈeərɪŋ/', 'việc phát sóng', 'The show is airing every Friday night.', 'Chương trình đang được phát sóng vào tối thứ Sáu hàng tuần.'],
      ['viewership', '/ˈvjuːərʃɪp/', 'số lượng người xem', 'The finale had record-breaking viewership.', 'Tập cuối đã đạt lượng người xem phá kỷ lục.'],
      ['award', '/əˈwɔːd/', 'giải thưởng', 'She received an award for best actress.', 'Cô ấy nhận được giải thưởng cho nữ diễn viên xuất sắc nhất.'],
      ['oscar', '/ˈɒskər/', 'giải Oscar', 'The film won three Oscars.', 'Bộ phim đã giành được ba giải Oscar.'],
      ['nomination', '/ˌnɒmɪˈneɪʃn/', 'đề cử', 'He received his first Oscar nomination this year.', 'Anh ấy nhận được đề cử Oscar đầu tiên trong năm nay.'],
      ['winner', '/ˈwɪnər/', 'người chiến thắng', 'The winner gave an emotional speech.', 'Người chiến thắng đã có một bài phát biểu đầy cảm xúc.'],
      ['red carpet', '/red ˈkɑːpɪt/', 'thảm đỏ', 'Stars walked the red carpet in elegant outfits.', 'Các ngôi sao đã bước trên thảm đỏ trong những bộ trang phục thanh lịch.'],
      ['critic', '/ˈkrɪtɪk/', 'nhà phê bình', 'The critic gave the film a glowing review.', 'Nhà phê bình đã dành cho bộ phim một bài đánh giá đầy lời khen.'],
      ['review', '/rɪˈvjuː/', 'bài đánh giá', 'The movie received mixed reviews.', 'Bộ phim nhận được những đánh giá trái chiều.'],
      ['star rating', '/stɑːr ˈreɪtɪŋ/', 'đánh giá theo số sao', 'The film got a five-star rating.', 'Bộ phim nhận được đánh giá năm sao.'],
      ['fan', '/fæn/', 'người hâm mộ', 'Fans lined up for hours to see the actor.', 'Người hâm mộ xếp hàng hàng giờ để gặp diễn viên.'],
      ['celebrity', '/səˈlebrəti/', 'người nổi tiếng', 'Many celebrities attended the gala.', 'Nhiều người nổi tiếng đã tham dự buổi dạ hội.'],
      ['movie star', '/ˈmuːvi stɑːr/', 'ngôi sao điện ảnh', 'She became a movie star overnight.', 'Cô ấy trở thành ngôi sao điện ảnh chỉ trong một đêm.'],
      ['icon', '/ˈaɪkɒn/', 'biểu tượng', 'He is considered a cinema icon.', 'Anh ấy được xem là một biểu tượng của điện ảnh.'],
      ['fame', '/feɪm/', 'sự nổi tiếng', 'The role brought her instant fame.', 'Vai diễn đã mang lại cho cô ấy sự nổi tiếng tức thì.'],
      ['paparazzi', '/ˌpæpəˈrætsi/', 'thợ săn ảnh người nổi tiếng', 'Paparazzi followed the celebrity everywhere.', 'Paparazzi theo dõi người nổi tiếng khắp mọi nơi.'],
      ['interview', '/ˈɪntəvjuː/', 'cuộc phỏng vấn', 'The actor gave an interview about his new film.', 'Diễn viên đã có một cuộc phỏng vấn về bộ phim mới của anh ấy.'],
      ['press conference', '/pres ˈkɒnfərəns/', 'họp báo', 'The director held a press conference before the release.', 'Đạo diễn đã tổ chức họp báo trước khi phát hành.'],
      ['film festival', '/fɪlm ˈfestɪvl/', 'liên hoan phim', 'The movie premiered at a film festival.', 'Bộ phim đã công chiếu tại một liên hoan phim.'],
      ['industry', '/ˈɪndəstri/', 'ngành công nghiệp (điện ảnh)', 'She has worked in the film industry for years.', 'Cô ấy đã làm việc trong ngành điện ảnh nhiều năm.'],
      ['hollywood', '/ˈhɒliwʊd/', 'kinh đô điện ảnh Hollywood', 'He dreams of working in Hollywood.', 'Anh ấy mơ ước được làm việc ở Hollywood.'],
      ['studio', '/ˈstjuːdiəʊ/', 'hãng phim / trường quay', 'The movie was made by a major studio.', 'Bộ phim được thực hiện bởi một hãng phim lớn.'],
      ['concert', '/ˈkɒnsət/', 'buổi hòa nhạc', 'We attended an amazing concert last night.', 'Chúng tôi đã tham dự một buổi hòa nhạc tuyệt vời tối hôm qua.'],
      ['musician', '/mjuˈzɪʃn/', 'nhạc sĩ / nhạc công', 'The musician played the guitar beautifully.', 'Nhạc sĩ đã chơi guitar rất hay.'],
      ['band', '/bænd/', 'ban nhạc', 'The band released a new album this year.', 'Ban nhạc đã phát hành một album mới trong năm nay.'],
      ['singer', '/ˈsɪŋər/', 'ca sĩ', 'The singer performed her hit song.', 'Ca sĩ đã trình bày bài hit của cô ấy.'],
      ['album', '/ˈælbəm/', 'album nhạc', 'Her new album topped the charts.', 'Album mới của cô ấy đã đứng đầu các bảng xếp hạng.'],
      ['song', '/sɒŋ/', 'bài hát', 'This song reminds me of my childhood.', 'Bài hát này gợi tôi nhớ đến tuổi thơ.'],
      ['lyrics', '/ˈlɪrɪks/', 'lời bài hát', 'The lyrics tell a touching love story.', 'Lời bài hát kể một câu chuyện tình cảm động.'],
      ['performance', '/pəˈfɔːməns/', 'buổi biểu diễn', 'The dancer gave an outstanding performance.', 'Vũ công đã có một buổi biểu diễn xuất sắc.'],
      ['stage', '/steɪdʒ/', 'sân khấu', 'The singer walked onto the stage.', 'Ca sĩ bước lên sân khấu.'],
      ['audience', '/ˈɔːdiəns/', 'khán giả', 'The audience cheered loudly.', 'Khán giả reo hò lớn tiếng.'],
      ['applause', '/əˈplɔːz/', 'tiếng vỗ tay', 'The performance ended with thunderous applause.', 'Buổi biểu diễn kết thúc bằng tiếng vỗ tay vang dội.'],
      ['encore', '/ˈɒŋkɔːr/', 'màn diễn thêm theo yêu cầu', 'The crowd demanded an encore.', 'Đám đông đòi một màn diễn thêm.'],
      ['tour', '/tʊər/', 'chuyến lưu diễn', 'The band is going on a world tour.', 'Ban nhạc sẽ đi lưu diễn khắp thế giới.'],
      ['music video', '/ˈmjuːzɪk ˈvɪdiəʊ/', 'video ca nhạc', 'The music video has millions of views.', 'Video ca nhạc đã có hàng triệu lượt xem.'],
      ['karaoke', '/ˌkæriˈəʊki/', 'hát karaoke', 'We sang karaoke all night at the party.', 'Chúng tôi hát karaoke cả đêm tại buổi tiệc.'],
      ['dj (disc jockey)', '/diː dʒeɪ/', 'người chơi nhạc DJ', 'The DJ mixed the music at the club.', 'DJ đã hòa nhạc tại câu lạc bộ.'],
      ['orchestra', '/ˈɔːkɪstrə/', 'dàn nhạc giao hưởng', 'The orchestra performed the film\'s score live.', 'Dàn nhạc giao hưởng đã biểu diễn nhạc phim trực tiếp.'],
      ['choir', '/ˈkwaɪər/', 'dàn hợp xướng', 'The choir sang beautifully at the event.', 'Dàn hợp xướng đã hát rất hay tại sự kiện.'],
      ['instrument', '/ˈɪnstrəmənt/', 'nhạc cụ', 'He plays several musical instruments.', 'Anh ấy chơi được nhiều loại nhạc cụ.'],
      ['gig', '/ɡɪɡ/', 'buổi diễn (thường quy mô nhỏ)', 'The band played a gig at a local bar.', 'Ban nhạc đã chơi một buổi diễn tại một quán bar địa phương.'],
      ['entertainment', '/ˌentəˈteɪnmənt/', 'sự giải trí', 'Movies are a popular form of entertainment.', 'Phim ảnh là một hình thức giải trí phổ biến.'],
      ['leisure', '/ˈleʒər/', 'thời gian rảnh rỗi', 'I spend my leisure time watching films.', 'Tôi dành thời gian rảnh để xem phim.'],
      ['amusement', '/əˈmjuːzmənt/', 'sự vui thích / giải trí', 'The clown provided amusement for the children.', 'Chú hề mang lại niềm vui cho trẻ em.'],
      ['fun', '/fʌn/', 'sự vui vẻ', 'We had so much fun at the movies.', 'Chúng tôi đã vui vẻ biết bao khi đi xem phim.'],
      ['hobby', '/ˈhɒbi/', 'sở thích', 'Watching films is her favorite hobby.', 'Xem phim là sở thích yêu thích của cô ấy.'],
      ['show', '/ʃəʊ/', 'chương trình / buổi diễn', 'The show starts at eight o\'clock.', 'Chương trình bắt đầu lúc tám giờ.'],
      ['program', '/ˈprəʊɡræm/', 'chương trình', 'The TV program airs every Sunday.', 'Chương trình truyền hình được phát sóng vào mỗi Chủ nhật.'],
      ['event', '/ɪˈvent/', 'sự kiện', 'The film festival is a major event in the city.', 'Liên hoan phim là một sự kiện lớn của thành phố.'],
      ['festival', '/ˈfestɪvl/', 'lễ hội', 'The music festival attracts thousands of fans.', 'Lễ hội âm nhạc thu hút hàng nghìn người hâm mộ.'],
      ['circus', '/ˈsɜːkəs/', 'rạp xiếc', 'The circus performers amazed the audience.', 'Các nghệ sĩ xiếc đã khiến khán giả kinh ngạc.'],
      ['theme park', '/θiːm pɑːk/', 'công viên giải trí', 'We spent the day at a theme park.', 'Chúng tôi đã dành cả ngày tại một công viên giải trí.'],
      ['comedy club', '/ˈkɒmədi klʌb/', 'câu lạc bộ hài kịch', 'He performs regularly at a comedy club.', 'Anh ấy thường xuyên biểu diễn tại một câu lạc bộ hài kịch.'],
      ['stand-up comedy', '/stænd ʌp ˈkɒmədi/', 'hài độc thoại', 'She loves watching stand-up comedy shows.', 'Cô ấy thích xem các chương trình hài độc thoại.'],
      ['magic show', '/ˈmædʒɪk ʃəʊ/', 'chương trình ảo thuật', 'The magic show left everyone amazed.', 'Chương trình ảo thuật khiến mọi người kinh ngạc.'],
      ['puppet show', '/ˈpʌpɪt ʃəʊ/', 'chương trình múa rối', 'Children enjoyed the puppet show.', 'Trẻ em thích thú với chương trình múa rối.'],
      ['video game', '/ˈvɪdiəʊ ɡeɪm/', 'trò chơi điện tử', 'He plays video games to relax.', 'Anh ấy chơi trò chơi điện tử để thư giãn.'],
      ['board game', '/bɔːd ɡeɪm/', 'trò chơi cờ bàn', 'We played a board game as a family.', 'Chúng tôi chơi một trò chơi cờ bàn cùng cả gia đình.'],
      ['party', '/ˈpɑːti/', 'bữa tiệc', 'They threw a party after the movie premiere.', 'Họ tổ chức một bữa tiệc sau buổi công chiếu phim.'],
      ['celebration', '/ˌselɪˈbreɪʃn/', 'lễ ăn mừng', 'The cast held a celebration for the film\'s success.', 'Dàn diễn viên tổ chức lễ ăn mừng cho thành công của bộ phim.'],
      ['fandom', '/ˈfændəm/', 'cộng đồng người hâm mộ', 'The movie has a huge fandom online.', 'Bộ phim có một cộng đồng người hâm mộ rất lớn trên mạng.'],
      ['enjoyable', '/ɪnˈdʒɔɪəbl/', 'thú vị, đáng tận hưởng', 'The film was an enjoyable experience.', 'Bộ phim là một trải nghiệm thú vị.'],
      ['boring', '/ˈbɔːrɪŋ/', 'nhàm chán', 'I found the second half quite boring.', 'Tôi thấy nửa sau khá nhàm chán.'],
      ['thrilling', '/ˈθrɪlɪŋ/', 'hồi hộp, kịch tính', 'The chase scene was absolutely thrilling.', 'Cảnh đuổi bắt thật sự hồi hộp đến mức tuyệt đối.'],
      ['hilarious', '/hɪˈleəriəs/', 'cực kỳ hài hước', 'The comedy was hilarious from start to finish.', 'Bộ phim hài cực kỳ vui từ đầu đến cuối.'],
      ['touching', '/ˈtʌtʃɪŋ/', 'cảm động', 'The ending was touching and emotional.', 'Cái kết vừa cảm động vừa đầy cảm xúc.'],
      ['suspenseful', '/səˈspensfl/', 'đầy hồi hộp, căng thẳng', 'The suspenseful plot kept us guessing.', 'Cốt truyện đầy hồi hộp khiến chúng tôi đoán mãi.'],
      ['overrated', '/ˌəʊvəˈreɪtɪd/', 'bị đánh giá quá cao', 'Many think the movie is overrated.', 'Nhiều người cho rằng bộ phim bị đánh giá quá cao.'],
      ['underrated', '/ˌʌndəˈreɪtɪd/', 'bị đánh giá thấp', 'This is an underrated film worth watching.', 'Đây là một bộ phim bị đánh giá thấp nhưng đáng xem.'],
      ['masterpiece', '/ˈmɑːstəpiːs/', 'kiệt tác', 'The director\'s latest film is a masterpiece.', 'Bộ phim mới nhất của đạo diễn là một kiệt tác.'],
      ['flop', '/flɒp/', 'thất bại (phòng vé)', 'The expensive movie turned out to be a flop.', 'Bộ phim đắt đỏ hóa ra lại là một thất bại phòng vé.'],
      ['hit', '/hɪt/', 'tác phẩm/bản hit thành công', 'The song became an instant hit.', 'Bài hát đã trở thành một hit ngay lập tức.'],
      ['iconic', '/aɪˈkɒnɪk/', 'mang tính biểu tượng', 'The scene is now an iconic movie moment.', 'Cảnh đó giờ đã trở thành một khoảnh khắc điện ảnh mang tính biểu tượng.'],
      ['classic', '/ˈklæsɪk/', 'kinh điển', 'This film is considered a classic.', 'Bộ phim này được xem là một tác phẩm kinh điển.'],
      ['cult classic', '/kʌlt ˈklæsɪk/', 'phim kinh điển được yêu thích bởi cộng đồng nhỏ', 'The movie became a cult classic over the years.', 'Qua nhiều năm, bộ phim đã trở thành một cult classic.'],
      ['must-watch', '/mʌst wɒtʃ/', 'phải xem', 'Critics called it a must-watch film of the year.', 'Các nhà phê bình gọi đây là bộ phim phải xem của năm.'],
      ['binge-worthy', '/bɪndʒ ˈwɜːði/', 'đáng để xem liền mạch nhiều tập', 'The series is truly binge-worthy.', 'Bộ phim dài tập thật sự đáng để xem một mạch.'],
      ['anticipated', '/ænˈtɪsɪpeɪtɪd/', 'được mong đợi', 'It\'s the most anticipated movie of the summer.', 'Đây là bộ phim được mong đợi nhất của mùa hè.'],
      ['highly-rated', '/ˈhaɪli ˈreɪtɪd/', 'được đánh giá cao', 'The show is highly-rated by critics.', 'Chương trình được các nhà phê bình đánh giá rất cao.'],
      ['box-office hit', '/bɒks ˈɒfɪs hɪt/', 'phim ăn khách phòng vé', 'The film became a box-office hit worldwide.', 'Bộ phim đã trở thành một hit phòng vé trên toàn thế giới.'],
      ['word of mouth', '/wɜːd əv maʊθ/', 'truyền miệng (đánh giá)', 'The movie gained popularity through word of mouth.', 'Bộ phim trở nên nổi tiếng nhờ truyền miệng.'],
  ],
};
