import { CefrLevel } from '@prisma/client';
import type { VocabularySeedSet } from './vocabulary-tech-sets';

export const ECONOMY_VOCABULARY_SET: VocabularySeedSet = {
  slug: 'kinh-te',
  title: 'Kinh tế',
  description:
    '220 từ vựng kinh tế thiết yếu: thị trường, lạm phát, tài chính, thương mại, đầu tư, chính sách và thuật ngữ kinh doanh',
  icon: 'trending-up',
  color: 'green',
  cefrLevel: CefrLevel.B1,
  topic: 'Kinh tế',
  isFeatured: true,
  sortOrder: 7,
  words: [
      ['economy', '/ɪˈkɒnəmi/', 'nền kinh tế', 'Vietnam has one of the fastest growing economies in Southeast Asia.', 'Vietnam có một trong những nền kinh tế tăng trưởng nhanh nhất ở Đông Nam Á.'],
      ['inflation', '/ɪnˈfleɪʃn/', 'lạm phát', 'High inflation reduces the purchasing power of consumers.', 'Lạm phát cao làm giảm sức mua của người tiêu dùng.'],
      ['recession', '/rɪˈseʃn/', 'suy thoái kinh tế', 'The country fell into a recession after two quarters of negative growth.', 'Đất nước rơi vào suy thoái sau hai quý tăng trưởng âm.'],
      ['depression', '/dɪˈpreʃn/', 'đại suy thoái', 'The Great Depression of the 1930s affected economies worldwide.', 'Đại suy thoái những năm 1930 ảnh hưởng đến các nền kinh tế trên toàn thế giới.'],
      ['recovery', '/rɪˈkʌvəri/', 'phục hồi kinh tế', 'The economy showed signs of recovery after the pandemic.', 'Nền kinh tế cho thấy dấu hiệu phục hồi sau đại dịch.'],
      ['boom', '/buːm/', 'sự bùng nổ kinh tế', 'The tech industry experienced a boom in the last decade.', 'Ngành công nghệ đã trải qua một giai đoạn bùng nổ trong thập kỷ vừa qua.'],
      ['gdp (gross domestic product)', '/ˌdʒiː diː ˈpiː/', 'tổng sản phẩm quốc nội', 'The GDP of the country grew by 6% last year.', 'GDP của đất nước đã tăng 6% năm ngoái.'],
      ['gnp (gross national product)', '/ˌdʒiː en ˈpiː/', 'tổng sản phẩm quốc dân', 'GNP includes income earned by citizens abroad.', 'GNP bao gồm thu nhập mà công dân kiếm được ở nước ngoài.'],
      ['supply', '/səˈplaɪ/', 'nguồn cung', 'The supply of oil dropped due to production cuts.', 'Nguồn cung dầu giảm do cắt giảm sản xuất.'],
      ['demand', '/dɪˈmɑːnd/', 'nhu cầu', 'Demand for electric cars has increased sharply in recent years.', 'Nhu cầu đối với xe điện đã tăng mạnh trong những năm gần đây.'],
      ['market', '/ˈmɑːkɪt/', 'thị trường', 'The stock market fell sharply after the announcement.', 'Thị trường chứng khoán giảm mạnh sau thông báo.'],
      ['investment', '/ɪnˈvestmənt/', 'đầu tư', 'Foreign investment is essential for economic development.', 'Đầu tư nước ngoài là yếu tố thiết yếu cho phát triển kinh tế.'],
      ['interest rate', '/ˈɪntrəst reɪt/', 'lãi suất', 'The central bank decided to raise the interest rate to control inflation.', 'Ngân hàng trung ương quyết định tăng lãi suất để kiểm soát lạm phát.'],
      ['currency', '/ˈkʌrənsi/', 'tiền tệ', 'The value of the local currency fell against the US dollar.', 'Giá trị đồng tiền địa phương giảm so với đô la Mỹ.'],
      ['trade deficit', '/treɪd ˈdefɪsɪt/', 'thâm hụt thương mại', 'The country is running a large trade deficit this year.', 'Đất nước đang có thâm hụt thương mại lớn trong năm nay.'],
      ['trade surplus', '/treɪd ˈsɜːplʌs/', 'thặng dư thương mại', 'China has recorded a trade surplus for many consecutive years.', 'China đã ghi nhận thặng dư thương mại trong nhiều năm liên tiếp.'],
      ['export', '/ˈekspɔːt/', 'xuất khẩu', 'Rice is one of Vietnam\'s major exports.', 'Gạo là một trong những mặt hàng xuất khẩu chính của Vietnam.'],
      ['import', '/ˈɪmpɔːt/', 'nhập khẩu', 'The company imports raw materials from China.', 'Công ty nhập khẩu nguyên liệu thô từ China.'],
      ['revenue', '/ˈrevənjuː/', 'doanh thu', 'The company\'s revenue increased by 20% this quarter.', 'Doanh thu của công ty tăng 20% trong quý này.'],
      ['profit', '/ˈprɒfɪt/', 'lợi nhuận', 'The business made a large profit last year.', 'Doanh nghiệp đã thu được lợi nhuận lớn năm ngoái.'],
      ['loss', '/lɒs/', 'thua lỗ', 'The firm reported a huge loss due to falling sales.', 'Công ty báo cáo khoản lỗ lớn do doanh số giảm.'],
      ['unemployment', '/ˌʌnɪmˈplɔɪmənt/', 'thất nghiệp', 'Unemployment rates rose sharply during the crisis.', 'Tỷ lệ thất nghiệp tăng mạnh trong thời kỳ khủng hoảng.'],
      ['employment', '/ɪmˈplɔɪmənt/', 'việc làm', 'The government aims to boost employment in rural areas.', 'Chính phủ nhằm mục tiêu thúc đẩy việc làm ở các vùng nông thôn.'],
      ['budget', '/ˈbʌdʒɪt/', 'ngân sách', 'The government announced a new budget for education.', 'Chính phủ công bố ngân sách mới cho giáo dục.'],
      ['tax', '/tæks/', 'thuế', 'The government plans to raise taxes on luxury goods.', 'Chính phủ có kế hoạch tăng thuế đối với hàng hóa xa xỉ.'],
      ['taxation', '/tækˈseɪʃn/', 'sự đánh thuế', 'High taxation can discourage business investment.', 'Mức thuế cao có thể làm nản lòng việc đầu tư kinh doanh.'],
      ['consumer', '/kənˈsjuːmə(r)/', 'người tiêu dùng', 'Consumers are spending less due to rising prices.', 'Người tiêu dùng chi tiêu ít hơn do giá cả tăng.'],
      ['producer', '/prəˈdjuːsə(r)/', 'nhà sản xuất', 'Producers must adjust output to meet market demand.', 'Các nhà sản xuất phải điều chỉnh sản lượng để đáp ứng nhu cầu thị trường.'],
      ['stock', '/stɒk/', 'cổ phiếu', 'He bought stocks in a technology company last month.', 'Anh ấy đã mua cổ phiếu của một công ty công nghệ tháng trước.'],
      ['bond', '/bɒnd/', 'trái phiếu', 'The government issued bonds to raise funds for infrastructure.', 'Chính phủ phát hành trái phiếu để huy động vốn cho cơ sở hạ tầng.'],
      ['bankruptcy', '/ˈbæŋkrʌptsi/', 'phá sản', 'The company filed for bankruptcy after years of losses.', 'Công ty nộp đơn phá sản sau nhiều năm thua lỗ.'],
      ['monopoly', '/məˈnɒpəli/', 'độc quyền', 'The corporation holds a monopoly over the local energy market.', 'Tập đoàn này nắm độc quyền trên thị trường năng lượng địa phương.'],
      ['oligopoly', '/ˌɒlɪˈɡɒpəli/', 'độc quyền nhóm', 'The airline industry is often described as an oligopoly.', 'Ngành hàng không thường được mô tả là một thị trường độc quyền nhóm.'],
      ['subsidy', '/ˈsʌbsədi/', 'trợ cấp', 'The government provides subsidies to support local farmers.', 'Chính phủ cung cấp trợ cấp để hỗ trợ nông dân địa phương.'],
      ['tariff', '/ˈtærɪf/', 'thuế quan', 'The new tariff on imported steel raised production costs.', 'Thuế quan mới đối với thép nhập khẩu đã làm tăng chi phí sản xuất.'],
      ['quota', '/ˈkwəʊtə/', 'hạn ngạch', 'The government set an import quota to protect local industry.', 'Chính phủ đặt hạn ngạch nhập khẩu để bảo vệ ngành công nghiệp trong nước.'],
      ['free trade', '/friː treɪd/', 'thương mại tự do', 'Free trade agreements have boosted exports between the two countries.', 'Các hiệp định thương mại tự do đã thúc đẩy xuất khẩu giữa hai nước.'],
      ['protectionism', '/prəˈtekʃənɪzəm/', 'chủ nghĩa bảo hộ', 'Protectionism can lead to trade wars between nations.', 'Chủ nghĩa bảo hộ có thể dẫn đến chiến tranh thương mại giữa các quốc gia.'],
      ['globalization', '/ˌɡləʊbəlaɪˈzeɪʃn/', 'toàn cầu hóa', 'Globalization has connected markets across the world.', 'Toàn cầu hóa đã kết nối các thị trường trên khắp thế giới.'],
      ['privatization', '/ˌpraɪvətaɪˈzeɪʃn/', 'tư nhân hóa', 'The privatization of state-owned enterprises attracted foreign investors.', 'Việc tư nhân hóa các doanh nghiệp nhà nước đã thu hút nhà đầu tư nước ngoài.'],
      ['nationalization', '/ˌnæʃnəlaɪˈzeɪʃn/', 'quốc hữu hóa', 'The government carried out the nationalization of the oil industry.', 'Chính phủ thực hiện quốc hữu hóa ngành dầu khí.'],
      ['deregulation', '/ˌdiːreɡjʊˈleɪʃn/', 'bãi bỏ quy định', 'Deregulation of the banking sector increased competition.', 'Việc bãi bỏ quy định trong lĩnh vực ngân hàng đã làm tăng cạnh tranh.'],
      ['regulation', '/ˌreɡjʊˈleɪʃn/', 'quy định, sự điều tiết', 'Strict regulation is needed to prevent financial fraud.', 'Cần có quy định chặt chẽ để ngăn chặn gian lận tài chính.'],
      ['fiscal policy', '/ˈfɪskl ˈpɒləsi/', 'chính sách tài khóa', 'The government used fiscal policy to stimulate the economy.', 'Chính phủ sử dụng chính sách tài khóa để kích thích nền kinh tế.'],
      ['monetary policy', '/ˈmʌnɪtri ˈpɒləsi/', 'chính sách tiền tệ', 'The central bank tightened monetary policy to fight inflation.', 'Ngân hàng trung ương thắt chặt chính sách tiền tệ để chống lạm phát.'],
      ['central bank', '/ˈsentrəl bæŋk/', 'ngân hàng trung ương', 'The central bank controls the money supply of the country.', 'Ngân hàng trung ương kiểm soát cung tiền của đất nước.'],
      ['commercial bank', '/kəˈmɜːʃl bæŋk/', 'ngân hàng thương mại', 'Commercial banks provide loans to individuals and businesses.', 'Các ngân hàng thương mại cung cấp khoản vay cho cá nhân và doanh nghiệp.'],
      ['interest', '/ˈɪntrəst/', 'lãi suất, tiền lãi', 'The bank charges 5% interest on personal loans.', 'Ngân hàng tính lãi suất 5% đối với các khoản vay cá nhân.'],
      ['loan', '/ləʊn/', 'khoản vay', 'She took out a loan to start her own business.', 'Cô ấy đã vay một khoản để khởi nghiệp kinh doanh riêng.'],
      ['debt', '/det/', 'nợ', 'The country\'s national debt has grown significantly.', 'Nợ quốc gia của đất nước đã tăng đáng kể.'],
      ['credit', '/ˈkredɪt/', 'tín dụng', 'Many consumers rely on credit cards for daily purchases.', 'Nhiều người tiêu dùng dựa vào thẻ tín dụng cho các khoản mua sắm hàng ngày.'],
      ['deficit', '/ˈdefɪsɪt/', 'thâm hụt', 'The government is trying to reduce the budget deficit.', 'Chính phủ đang cố gắng giảm thâm hụt ngân sách.'],
      ['surplus', '/ˈsɜːplʌs/', 'thặng dư', 'The country recorded a budget surplus this year.', 'Đất nước ghi nhận thặng dư ngân sách trong năm nay.'],
      ['asset', '/ˈæset/', 'tài sản', 'Real estate is considered a valuable asset.', 'Bất động sản được coi là một tài sản có giá trị.'],
      ['liability', '/ˌlaɪəˈbɪləti/', 'nợ phải trả', 'The company\'s liabilities exceeded its assets last year.', 'Nợ phải trả của công ty đã vượt quá tài sản năm ngoái.'],
      ['equity', '/ˈekwəti/', 'vốn chủ sở hữu', 'Shareholders\' equity increased after the profitable year.', 'Vốn chủ sở hữu của cổ đông tăng sau một năm có lợi nhuận.'],
      ['capital', '/ˈkæpɪtl/', 'vốn', 'The startup needs more capital to expand its operations.', 'Công ty khởi nghiệp cần thêm vốn để mở rộng hoạt động.'],
      ['capitalism', '/ˈkæpɪtəlɪzəm/', 'chủ nghĩa tư bản', 'Capitalism is based on private ownership and free markets.', 'Chủ nghĩa tư bản dựa trên sở hữu tư nhân và thị trường tự do.'],
      ['socialism', '/ˈsəʊʃəlɪzəm/', 'chủ nghĩa xã hội', 'Socialism emphasizes collective ownership of resources.', 'Chủ nghĩa xã hội nhấn mạnh sở hữu tập thể đối với các nguồn lực.'],
      ['communism', '/ˈkɒmjʊnɪzəm/', 'chủ nghĩa cộng sản', 'Communism advocates for a classless, stateless society.', 'Chủ nghĩa cộng sản chủ trương một xã hội không giai cấp, không nhà nước.'],
      ['mixed economy', '/mɪkst ɪˈkɒnəmi/', 'nền kinh tế hỗn hợp', 'Many countries today operate a mixed economy combining public and private sectors.', 'Nhiều quốc gia ngày nay vận hành nền kinh tế hỗn hợp kết hợp khu vực công và tư.'],
      ['market economy', '/ˈmɑːkɪt ɪˈkɒnəmi/', 'nền kinh tế thị trường', 'In a market economy, prices are determined by supply and demand.', 'Trong nền kinh tế thị trường, giá cả được quyết định bởi cung và cầu.'],
      ['command economy', '/kəˈmɑːnd ɪˈkɒnəmi/', 'nền kinh tế kế hoạch hóa', 'In a command economy, the government controls production and pricing.', 'Trong nền kinh tế kế hoạch hóa, chính phủ kiểm soát sản xuất và định giá.'],
      ['labor force', '/ˈleɪbə fɔːs/', 'lực lượng lao động', 'The labor force includes all people who are employed or seeking work.', 'Lực lượng lao động bao gồm tất cả những người đang làm việc hoặc đang tìm việc.'],
      ['wage', '/weɪdʒ/', 'tiền công', 'Factory workers received a wage increase this year.', 'Công nhân nhà máy được tăng tiền công trong năm nay.'],
      ['salary', '/ˈsæləri/', 'tiền lương', 'Her monthly salary was raised after the promotion.', 'Tiền lương hàng tháng của cô ấy được tăng sau khi thăng chức.'],
      ['minimum wage', '/ˈmɪnɪməm weɪdʒ/', 'lương tối thiểu', 'The government raised the minimum wage to help low-income workers.', 'Chính phủ tăng lương tối thiểu để hỗ trợ người lao động thu nhập thấp.'],
      ['income', '/ˈɪŋkʌm/', 'thu nhập', 'His income has increased since he changed jobs.', 'Thu nhập của anh ấy đã tăng kể từ khi đổi việc.'],
      ['purchasing power', '/ˈpɜːtʃəsɪŋ ˈpaʊə/', 'sức mua', 'Inflation has eroded the purchasing power of many households.', 'Lạm phát đã làm xói mòn sức mua của nhiều hộ gia đình.'],
      ['cost of living', '/kɒst əv ˈlɪvɪŋ/', 'chi phí sinh hoạt', 'The cost of living in big cities keeps rising every year.', 'Chi phí sinh hoạt ở các thành phố lớn cứ tăng mỗi năm.'],
      ['standard of living', '/ˈstændəd əv ˈlɪvɪŋ/', 'mức sống', 'Economic growth has improved the standard of living for many people.', 'Tăng trưởng kinh tế đã cải thiện mức sống của nhiều người.'],
      ['poverty', '/ˈpɒvəti/', 'nghèo đói', 'The government launched a program to reduce poverty in rural areas.', 'Chính phủ triển khai chương trình nhằm giảm nghèo ở các vùng nông thôn.'],
      ['wealth', '/welθ/', 'của cải, sự giàu có', 'The wealth gap between rich and poor continues to widen.', 'Khoảng cách giàu nghèo giữa người giàu và người nghèo tiếp tục mở rộng.'],
      ['distribution of wealth', '/ˌdɪstrɪˈbjuːʃn əv welθ/', 'sự phân phối của cải', 'Unequal distribution of wealth can cause social tension.', 'Sự phân phối của cải không đồng đều có thể gây ra căng thẳng xã hội.'],
      ['income inequality', '/ˈɪŋkʌm ˌɪnɪˈkwɒləti/', 'bất bình đẳng thu nhập', 'Income inequality has become a major political issue.', 'Bất bình đẳng thu nhập đã trở thành một vấn đề chính trị lớn.'],
      ['gross income', '/ɡrəʊs ˈɪŋkʌm/', 'tổng thu nhập', 'Her gross income before tax was quite high.', 'Tổng thu nhập trước thuế của cô ấy khá cao.'],
      ['net income', '/net ˈɪŋkʌm/', 'thu nhập ròng', 'The company\'s net income increased after cutting costs.', 'Thu nhập ròng của công ty tăng sau khi cắt giảm chi phí.'],
      ['disposable income', '/dɪˈspəʊzəbl ˈɪŋkʌm/', 'thu nhập khả dụng', 'Higher disposable income leads to greater consumer spending.', 'Thu nhập khả dụng cao hơn dẫn đến chi tiêu tiêu dùng lớn hơn.'],
      ['savings', '/ˈseɪvɪŋz/', 'tiền tiết kiệm', 'She keeps her savings in a fixed deposit account.', 'Cô ấy gửi tiền tiết kiệm vào tài khoản tiền gửi có kỳ hạn.'],
      ['consumption', '/kənˈsʌmpʃn/', 'tiêu dùng', 'Household consumption drives a large part of the economy.', 'Tiêu dùng của hộ gia đình thúc đẩy một phần lớn nền kinh tế.'],
      ['spending', '/ˈspendɪŋ/', 'chi tiêu', 'Government spending on healthcare increased this year.', 'Chi tiêu của chính phủ cho y tế đã tăng trong năm nay.'],
      ['expenditure', '/ɪkˈspendɪtʃə(r)/', 'chi phí, chi tiêu', 'Total expenditure exceeded the budgeted amount.', 'Tổng chi tiêu đã vượt quá số tiền được lập ngân sách.'],
      ['household', '/ˈhaʊshəʊld/', 'hộ gia đình', 'Many households struggle to make ends meet during inflation.', 'Nhiều hộ gia đình phải xoay xở để trang trải cuộc sống trong thời kỳ lạm phát.'],
      ['firm', '/fɜːm/', 'doanh nghiệp, hãng', 'The firm reported strong earnings this quarter.', 'Công ty báo cáo thu nhập mạnh trong quý này.'],
      ['industry', '/ˈɪndəstri/', 'ngành công nghiệp', 'The tourism industry suffered greatly during the pandemic.', 'Ngành du lịch chịu thiệt hại lớn trong đại dịch.'],
      ['sector', '/ˈsektə(r)/', 'khu vực (kinh tế)', 'The service sector now dominates the national economy.', 'Khu vực dịch vụ hiện chiếm ưu thế trong nền kinh tế quốc dân.'],
      ['manufacturing', '/ˌmænjuˈfæktʃərɪŋ/', 'sản xuất, chế tạo', 'Manufacturing accounts for a large share of exports.', 'Sản xuất chế tạo chiếm tỷ trọng lớn trong xuất khẩu.'],
      ['agriculture', '/ˈæɡrɪkʌltʃə(r)/', 'nông nghiệp', 'Agriculture remains vital to the rural economy.', 'Nông nghiệp vẫn đóng vai trò quan trọng đối với kinh tế nông thôn.'],
      ['service sector', '/ˈsɜːvɪs ˈsektə(r)/', 'khu vực dịch vụ', 'The service sector employs the majority of the workforce.', 'Khu vực dịch vụ thuê phần lớn lực lượng lao động.'],
      ['production', '/prəˈdʌkʃn/', 'sản xuất', 'Production costs rose due to higher fuel prices.', 'Chi phí sản xuất tăng do giá nhiên liệu cao hơn.'],
      ['productivity', '/ˌprɒdʌkˈtɪvəti/', 'năng suất', 'New technology has boosted worker productivity.', 'Công nghệ mới đã nâng cao năng suất của người lao động.'],
      ['output', '/ˈaʊtpʊt/', 'sản lượng', 'Industrial output grew steadily throughout the year.', 'Sản lượng công nghiệp tăng đều đặn trong suốt năm.'],
      ['input', '/ˈɪnpʊt/', 'đầu vào', 'Rising input costs squeezed the company\'s profit margin.', 'Chi phí đầu vào tăng đã làm thu hẹp biên lợi nhuận của công ty.'],
      ['resources', '/rɪˈsɔːsɪz/', 'tài nguyên', 'Natural resources are essential for economic development.', 'Tài nguyên thiên nhiên là yếu tố thiết yếu cho phát triển kinh tế.'],
      ['scarcity', '/ˈskeəsəti/', 'sự khan hiếm', 'Scarcity forces societies to make choices about resource allocation.', 'Sự khan hiếm buộc xã hội phải đưa ra lựa chọn về phân bổ nguồn lực.'],
      ['opportunity cost', '/ˌɒpəˈtjuːnəti kɒst/', 'chi phí cơ hội', 'The opportunity cost of studying is the income you give up.', 'Chi phí cơ hội của việc học là thu nhập mà bạn phải từ bỏ.'],
      ['trade-off', '/ˈtreɪd ɒf/', 'sự đánh đổi', 'There is always a trade-off between saving and spending.', 'Luôn có sự đánh đổi giữa tiết kiệm và chi tiêu.'],
      ['efficiency', '/ɪˈfɪʃnsi/', 'hiệu quả', 'Automation improved efficiency in the production line.', 'Tự động hóa đã cải thiện hiệu quả trên dây chuyền sản xuất.'],
      ['economic growth', '/ˌiːkəˈnɒmɪk ɡrəʊθ/', 'tăng trưởng kinh tế', 'Economic growth slowed due to weaker global demand.', 'Tăng trưởng kinh tế chậm lại do nhu cầu toàn cầu yếu hơn.'],
      ['sustainable development', '/səˈsteɪnəbl dɪˈveləpmənt/', 'phát triển bền vững', 'Sustainable development balances economic growth with environmental protection.', 'Phát triển bền vững cân bằng giữa tăng trưởng kinh tế và bảo vệ môi trường.'],
      ['developing country', '/dɪˈveləpɪŋ ˈkʌntri/', 'nước đang phát triển', 'Vietnam is considered a fast-growing developing country.', 'Vietnam được coi là một nước đang phát triển tăng trưởng nhanh.'],
      ['developed country', '/dɪˈveləpt ˈkʌntri/', 'nước phát triển', 'Developed countries generally have high GDP per capita.', 'Các nước phát triển nhìn chung có GDP bình quân đầu người cao.'],
      ['emerging market', '/ɪˈmɜːdʒɪŋ ˈmɑːkɪt/', 'thị trường mới nổi', 'Investors are attracted to emerging markets for their growth potential.', 'Nhà đầu tư bị thu hút bởi các thị trường mới nổi vì tiềm năng tăng trưởng của chúng.'],
      ['foreign direct investment (fdi)', '/ˈfɒrən dəˈrekt ɪnˈvestmənt/', 'đầu tư trực tiếp nước ngoài', 'Foreign direct investment has fueled Vietnam\'s industrial growth.', 'Đầu tư trực tiếp nước ngoài đã thúc đẩy tăng trưởng công nghiệp của Vietnam.'],
      ['portfolio investment', '/pɔːtˈfəʊliəʊ ɪnˈvestmənt/', 'đầu tư danh mục', 'Portfolio investment involves buying stocks and bonds in foreign markets.', 'Đầu tư danh mục liên quan đến việc mua cổ phiếu và trái phiếu trên các thị trường nước ngoài.'],
      ['stock market', '/stɒk ˈmɑːkɪt/', 'thị trường chứng khoán', 'The stock market rallied after positive economic data.', 'Thị trường chứng khoán tăng mạnh sau dữ liệu kinh tế tích cực.'],
      ['stock exchange', '/stɒk ɪksˈtʃeɪndʒ/', 'sàn giao dịch chứng khoán', 'The company was listed on the New York Stock Exchange.', 'Công ty được niêm yết trên New York Stock Exchange.'],
      ['share', '/ʃeə(r)/', 'cổ phần', 'He owns shares in several technology companies.', 'Anh ấy sở hữu cổ phần tại một số công ty công nghệ.'],
      ['shareholder', '/ˈʃeəhəʊldə(r)/', 'cổ đông', 'Shareholders voted to approve the merger.', 'Các cổ đông đã bỏ phiếu phê duyệt vụ sáp nhập.'],
      ['dividend', '/ˈdɪvɪdend/', 'cổ tức', 'The company paid a generous dividend to its shareholders.', 'Công ty trả cổ tức hậu hĩnh cho các cổ đông.'],
      ['broker', '/ˈbrəʊkə(r)/', 'nhà môi giới', 'She works as a stockbroker on Wall Street.', 'Cô ấy làm việc như một nhà môi giới chứng khoán trên Wall Street.'],
      ['trader', '/ˈtreɪdə(r)/', 'nhà giao dịch', 'The trader made a huge profit from currency speculation.', 'Nhà giao dịch đã kiếm được lợi nhuận lớn từ đầu cơ tiền tệ.'],
      ['speculation', '/ˌspekjuˈleɪʃn/', 'đầu cơ', 'Speculation in the housing market drove prices to unsustainable levels.', 'Đầu cơ trên thị trường nhà ở đã đẩy giá lên mức không bền vững.'],
      ['hedge fund', '/hedʒ fʌnd/', 'quỹ đầu cơ', 'The hedge fund invests in high-risk, high-return assets.', 'Quỹ đầu cơ đầu tư vào các tài sản rủi ro cao, lợi nhuận cao.'],
      ['mutual fund', '/ˈmjuːtʃuəl fʌnd/', 'quỹ tương hỗ', 'She invests her savings in a mutual fund.', 'Cô ấy đầu tư tiền tiết kiệm vào một quỹ tương hỗ.'],
      ['venture capital', '/ˈventʃə(r) ˈkæpɪtl/', 'vốn đầu tư mạo hiểm', 'The startup raised venture capital to develop its product.', 'Công ty khởi nghiệp đã huy động được vốn đầu tư mạo hiểm để phát triển sản phẩm.'],
      ['startup', '/ˈstɑːrtʌp/', 'công ty khởi nghiệp', 'The startup attracted millions in funding within its first year.', 'Công ty khởi nghiệp đã thu hút hàng triệu đô la vốn trong năm đầu tiên.'],
      ['entrepreneur', '/ˌɒntrəprəˈnɜː(r)/', 'doanh nhân khởi nghiệp', 'The young entrepreneur built a successful e-commerce business.', 'Doanh nhân trẻ đã xây dựng một doanh nghiệp thương mại điện tử thành công.'],
      ['entrepreneurship', '/ˌɒntrəprəˈnɜːʃɪp/', 'tinh thần khởi nghiệp', 'The university encourages entrepreneurship among students.', 'Trường đại học khuyến khích tinh thần khởi nghiệp trong sinh viên.'],
      ['corporation', '/ˌkɔːpəˈreɪʃn/', 'tập đoàn, công ty', 'The corporation reported record profits this year.', 'Tập đoàn báo cáo lợi nhuận kỷ lục trong năm nay.'],
      ['multinational corporation', '/ˌmʌltiˈnæʃnəl ˌkɔːpəˈreɪʃn/', 'tập đoàn đa quốc gia', 'The multinational corporation operates in over fifty countries.', 'Tập đoàn đa quốc gia hoạt động tại hơn năm mươi quốc gia.'],
      ['merger', '/ˈmɜːdʒə(r)/', 'sự sáp nhập', 'The merger created one of the largest companies in the industry.', 'Vụ sáp nhập đã tạo ra một trong những công ty lớn nhất trong ngành.'],
      ['acquisition', '/ˌækwɪˈzɪʃn/', 'sự mua lại, thâu tóm', 'The acquisition of the smaller firm strengthened its market position.', 'Việc mua lại công ty nhỏ hơn đã củng cố vị thế thị trường của nó.'],
      ['takeover', '/ˈteɪkəʊvə(r)/', 'sự thâu tóm', 'Shareholders approved the hostile takeover bid.', 'Các cổ đông đã phê duyệt đề nghị thâu tóm thù địch.'],
      ['competition', '/ˌkɒmpəˈtɪʃn/', 'sự cạnh tranh', 'Strong competition forced companies to lower their prices.', 'Cạnh tranh mạnh đã buộc các công ty phải giảm giá.'],
      ['competitive advantage', '/kəmˈpetətɪv ədˈvɑːntɪdʒ/', 'lợi thế cạnh tranh', 'Lower production costs gave the firm a competitive advantage.', 'Chi phí sản xuất thấp hơn đã mang lại lợi thế cạnh tranh cho công ty.'],
      ['market share', '/ˈmɑːkɪt ʃeə(r)/', 'thị phần', 'The company increased its market share through aggressive marketing.', 'Công ty tăng thị phần nhờ tiếp thị quyết liệt.'],
      ['brand', '/brænd/', 'thương hiệu', 'Building a strong brand helps attract loyal customers.', 'Xây dựng thương hiệu mạnh giúp thu hút khách hàng trung thành.'],
      ['consumer behavior', '/kənˈsjuːmə bɪˈheɪvjə(r)/', 'hành vi người tiêu dùng', 'Understanding consumer behavior helps companies design better products.', 'Hiểu hành vi người tiêu dùng giúp các công ty thiết kế sản phẩm tốt hơn.'],
      ['marketing', '/ˈmɑːkɪtɪŋ/', 'tiếp thị, marketing', 'The company spent heavily on marketing to launch its new product.', 'Công ty chi mạnh cho marketing để ra mắt sản phẩm mới.'],
      ['advertising', '/ˈædvətaɪzɪŋ/', 'quảng cáo', 'Advertising plays a key role in shaping consumer choices.', 'Quảng cáo đóng vai trò then chốt trong việc định hình lựa chọn của người tiêu dùng.'],
      ['supply chain', '/səˈplaɪ tʃeɪn/', 'chuỗi cung ứng', 'The pandemic disrupted global supply chains.', 'Đại dịch đã làm gián đoạn các chuỗi cung ứng toàn cầu.'],
      ['logistics', '/ləˈdʒɪstɪks/', 'hậu cần, logistics', 'Efficient logistics reduce delivery time and costs.', 'Logistics hiệu quả giúp giảm thời gian và chi phí giao hàng.'],
      ['distribution', '/ˌdɪstrɪˈbjuːʃn/', 'phân phối', 'The company improved its distribution network across the country.', 'Công ty đã cải thiện mạng lưới phân phối trên cả nước.'],
      ['retail', '/ˈriːteɪl/', 'bán lẻ', 'Retail sales increased during the holiday season.', 'Doanh số bán lẻ tăng trong mùa nghỉ lễ.'],
      ['wholesale', '/ˈhəʊlseɪl/', 'bán buôn', 'He buys goods at wholesale prices and resells them.', 'Anh ấy mua hàng với giá bán buôn rồi bán lại.'],
      ['e-commerce', '/ˈiː ˌkɒmɜːs/', 'thương mại điện tử', 'E-commerce has grown rapidly since the pandemic.', 'Thương mại điện tử đã tăng trưởng nhanh chóng kể từ đại dịch.'],
      ['digital economy', '/ˈdɪdʒɪtl ɪˈkɒnəmi/', 'kinh tế số', 'The digital economy is reshaping traditional business models.', 'Kinh tế số đang định hình lại các mô hình kinh doanh truyền thống.'],
      ['cryptocurrency', '/ˈkrɪptəʊˌkʌrənsi/', 'tiền điện tử', 'Cryptocurrency prices are known for their high volatility.', 'Giá tiền điện tử nổi tiếng vì độ biến động cao.'],
      ['blockchain', '/ˈblɒktʃeɪn/', 'công nghệ chuỗi khối', 'Blockchain technology enables secure and transparent transactions.', 'Công nghệ blockchain cho phép các giao dịch an toàn và minh bạch.'],
      ['fintech', '/ˈfɪntek/', 'công nghệ tài chính', 'Fintech companies are transforming how people manage money.', 'Các công ty fintech đang thay đổi cách mọi người quản lý tiền bạc.'],
      ['insurance', '/ɪnˈʃʊərəns/', 'bảo hiểm', 'Health insurance covers most medical expenses.', 'Bảo hiểm y tế chi trả hầu hết các chi phí y tế.'],
      ['premium', '/ˈpriːmiəm/', 'phí bảo hiểm', 'Her monthly insurance premium increased this year.', 'Phí bảo hiểm hàng tháng của cô ấy đã tăng trong năm nay.'],
      ['claim', '/kleɪm/', 'yêu cầu bồi thường', 'He filed a claim after the car accident.', 'Anh ấy nộp yêu cầu bồi thường sau vụ tai nạn xe hơi.'],
      ['risk management', '/rɪsk ˈmænɪdʒmənt/', 'quản lý rủi ro', 'Effective risk management helps companies avoid major losses.', 'Quản lý rủi ro hiệu quả giúp các công ty tránh được những khoản lỗ lớn.'],
      ['diversification', '/daɪˌvɜːsɪfɪˈkeɪʃn/', 'đa dạng hóa', 'Diversification of investments reduces overall risk.', 'Đa dạng hóa đầu tư làm giảm rủi ro tổng thể.'],
      ['portfolio', '/pɔːtˈfəʊliəʊ/', 'danh mục đầu tư', 'Her investment portfolio includes stocks, bonds, and real estate.', 'Danh mục đầu tư của cô ấy bao gồm cổ phiếu, trái phiếu và bất động sản.'],
      ['interest expense', '/ˈɪntrəst ɪkˈspens/', 'chi phí lãi vay', 'High interest expense reduced the company\'s net profit.', 'Chi phí lãi vay cao đã làm giảm lợi nhuận ròng của công ty.'],
      ['amortization', '/əˌmɔːtaɪˈzeɪʃn/', 'sự khấu hao (nợ)', 'The loan amortization schedule spans over ten years.', 'Lịch khấu hao khoản vay kéo dài hơn mười năm.'],
      ['depreciation', '/dɪˌpriːʃiˈeɪʃn/', 'khấu hao (tài sản)', 'Depreciation of equipment is recorded annually on the balance sheet.', 'Khấu hao thiết bị được ghi nhận hàng năm trên bảng cân đối kế toán.'],
      ['inflation rate', '/ɪnˈfleɪʃn reɪt/', 'tỷ lệ lạm phát', 'The inflation rate rose to its highest level in a decade.', 'Tỷ lệ lạm phát đã tăng lên mức cao nhất trong một thập kỷ.'],
      ['deflation', '/diːˈfleɪʃn/', 'giảm phát', 'Deflation can lead to lower consumer spending and economic stagnation.', 'Giảm phát có thể dẫn đến chi tiêu tiêu dùng thấp hơn và đình trệ kinh tế.'],
      ['stagflation', '/stæɡˈfleɪʃn/', 'lạm phát đình trệ', 'Stagflation combines high inflation with stagnant economic growth.', 'Lạm phát đình trệ kết hợp lạm phát cao với tăng trưởng kinh tế trì trệ.'],
      ['hyperinflation', '/ˌhaɪpərɪnˈfleɪʃn/', 'siêu lạm phát', 'Hyperinflation destroyed the value of the national currency.', 'Siêu lạm phát đã phá hủy giá trị của đồng tiền quốc gia.'],
      ['consumer price index (cpi)', '/kənˈsjuːmə praɪs ˈɪndeks/', 'chỉ số giá tiêu dùng', 'The consumer price index measures changes in the cost of living.', 'Chỉ số giá tiêu dùng đo lường sự thay đổi trong chi phí sinh hoạt.'],
      ['producer price index (ppi)', '/prəˈdjuːsə praɪs ˈɪndeks/', 'chỉ số giá sản xuất', 'The producer price index tracks changes in wholesale prices.', 'Chỉ số giá sản xuất theo dõi sự thay đổi của giá bán buôn.'],
      ['exchange rate', '/ɪksˈtʃeɪndʒ reɪt/', 'tỷ giá hối đoái', 'The exchange rate between the dong and the dollar fluctuates daily.', 'Tỷ giá hối đoái giữa đồng và đô la biến động hàng ngày.'],
      ['devaluation', '/ˌdiːvæljuˈeɪʃn/', 'sự phá giá tiền tệ', 'The devaluation of the currency made exports cheaper abroad.', 'Việc phá giá tiền tệ khiến hàng xuất khẩu rẻ hơn ở nước ngoài.'],
      ['appreciation (currency)', '/əˌpriːʃiˈeɪʃn/', 'sự tăng giá (tiền tệ)', 'Appreciation of the currency made imported goods cheaper.', 'Sự tăng giá của đồng tiền khiến hàng nhập khẩu rẻ hơn.'],
      ['depreciation (currency)', '/dɪˌpriːʃiˈeɪʃn/', 'sự mất giá (tiền tệ)', 'Depreciation of the currency boosted the country\'s exports.', 'Sự mất giá của đồng tiền đã thúc đẩy xuất khẩu của đất nước.'],
      ['balance of payments', '/ˈbæləns əv ˈpeɪmənts/', 'cán cân thanh toán', 'The balance of payments records all transactions with other countries.', 'Cán cân thanh toán ghi nhận mọi giao dịch với các nước khác.'],
      ['balance of trade', '/ˈbæləns əv treɪd/', 'cán cân thương mại', 'A positive balance of trade means exports exceed imports.', 'Cán cân thương mại dương có nghĩa là xuất khẩu vượt quá nhập khẩu.'],
      ['current account', '/ˈkʌrənt əˈkaʊnt/', 'tài khoản vãng lai', 'The current account deficit widened due to higher imports.', 'Thâm hụt tài khoản vãng lai mở rộng do nhập khẩu tăng.'],
      ['capital account', '/ˈkæpɪtl əˈkaʊnt/', 'tài khoản vốn', 'The capital account tracks investment flows between countries.', 'Tài khoản vốn theo dõi các dòng đầu tư giữa các quốc gia.'],
      ['foreign reserves', '/ˈfɒrən rɪˈzɜːvz/', 'dự trữ ngoại hối', 'The central bank increased its foreign reserves to stabilize the currency.', 'Ngân hàng trung ương tăng dự trữ ngoại hối để ổn định đồng tiền.'],
      ['gold standard', '/ɡəʊld ˈstændəd/', 'bản vị vàng', 'Many countries abandoned the gold standard in the 20th century.', 'Nhiều quốc gia đã từ bỏ bản vị vàng trong thế kỷ 20.'],
      ['fiat money', '/ˈfiːæt ˈmʌni/', 'tiền pháp định', 'Fiat money has value because the government declares it legal tender.', 'Tiền pháp định có giá trị vì chính phủ tuyên bố nó là tiền tệ hợp pháp.'],
      ['legal tender', '/ˈliːɡl ˈtendə(r)/', 'tiền tệ hợp pháp', 'The dollar is the legal tender in the United States.', 'Đô la là tiền tệ hợp pháp ở United States.'],
      ['money supply', '/ˈmʌni səˈplaɪ/', 'cung tiền', 'The central bank controls the money supply to manage inflation.', 'Ngân hàng trung ương kiểm soát cung tiền để quản lý lạm phát.'],
      ['liquidity', '/lɪˈkwɪdəti/', 'tính thanh khoản', 'Cash is the most liquid of all assets.', 'Tiền mặt là tài sản có tính thanh khoản cao nhất trong mọi loại tài sản.'],
      ['solvency', '/ˈsɒlvənsi/', 'khả năng thanh toán', 'The bank\'s solvency was questioned after huge losses.', 'Khả năng thanh toán của ngân hàng bị đặt dấu hỏi sau những khoản lỗ lớn.'],
      ['credit rating', '/ˈkredɪt ˈreɪtɪŋ/', 'xếp hạng tín dụng', 'The country\'s credit rating was downgraded due to rising debt.', 'Xếp hạng tín dụng của đất nước bị hạ bậc do nợ tăng.'],
      ['credit score', '/ˈkredɪt skɔː(r)/', 'điểm tín dụng', 'A high credit score makes it easier to get a loan.', 'Điểm tín dụng cao giúp dễ dàng vay được tiền hơn.'],
      ['mortgage', '/ˈmɔːɡɪdʒ/', 'khoản vay thế chấp', 'They took out a mortgage to buy their first house.', 'Họ đã vay thế chấp để mua ngôi nhà đầu tiên.'],
      ['collateral', '/kəˈlætərəl/', 'tài sản thế chấp', 'The bank required collateral before approving the loan.', 'Ngân hàng yêu cầu tài sản thế chấp trước khi phê duyệt khoản vay.'],
      ['interest-free loan', '/ˈɪntrəst friː ləʊn/', 'khoản vay không lãi suất', 'The program offers interest-free loans to small farmers.', 'Chương trình cung cấp các khoản vay không lãi suất cho nông dân nhỏ.'],
      ['microfinance', '/ˈmaɪkrəʊˌfaɪnæns/', 'tài chính vi mô', 'Microfinance helps low-income people start small businesses.', 'Tài chính vi mô giúp người thu nhập thấp khởi nghiệp kinh doanh nhỏ.'],
      ['remittance', '/rɪˈmɪtəns/', 'kiều hối', 'Remittances from overseas workers support many families back home.', 'Kiều hối từ người lao động ở nước ngoài hỗ trợ nhiều gia đình ở quê nhà.'],
      ['outsourcing', '/ˈaʊtsɔːsɪŋ/', 'thuê ngoài', 'The company outsourced its customer service to another country.', 'Công ty đã thuê ngoài dịch vụ chăm sóc khách hàng cho một nước khác.'],
      ['offshoring', '/ˈɒfʃɔːrɪŋ/', 'chuyển sản xuất ra nước ngoài', 'Offshoring manufacturing helped the firm cut labor costs.', 'Việc chuyển sản xuất ra nước ngoài đã giúp công ty cắt giảm chi phí lao động.'],
      ['supply and demand curve', '/səˈplaɪ ənd dɪˈmɑːnd kɜːv/', 'đường cung cầu', 'The supply and demand curve shows how price affects quantity.', 'Đường cung cầu cho thấy giá ảnh hưởng đến số lượng như thế nào.'],
      ['equilibrium price', '/ˌiːkwɪˈlɪbriəm praɪs/', 'giá cân bằng', 'The equilibrium price is where supply equals demand.', 'Giá cân bằng là mức giá tại đó cung bằng cầu.'],
      ['price ceiling', '/praɪs ˈsiːlɪŋ/', 'giá trần', 'The government imposed a price ceiling on essential goods.', 'Chính phủ áp đặt giá trần đối với hàng hóa thiết yếu.'],
      ['price floor', '/praɪs flɔː(r)/', 'giá sàn', 'The minimum wage acts as a price floor for labor.', 'Lương tối thiểu đóng vai trò như giá sàn đối với lao động.'],
      ['elasticity', '/ˌiːlæˈstɪsəti/', 'độ co giãn', 'The elasticity of demand shows how sensitive buyers are to price changes.', 'Độ co giãn của cầu cho thấy người mua nhạy cảm thế nào với thay đổi giá.'],
      ['inelastic demand', '/ˌɪnɪˈlæstɪk dɪˈmɑːnd/', 'cầu không co giãn', 'Demand for medicine is usually inelastic.', 'Nhu cầu đối với thuốc thường không co giãn.'],
      ['elastic demand', '/ɪˈlæstɪk dɪˈmɑːnd/', 'cầu co giãn', 'Luxury goods often have elastic demand.', 'Hàng hóa xa xỉ thường có cầu co giãn.'],
      ['market failure', '/ˈmɑːkɪt ˈfeɪljə(r)/', 'thất bại thị trường', 'Pollution is a classic example of market failure.', 'Ô nhiễm là một ví dụ kinh điển về thất bại thị trường.'],
      ['externality', '/ˌekstəˈnæləti/', 'ngoại tác', 'Air pollution is a negative externality of industrial production.', 'Ô nhiễm không khí là một ngoại tác tiêu cực của sản xuất công nghiệp.'],
      ['public good', '/ˈpʌblɪk ɡʊd/', 'hàng hóa công cộng', 'National defense is considered a public good.', 'Quốc phòng được coi là một hàng hóa công cộng.'],
      ['private good', '/ˈpraɪvət ɡʊd/', 'hàng hóa tư nhân', 'Food and clothing are examples of private goods.', 'Thực phẩm và quần áo là ví dụ về hàng hóa tư nhân.'],
      ['government intervention', '/ˈɡʌvənmənt ˌɪntəˈvenʃn/', 'sự can thiệp của chính phủ', 'Government intervention helped stabilize the financial sector.', 'Sự can thiệp của chính phủ đã giúp ổn định khu vực tài chính.'],
      ['welfare state', '/ˈwelfeə steɪt/', 'nhà nước phúc lợi', 'Scandinavian countries are known for their strong welfare states.', 'Các nước Scandinavian nổi tiếng với nhà nước phúc lợi mạnh.'],
      ['social security', '/ˈsəʊʃl sɪˈkjʊərəti/', 'an sinh xã hội', 'Social security provides income support for the elderly.', 'An sinh xã hội cung cấp hỗ trợ thu nhập cho người cao tuổi.'],
      ['pension', '/ˈpenʃn/', 'lương hưu', 'She receives a monthly pension after retirement.', 'Cô ấy nhận lương hưu hàng tháng sau khi nghỉ hưu.'],
      ['retirement fund', '/rɪˈtaɪəmənt fʌnd/', 'quỹ hưu trí', 'Employees contribute part of their salary to a retirement fund.', 'Nhân viên đóng góp một phần lương vào quỹ hưu trí.'],
      ['unemployment benefits', '/ˌʌnɪmˈplɔɪmənt ˈbenɪfɪts/', 'trợ cấp thất nghiệp', 'He applied for unemployment benefits after losing his job.', 'Anh ấy nộp đơn xin trợ cấp thất nghiệp sau khi mất việc.'],
      ['labor union', '/ˈleɪbə ˈjuːniən/', 'công đoàn lao động', 'The labor union negotiated better wages for factory workers.', 'Công đoàn lao động đã thương lượng mức lương tốt hơn cho công nhân nhà máy.'],
      ['strike', '/straɪk/', 'cuộc đình công', 'Workers went on strike to demand higher pay.', 'Công nhân đình công để đòi tăng lương.'],
      ['collective bargaining', '/kəˈlektɪv ˈbɑːɡɪnɪŋ/', 'thương lượng tập thể', 'Collective bargaining resulted in improved working conditions.', 'Thương lượng tập thể đã dẫn đến điều kiện làm việc được cải thiện.'],
      ['human capital', '/ˈhjuːmən ˈkæpɪtl/', 'vốn con người', 'Education and training increase a nation\'s human capital.', 'Giáo dục và đào tạo làm tăng vốn con người của một quốc gia.'],
      ['skilled labor', '/skɪld ˈleɪbə/', 'lao động có tay nghề', 'Skilled labor is in high demand in the tech industry.', 'Lao động có tay nghề đang được nhu cầu cao trong ngành công nghệ.'],
      ['unskilled labor', '/ʌnˈskɪld ˈleɪbə/', 'lao động phổ thông', 'Unskilled labor often receives lower wages.', 'Lao động phổ thông thường nhận mức lương thấp hơn.'],
      ['automation', '/ˌɔːtəˈmeɪʃn/', 'tự động hóa', 'Automation has replaced many manual jobs in factories.', 'Tự động hóa đã thay thế nhiều công việc thủ công trong các nhà máy.'],
      ['artificial intelligence', '/ˌɑːtɪˈfɪʃl ɪnˈtelɪdʒəns/', 'trí tuệ nhân tạo', 'Artificial intelligence is transforming how businesses analyze data.', 'Trí tuệ nhân tạo đang thay đổi cách doanh nghiệp phân tích dữ liệu.'],
      ['digital transformation', '/ˈdɪdʒɪtl ˌtrænsfəˈmeɪʃn/', 'chuyển đổi số', 'Digital transformation helped the company reduce operating costs.', 'Chuyển đổi số đã giúp công ty giảm chi phí vận hành.'],
      ['sustainability', '/səˌsteɪnəˈbɪləti/', 'tính bền vững', 'Sustainability is now a key factor in business strategy.', 'Tính bền vững hiện là yếu tố then chốt trong chiến lược kinh doanh.'],
      ['green economy', '/ɡriːn ɪˈkɒnəmi/', 'kinh tế xanh', 'The country is investing heavily in a green economy.', 'Đất nước đang đầu tư mạnh vào kinh tế xanh.'],
      ['carbon tax', '/ˈkɑːbən tæks/', 'thuế carbon', 'A carbon tax encourages companies to reduce emissions.', 'Thuế carbon khuyến khích các công ty giảm phát thải.'],
      ['circular economy', '/ˈsɜːkjələ ɪˈkɒnəmi/', 'kinh tế tuần hoàn', 'The circular economy focuses on reusing and recycling resources.', 'Kinh tế tuần hoàn tập trung vào việc tái sử dụng và tái chế nguồn lực.'],
      ['economic indicator', '/ˌiːkəˈnɒmɪk ˈɪndɪkeɪtə(r)/', 'chỉ số kinh tế', 'GDP is one of the most important economic indicators.', 'GDP là một trong những chỉ số kinh tế quan trọng nhất.'],
      ['leading indicator', '/ˈliːdɪŋ ˈɪndɪkeɪtə(r)/', 'chỉ số dẫn báo', 'Stock prices are often used as a leading indicator of the economy.', 'Giá cổ phiếu thường được dùng như một chỉ số dẫn báo của nền kinh tế.'],
      ['lagging indicator', '/ˈlæɡɪŋ ˈɪndɪkeɪtə(r)/', 'chỉ số trễ', 'Unemployment rate is considered a lagging indicator.', 'Tỷ lệ thất nghiệp được coi là một chỉ số trễ.'],
      ['business cycle', '/ˈbɪznəs ˈsaɪkl/', 'chu kỳ kinh doanh', 'The economy goes through phases known as the business cycle.', 'Nền kinh tế trải qua các giai đoạn được gọi là chu kỳ kinh doanh.'],
      ['peak (business cycle)', '/piːk/', 'đỉnh (chu kỳ kinh tế)', 'The economy reached its peak before the recession began.', 'Nền kinh tế đạt đỉnh trước khi suy thoái bắt đầu.'],
      ['trough', '/trɒf/', 'đáy (chu kỳ kinh tế)', 'The economy hit a trough before slowly recovering.', 'Nền kinh tế chạm đáy trước khi phục hồi dần.'],
      ['contraction', '/kənˈtrækʃn/', 'sự suy giảm kinh tế', 'The economic contraction led to widespread job losses.', 'Sự suy giảm kinh tế đã dẫn đến mất việc làm trên diện rộng.'],
      ['expansion', '/ɪkˈspænʃn/', 'sự mở rộng kinh tế', 'The expansion phase saw rising output and employment.', 'Giai đoạn mở rộng chứng kiến sản lượng và việc làm tăng lên.'],
      ['fiscal year', '/ˈfɪskl jɪə(r)/', 'năm tài chính', 'The company\'s fiscal year ends in March.', 'Năm tài chính của công ty kết thúc vào tháng Ba.'],
      ['audit', '/ˈɔːdɪt/', 'kiểm toán', 'An independent audit confirmed the company\'s financial statements.', 'Một cuộc kiểm toán độc lập đã xác nhận báo cáo tài chính của công ty.'],
  ],
};
