import { CefrLevel } from '@prisma/client';
import type { VocabularySeedSet } from './vocabulary-tech-sets';

export const OFFICE_VOCABULARY_SET: VocabularySeedSet = {
  slug: 'cong-viec-van-phong',
  title: 'Công việc văn phòng',
  description:
    '200 từ vựng văn phòng thiết yếu: chức danh, họp hành, email, báo cáo, dự án, thiết bị và quy trình làm việc',
  icon: 'briefcase',
  color: 'teal',
  cefrLevel: CefrLevel.A2,
  topic: 'Công việc',
  isFeatured: true,
  sortOrder: 3,
  words: [
      ['ceo (chief executive officer)', '/ˌsiː iː ˈəʊ/', 'giám đốc điều hành', 'The CEO announced a new company strategy.', 'CEO đã công bố một chiến lược công ty mới.'],
      ['manager', '/ˈmænɪdʒər/', 'quản lý', 'The manager reviewed the monthly sales report.', 'Người quản lý đã xem xét báo cáo doanh số hàng tháng.'],
      ['employee', '/ɪmˈplɔɪiː/', 'nhân viên', 'Every employee must clock in by nine.', 'Mọi nhân viên phải chấm công trước chín giờ.'],
      ['colleague', '/ˈkɒliːɡ/', 'đồng nghiệp', 'I had lunch with my colleague today.', 'Hôm nay tôi đã ăn trưa với đồng nghiệp.'],
      ['intern', '/ˈɪntɜːn/', 'thực tập sinh', 'The intern helped organize the files.', 'Thực tập sinh đã giúp sắp xếp các hồ sơ.'],
      ['supervisor', '/ˈsuːpəvaɪzər/', 'người giám sát', 'The supervisor checked everyone\'s progress.', 'Người giám sát đã kiểm tra tiến độ của mọi người.'],
      ['assistant', '/əˈsɪstənt/', 'trợ lý', 'Her assistant scheduled all her meetings.', 'Trợ lý của cô ấy đã sắp xếp tất cả các cuộc họp.'],
      ['receptionist', '/rɪˈsepʃənɪst/', 'lễ tân', 'The receptionist greeted the visitors warmly.', 'Lễ tân đã chào đón khách một cách nhiệt tình.'],
      ['hr (human resources)', '/eɪtʃ ɑːr/', 'nhân sự', 'HR is handling the new hiring process.', 'HR đang xử lý quy trình tuyển dụng mới.'],
      ['accountant', '/əˈkaʊntənt/', 'kế toán viên', 'The accountant prepared the annual financial report.', 'Kế toán viên đã chuẩn bị báo cáo tài chính hàng năm.'],
      ['secretary', '/ˈsekrətri/', 'thư ký', 'The secretary typed up the meeting minutes.', 'Thư ký đã đánh máy biên bản cuộc họp.'],
      ['director', '/dəˈrektər/', 'giám đốc', 'The director approved the new budget plan.', 'Giám đốc đã phê duyệt kế hoạch ngân sách mới.'],
      ['staff', '/stɑːf/', 'nhân viên (tập thể)', 'All staff must attend the training session.', 'Tất cả nhân viên phải tham dự buổi đào tạo.'],
      ['boss', '/bɒs/', 'sếp', 'My boss praised my work this week.', 'Tuần này sếp đã khen ngợi công việc của tôi.'],
      ['team leader', '/tiːm ˈliːdər/', 'trưởng nhóm', 'The team leader assigned tasks to each member.', 'Trưởng nhóm đã giao nhiệm vụ cho từng thành viên.'],
      ['client', '/ˈklaɪənt/', 'khách hàng (doanh nghiệp)', 'We met with an important client this morning.', 'Sáng nay chúng tôi đã gặp một khách hàng quan trọng.'],
      ['customer', '/ˈkʌstəmər/', 'khách hàng', 'The customer complained about the delayed order.', 'Khách hàng đã phàn nàn về đơn hàng bị chậm.'],
      ['business partner', '/ˈbɪznəs ˈpɑːtnər/', 'đối tác kinh doanh', 'We signed a deal with our business partner.', 'Chúng tôi đã ký thỏa thuận với đối tác kinh doanh.'],
      ['freelancer', '/ˈfriːlɑːnsər/', 'người làm tự do', 'She works as a freelancer from home.', 'Cô ấy làm freelancer từ nhà.'],
      ['consultant', '/kənˈsʌltənt/', 'nhà tư vấn', 'The consultant advised on improving efficiency.', 'Nhà tư vấn đã đưa ra lời khuyên để cải thiện hiệu quả.'],
      ['computer', '/kəmˈpjuːtər/', 'máy tính', 'I use my computer to write reports.', 'Tôi dùng máy tính để viết báo cáo.'],
      ['laptop', '/ˈlæptɒp/', 'máy tính xách tay', 'She brought her laptop to the meeting.', 'Cô ấy mang laptop đến cuộc họp.'],
      ['printer', '/ˈprɪntər/', 'máy in', 'The printer ran out of ink again.', 'Máy in lại hết mực rồi.'],
      ['scanner', '/ˈskænər/', 'máy quét', 'Use the scanner to digitize the contract.', 'Hãy dùng máy quét để số hóa hợp đồng.'],
      ['photocopier', '/ˈfəʊtəʊkɒpiər/', 'máy photocopy', 'The photocopier is out of paper.', 'Máy photocopy hết giấy rồi.'],
      ['stapler', '/ˈsteɪplər/', 'cái bấm ghim', 'Can I borrow your stapler for a second?', 'Tôi có thể mượn cái bấm ghim của bạn một chút không?'],
      ['paper clip', '/ˈpeɪpə klɪp/', 'kẹp giấy', 'She attached the receipt with a paper clip.', 'Cô ấy kẹp biên lai bằng một cái kẹp giấy.'],
      ['folder', '/ˈfəʊldər/', 'cặp tài liệu / thư mục', 'Please put the documents in this folder.', 'Xin hãy để tài liệu vào cặp này.'],
      ['notebook', '/ˈnəʊtbʊk/', 'sổ ghi chép', 'I write my ideas in a notebook.', 'Tôi ghi ý tưởng vào sổ tay.'],
      ['pen', '/pen/', 'bút mực', 'He signed the contract with a blue pen.', 'Anh ấy ký hợp đồng bằng một cây bút mực xanh.'],
      ['desk', '/desk/', 'bàn làm việc', 'Her desk is always neat and organized.', 'Bàn làm việc của cô ấy luôn gọn gàng và ngăn nắp.'],
      ['office chair', '/ˈɒfɪs tʃeər/', 'ghế văn phòng', 'The office chair is very comfortable.', 'Ghế văn phòng rất thoải mái.'],
      ['cabinet', '/ˈkæbɪnət/', 'tủ hồ sơ', 'The files are stored in the cabinet.', 'Các hồ sơ được lưu trong tủ hồ sơ.'],
      ['whiteboard', '/ˈwaɪtbɔːd/', 'bảng trắng', 'He drew the plan on the whiteboard.', 'Anh ấy vẽ kế hoạch lên bảng trắng.'],
      ['projector', '/prəˈdʒektər/', 'máy chiếu', 'The projector displayed the presentation slides.', 'Máy chiếu đã hiển thị các slide thuyết trình.'],
      ['telephone', '/ˈtelɪfəʊn/', 'điện thoại (bàn)', 'The telephone rang during the meeting.', 'Điện thoại bàn reo trong lúc họp.'],
      ['fax machine', '/fæks məˈʃiːn/', 'máy fax', 'We sent the document by fax machine.', 'Chúng tôi đã gửi tài liệu bằng máy fax.'],
      ['calculator', '/ˈkælkjuleɪtər/', 'máy tính (số học)', 'The accountant used a calculator to check the figures.', 'Kế toán viên dùng máy tính để kiểm tra các con số.'],
      ['envelope', '/ˈenvələʊp/', 'phong bì', 'She sealed the letter in an envelope.', 'Cô ấy đã dán kín lá thư trong phong bì.'],
      ['calendar', '/ˈkælɪndər/', 'lịch làm việc', 'Mark the deadline on your calendar.', 'Hãy đánh dấu hạn chót trên lịch của bạn.'],
      ['office', '/ˈɒfɪs/', 'văn phòng', 'She arrives at the office at eight every day.', 'Cô ấy đến văn phòng lúc tám giờ mỗi ngày.'],
      ['workplace', '/ˈwɜːkpleɪs/', 'nơi làm việc', 'Our workplace has a friendly atmosphere.', 'Nơi làm việc của chúng tôi có bầu không khí thân thiện.'],
      ['meeting room', '/ˈmiːtɪŋ ruːm/', 'phòng họp', 'The meeting room is booked for two o\'clock.', 'Phòng họp đã được đặt vào lúc hai giờ.'],
      ['conference room', '/ˈkɒnfərəns ruːm/', 'phòng hội nghị', 'The conference room can hold fifty people.', 'Phòng hội nghị có thể chứa năm mươi người.'],
      ['cubicle', '/ˈkjuːbɪkl/', 'ô làm việc riêng', 'He works in a small cubicle.', 'Anh ấy làm việc trong một ô làm việc nhỏ.'],
      ['reception', '/rɪˈsepʃn/', 'quầy lễ tân', 'Please sign in at reception.', 'Xin hãy đăng ký tại quầy lễ tân.'],
      ['lobby', '/ˈlɒbi/', 'sảnh chờ', 'We waited for our guest in the lobby.', 'Chúng tôi đợi khách trong sảnh chờ.'],
      ['pantry', '/ˈpæntri/', 'nhà bếp nhỏ (văn phòng)', 'There\'s coffee in the pantry.', 'Có cà phê trong nhà bếp nhỏ.'],
      ['break room', '/breɪk ruːm/', 'phòng nghỉ giải lao', 'Employees relax in the break room during lunch.', 'Nhân viên thư giãn trong phòng nghỉ giải lao vào giờ trưa.'],
      ['open-plan office', '/ˈəʊpən plæn ˈɒfɪs/', 'văn phòng mở', 'The company redesigned into an open-plan office.', 'Công ty đã thiết kế lại thành văn phòng mở.'],
      ['headquarters', '/ˌhedˈkwɔːtəz/', 'trụ sở chính', 'The headquarters is located downtown.', 'Trụ sở chính nằm ở trung tâm thành phố.'],
      ['branch', '/brɑːntʃ/', 'chi nhánh', 'The company opened a new branch last year.', 'Công ty đã mở một chi nhánh mới năm ngoái.'],
      ['department', '/dɪˈpɑːtmənt/', 'phòng ban', 'She works in the marketing department.', 'Cô ấy làm việc ở phòng marketing.'],
      ['floor', '/flɔːr/', 'tầng (tòa nhà)', 'Our office is on the fifth floor.', 'Văn phòng của chúng tôi ở tầng năm.'],
      ['elevator', '/ˈelɪveɪtər/', 'thang máy', 'The elevator was out of service this morning.', 'Sáng nay thang máy bị hỏng.'],
      ['parking lot', '/ˈpɑːkɪŋ lɒt/', 'bãi đỗ xe', 'Employees park in the company parking lot.', 'Nhân viên đỗ xe ở bãi đỗ xe của công ty.'],
      ['cafeteria', '/ˌkæfəˈtɪəriə/', 'căng tin', 'We had lunch in the cafeteria.', 'Chúng tôi đã ăn trưa ở căng tin.'],
      ['storage room', '/ˈstɔːrɪdʒ ruːm/', 'phòng lưu trữ', 'Old files are kept in the storage room.', 'Hồ sơ cũ được giữ trong phòng lưu trữ.'],
      ['workstation', '/ˈwɜːksteɪʃn/', 'chỗ làm việc', 'Each employee has their own workstation.', 'Mỗi nhân viên có chỗ làm việc riêng.'],
      ['building', '/ˈbɪldɪŋ/', 'tòa nhà', 'The office building has twenty floors.', 'Tòa nhà văn phòng có hai mươi tầng.'],
      ['task', '/tɑːsk/', 'nhiệm vụ', 'I completed all my tasks before noon.', 'Tôi đã hoàn thành tất cả nhiệm vụ trước buổi trưa.'],
      ['assignment', '/əˈsaɪnmənt/', 'công việc được giao', 'She finished the assignment ahead of schedule.', 'Cô ấy đã hoàn thành công việc được giao trước thời hạn.'],
      ['deadline', '/ˈdedlaɪn/', 'hạn chót', 'The deadline for the report is Friday.', 'Hạn chót của báo cáo là thứ Sáu.'],
      ['schedule', '/ˈʃedjuːl/', 'lịch trình', 'Check your schedule before booking a meeting.', 'Hãy kiểm tra lịch trình trước khi đặt cuộc họp.'],
      ['agenda', '/əˈdʒendə/', 'chương trình nghị sự', 'The agenda includes three main topics.', 'Chương trình nghị sự gồm ba chủ đề chính.'],
      ['report', '/rɪˈpɔːt/', 'báo cáo', 'He submitted the report to his manager.', 'Anh ấy đã nộp báo cáo cho quản lý.'],
      ['memo', '/ˈmeməʊ/', 'bản ghi nhớ', 'The manager sent a memo about the new policy.', 'Người quản lý đã gửi một bản ghi nhớ về chính sách mới.'],
      ['email', '/ˈiːmeɪl/', 'thư điện tử', 'I\'ll send you an email with the details.', 'Tôi sẽ gửi cho bạn một email kèm chi tiết.'],
      ['meeting', '/ˈmiːtɪŋ/', 'cuộc họp', 'We have a meeting at ten o\'clock.', 'Chúng tôi có cuộc họp lúc mười giờ.'],
      ['appointment', '/əˈpɔɪntmənt/', 'cuộc hẹn', 'She has an appointment with a client.', 'Cô ấy có cuộc hẹn với một khách hàng.'],
      ['presentation', '/ˌprezənˈteɪʃn/', 'bài thuyết trình', 'He gave a presentation on the new product.', 'Anh ấy đã thuyết trình về sản phẩm mới.'],
      ['proposal', '/prəˈpəʊzl/', 'đề xuất', 'The team submitted a proposal for the project.', 'Nhóm đã nộp một đề xuất cho dự án.'],
      ['project', '/ˈprɒdʒekt/', 'dự án', 'The project must be finished by next month.', 'Dự án phải được hoàn thành trước tháng sau.'],
      ['workload', '/ˈwɜːkləʊd/', 'khối lượng công việc', 'Her workload increased after the promotion.', 'Khối lượng công việc của cô ấy tăng lên sau khi được thăng chức.'],
      ['overtime', '/ˈəʊvətaɪm/', 'làm thêm giờ', 'He worked overtime to meet the deadline.', 'Anh ấy đã làm thêm giờ để kịp hạn chót.'],
      ['shift', '/ʃɪft/', 'ca làm việc', 'She works the morning shift.', 'Cô ấy làm ca sáng.'],
      ['routine', '/ruːˈtiːn/', 'công việc thường lệ', 'Checking emails is part of his daily routine.', 'Kiểm tra email là một phần trong công việc thường lệ hàng ngày của anh ấy.'],
      ['duty', '/ˈdjuːti/', 'trách nhiệm / nghĩa vụ', 'It\'s my duty to train new staff.', 'Đó là trách nhiệm của tôi khi đào tạo nhân viên mới.'],
      ['responsibility', '/rɪˌspɒnsəˈbɪləti/', 'trách nhiệm', 'Managing the budget is his responsibility.', 'Quản lý ngân sách là trách nhiệm của anh ấy.'],
      ['priority', '/praɪˈɒrəti/', 'ưu tiên', 'Finishing this report is a top priority.', 'Hoàn thành báo cáo này là ưu tiên hàng đầu.'],
      ['skill', '/skɪl/', 'kỹ năng', 'Good communication skill is essential at work.', 'Kỹ năng giao tiếp tốt rất cần thiết trong công việc.'],
      ['experience', '/ɪkˈspɪəriəns/', 'kinh nghiệm', 'She has five years of experience in marketing.', 'Cô ấy có năm năm kinh nghiệm trong lĩnh vực marketing.'],
      ['qualification', '/ˌkwɒlɪfɪˈkeɪʃn/', 'bằng cấp / trình độ', 'He has the right qualifications for this job.', 'Anh ấy có đủ bằng cấp phù hợp cho công việc này.'],
      ['teamwork', '/ˈtiːmwɜːk/', 'làm việc nhóm', 'Teamwork helped us finish the project on time.', 'Làm việc nhóm đã giúp chúng tôi hoàn thành dự án đúng hạn.'],
      ['communication', '/kəˌmjuːnɪˈkeɪʃn/', 'giao tiếp', 'Clear communication prevents misunderstandings.', 'Giao tiếp rõ ràng giúp tránh hiểu lầm.'],
      ['leadership', '/ˈliːdəʃɪp/', 'khả năng lãnh đạo', 'Her leadership inspired the whole team.', 'Khả năng lãnh đạo của cô ấy đã truyền cảm hứng cho cả nhóm.'],
      ['time management', '/taɪm ˈmænɪdʒmənt/', 'quản lý thời gian', 'Time management helps you meet deadlines.', 'Quản lý thời gian giúp bạn kịp hạn chót.'],
      ['problem-solving', '/ˈprɒbləm ˈsɒlvɪŋ/', 'giải quyết vấn đề', 'Problem-solving skills are valued by employers.', 'Kỹ năng giải quyết vấn đề được các nhà tuyển dụng đánh giá cao.'],
      ['multitasking', '/ˌmʌltiˈtɑːskɪŋ/', 'làm nhiều việc cùng lúc', 'Multitasking can sometimes reduce efficiency.', 'Làm nhiều việc cùng lúc đôi khi có thể làm giảm hiệu quả.'],
      ['efficiency', '/ɪˈfɪʃnsi/', 'hiệu quả', 'The new system improved office efficiency.', 'Hệ thống mới đã cải thiện hiệu quả văn phòng.'],
      ['productivity', '/ˌprɒdʌkˈtɪvəti/', 'năng suất', 'Productivity increased after the training.', 'Năng suất tăng lên sau buổi đào tạo.'],
      ['punctuality', '/ˌpʌŋktʃuˈæləti/', 'tính đúng giờ', 'Punctuality is important for professional image.', 'Tính đúng giờ rất quan trọng đối với hình ảnh chuyên nghiệp.'],
      ['reliability', '/rɪˌlaɪəˈbɪləti/', 'sự đáng tin cậy', 'Her reliability makes her a valuable employee.', 'Sự đáng tin cậy khiến cô ấy trở thành một nhân viên quý giá.'],
      ['creativity', '/ˌkriːeɪˈtɪvəti/', 'sự sáng tạo', 'Creativity helps solve problems in new ways.', 'Sự sáng tạo giúp giải quyết vấn đề theo những cách mới.'],
      ['negotiation', '/nɪˌɡəʊʃiˈeɪʃn/', 'đàm phán', 'Negotiation skills are crucial in sales.', 'Kỹ năng đàm phán rất quan trọng trong bán hàng.'],
      ['adaptability', '/əˌdæptəˈbɪləti/', 'khả năng thích nghi', 'Adaptability helps employees handle change.', 'Khả năng thích nghi giúp nhân viên đối phó với sự thay đổi.'],
      ['initiative', '/ɪˈnɪʃətɪv/', 'tính chủ động', 'She showed initiative by solving the issue herself.', 'Cô ấy thể hiện tính chủ động bằng cách tự giải quyết vấn đề.'],
      ['professionalism', '/prəˈfeʃənəlɪzəm/', 'tính chuyên nghiệp', 'Professionalism is expected in every meeting.', 'Tính chuyên nghiệp được kỳ vọng trong mọi cuộc họp.'],
      ['discipline', '/ˈdɪsəplɪn/', 'kỷ luật', 'Discipline keeps the team focused on goals.', 'Kỷ luật giúp nhóm tập trung vào mục tiêu.'],
      ['competence', '/ˈkɒmpɪtəns/', 'năng lực', 'His competence impressed the interviewers.', 'Năng lực của anh ấy đã gây ấn tượng với các nhà phỏng vấn.'],
      ['resume/cv', '/ˈrezjumeɪ/', 'sơ yếu lý lịch', 'She updated her resume before applying.', 'Cô ấy đã cập nhật resume trước khi ứng tuyển.'],
      ['cover letter', '/ˈkʌvər ˈletər/', 'thư xin việc', 'Attach a cover letter with your application.', 'Hãy đính kèm một cover letter cùng hồ sơ ứng tuyển của bạn.'],
      ['job interview', '/dʒɒb ˈɪntəvjuː/', 'phỏng vấn xin việc', 'He prepared carefully for the job interview.', 'Anh ấy đã chuẩn bị kỹ lưỡng cho buổi phỏng vấn xin việc.'],
      ['job application', '/dʒɒb ˌæplɪˈkeɪʃn/', 'đơn xin việc', 'I submitted my job application online.', 'Tôi đã nộp đơn xin việc trực tuyến.'],
      ['job offer', '/dʒɒb ˈɒfər/', 'lời mời làm việc', 'She accepted the job offer immediately.', 'Cô ấy đã nhận lời mời làm việc ngay lập tức.'],
      ['job description', '/dʒɒb dɪˈskrɪpʃn/', 'mô tả công việc', 'Read the job description before applying.', 'Hãy đọc mô tả công việc trước khi ứng tuyển.'],
      ['recruitment', '/rɪˈkruːtmənt/', 'tuyển dụng', 'The company is running a recruitment campaign.', 'Công ty đang triển khai một chiến dịch tuyển dụng.'],
      ['candidate', '/ˈkændɪdət/', 'ứng viên', 'Three candidates were shortlisted for the role.', 'Ba ứng viên đã được chọn vào danh sách ngắn cho vị trí này.'],
      ['employer', '/ɪmˈplɔɪər/', 'nhà tuyển dụng', 'The employer offered flexible working hours.', 'Nhà tuyển dụng đã đề xuất giờ làm việc linh hoạt.'],
      ['employee benefits', '/ɪmˈplɔɪiː ˈbenɪfɪts/', 'phúc lợi nhân viên', 'Employee benefits include health insurance.', 'Phúc lợi nhân viên bao gồm bảo hiểm sức khỏe.'],
      ['salary', '/ˈsæləri/', 'lương', 'Her salary was raised after the promotion.', 'Lương của cô ấy được tăng sau khi thăng chức.'],
      ['promotion', '/prəˈməʊʃn/', 'sự thăng chức', 'He received a promotion to senior manager.', 'Anh ấy được thăng chức lên vị trí quản lý cấp cao.'],
      ['probation', '/prəˈbeɪʃn/', 'thời gian thử việc', 'New staff undergo a three-month probation.', 'Nhân viên mới trải qua thời gian thử việc ba tháng.'],
      ['contract', '/ˈkɒntrækt/', 'hợp đồng', 'She signed a one-year contract.', 'Cô ấy đã ký hợp đồng một năm.'],
      ['resignation', '/ˌrezɪɡˈneɪʃn/', 'đơn xin nghỉ việc', 'He submitted his resignation letter yesterday.', 'Hôm qua anh ấy đã nộp đơn xin nghỉ việc.'],
      ['retirement', '/rɪˈtaɪəmənt/', 'nghỉ hưu', 'She is planning her retirement next year.', 'Cô ấy đang lên kế hoạch nghỉ hưu vào năm tới.'],
      ['onboarding', '/ˈɒnbɔːdɪŋ/', 'đào tạo hội nhập nhân viên mới', 'The onboarding process took a full week.', 'Quy trình onboarding mất cả một tuần.'],
      ['training', '/ˈtreɪnɪŋ/', 'đào tạo', 'New employees attend training sessions.', 'Nhân viên mới tham dự các buổi đào tạo.'],
      ['performance review', '/pəˈfɔːməns rɪˈvjuː/', 'đánh giá hiệu suất', 'The performance review happens twice a year.', 'Đánh giá hiệu suất diễn ra hai lần một năm.'],
      ['career path', '/kəˈrɪər pɑːθ/', 'con đường sự nghiệp', 'She planned her career path carefully.', 'Cô ấy đã lên kế hoạch con đường sự nghiệp một cách cẩn thận.'],
      ['meeting agenda', '/ˈmiːtɪŋ əˈdʒendə/', 'chương trình họp', 'Please review the meeting agenda beforehand.', 'Xin hãy xem trước chương trình họp.'],
      ['minutes', '/ˈmɪnɪts/', 'biên bản họp', 'The secretary took the minutes of the meeting.', 'Thư ký đã ghi biên bản cuộc họp.'],
      ['brainstorm', '/ˈbreɪnstɔːm/', 'động não (ý tưởng)', 'The team held a brainstorm session for the campaign.', 'Nhóm đã tổ chức buổi brainstorm cho chiến dịch.'],
      ['feedback', '/ˈfiːdbæk/', 'phản hồi', 'He gave useful feedback on my proposal.', 'Anh ấy đã đưa ra phản hồi hữu ích về đề xuất của tôi.'],
      ['discussion', '/dɪˈskʌʃn/', 'cuộc thảo luận', 'The discussion focused on the new budget.', 'Cuộc thảo luận tập trung vào ngân sách mới.'],
      ['conference call', '/ˈkɒnfərəns kɔːl/', 'cuộc gọi hội nghị', 'We joined a conference call with the overseas office.', 'Chúng tôi đã tham gia một conference call với văn phòng ở nước ngoài.'],
      ['video call', '/ˈvɪdiəʊ kɔːl/', 'cuộc gọi video', 'The interview was conducted via video call.', 'Buổi phỏng vấn được thực hiện qua video call.'],
      ['memorandum', '/ˌmeməˈrændəm/', 'văn bản ghi nhớ (chính thức)', 'The memorandum outlines the new dress code.', 'Bản ghi nhớ nêu rõ quy định trang phục mới.'],
      ['announcement', '/əˈnaʊnsmənt/', 'thông báo', 'The manager made an important announcement.', 'Người quản lý đã đưa ra một thông báo quan trọng.'],
      ['correspondence', '/ˌkɒrəˈspɒndəns/', 'thư từ trao đổi', 'She handles all business correspondence.', 'Cô ấy phụ trách tất cả thư từ trao đổi công việc.'],
      ['presentation slide', '/ˌprezənˈteɪʃn slaɪd/', 'slide thuyết trình', 'Each presentation slide should be clear and simple.', 'Mỗi slide thuyết trình nên rõ ràng và đơn giản.'],
      ['q&a session', '/kjuː ənd eɪ ˈseʃn/', 'phiên hỏi đáp', 'The Q&A session followed the presentation.', 'Phiên Q&A diễn ra sau bài thuyết trình.'],
      ['follow-up', '/ˈfɒləʊ ʌp/', 'theo dõi tiếp theo', 'I\'ll send a follow-up email tomorrow.', 'Ngày mai tôi sẽ gửi một email follow-up.'],
      ['consensus', '/kənˈsensəs/', 'sự đồng thuận', 'The team reached a consensus on the plan.', 'Nhóm đã đạt được sự đồng thuận về kế hoạch.'],
      ['negotiation meeting', '/nɪˌɡəʊʃiˈeɪʃn ˈmiːtɪŋ/', 'cuộc họp đàm phán', 'The negotiation meeting lasted two hours.', 'Cuộc họp đàm phán kéo dài hai giờ.'],
      ['business trip', '/ˈbɪznəs trɪp/', 'chuyến công tác', 'He is going on a business trip next week.', 'Tuần tới anh ấy sẽ đi công tác.'],
      ['networking', '/ˈnetwɜːkɪŋ/', 'kết nối quan hệ (công việc)', 'Networking events help build business relationships.', 'Các sự kiện networking giúp xây dựng quan hệ kinh doanh.'],
      ['colleague relations', '/ˈkɒliːɡ rɪˈleɪʃnz/', 'quan hệ đồng nghiệp', 'Good colleague relations improve teamwork.', 'Quan hệ đồng nghiệp tốt giúp cải thiện làm việc nhóm.'],
      ['office gossip', '/ˈɒfɪs ˈɡɒsɪp/', 'chuyện phiếm nơi công sở', 'She avoids getting involved in office gossip.', 'Cô ấy tránh dính vào chuyện phiếm nơi công sở.'],
      ['team building', '/tiːm ˈbɪldɪŋ/', 'xây dựng đội nhóm', 'The company organized a team building trip.', 'Công ty đã tổ chức một chuyến team building.'],
      ['budget', '/ˈbʌdʒɪt/', 'ngân sách', 'The department must stick to its budget.', 'Phòng ban phải tuân thủ ngân sách của mình.'],
      ['invoice', '/ˈɪnvɔɪs/', 'hóa đơn', 'Please send the invoice to the finance team.', 'Xin hãy gửi hóa đơn cho bộ phận tài chính.'],
      ['expense', '/ɪkˈspens/', 'chi phí', 'Travel expenses are reimbursed monthly.', 'Chi phí đi lại được hoàn trả hàng tháng.'],
      ['payroll', '/ˈpeɪrəʊl/', 'bảng lương', 'The payroll is processed at the end of the month.', 'Bảng lương được xử lý vào cuối tháng.'],
      ['salary slip', '/ˈsæləri slɪp/', 'phiếu lương', 'You can check your salary slip online.', 'Bạn có thể xem phiếu lương trực tuyến.'],
      ['tax', '/tæks/', 'thuế', 'Income tax is deducted from the salary.', 'Thuế thu nhập được trừ vào lương.'],
      ['reimbursement', '/ˌriːɪmˈbɜːsmənt/', 'sự hoàn trả (chi phí)', 'She requested reimbursement for her travel costs.', 'Cô ấy đã yêu cầu hoàn trả chi phí đi lại.'],
      ['bonus', '/ˈbəʊnəs/', 'tiền thưởng', 'Employees received a year-end bonus.', 'Nhân viên đã nhận tiền thưởng cuối năm.'],
      ['allowance', '/əˈlaʊəns/', 'phụ cấp', 'The company provides a lunch allowance.', 'Công ty cung cấp phụ cấp ăn trưa.'],
      ['employment contract', '/ɪmˈplɔɪmənt ˈkɒntrækt/', 'hợp đồng lao động', 'Read the employment contract carefully before signing.', 'Hãy đọc kỹ hợp đồng lao động trước khi ký.'],
      ['filing', '/ˈfaɪlɪŋ/', 'sắp xếp hồ sơ', 'Filing documents is part of her daily job.', 'Sắp xếp hồ sơ là một phần công việc hàng ngày của cô ấy.'],
      ['documentation', '/ˌdɒkjumenˈteɪʃn/', 'hồ sơ tài liệu', 'All documentation must be kept up to date.', 'Tất cả hồ sơ tài liệu phải được cập nhật thường xuyên.'],
      ['paperwork', '/ˈpeɪpəwɜːk/', 'giấy tờ hành chính', 'There\'s a lot of paperwork to finish today.', 'Hôm nay còn rất nhiều giấy tờ hành chính phải hoàn thành.'],
      ['signature', '/ˈsɪɡnətʃər/', 'chữ ký', 'The manager\'s signature is required on the form.', 'Chữ ký của người quản lý là bắt buộc trên mẫu đơn.'],
      ['approval', '/əˈpruːvl/', 'sự phê duyệt', 'The proposal is waiting for approval.', 'Đề xuất đang chờ phê duyệt.'],
      ['petty cash', '/ˈpeti kæʃ/', 'quỹ tiền mặt nhỏ', 'Use the petty cash for small office purchases.', 'Hãy dùng quỹ tiền mặt nhỏ cho các khoản mua văn phòng nhỏ.'],
      ['purchase order', '/ˈpɜːtʃəs ˈɔːdər/', 'đơn đặt hàng', 'The purchase order was sent to the supplier.', 'Đơn đặt hàng đã được gửi cho nhà cung cấp.'],
      ['receipt', '/rɪˈsiːt/', 'biên lai', 'Keep the receipt for reimbursement.', 'Hãy giữ biên lai để hoàn trả chi phí.'],
      ['audit', '/ˈɔːdɪt/', 'kiểm toán', 'The company undergoes an annual audit.', 'Công ty trải qua một đợt kiểm toán hàng năm.'],
      ['compliance', '/kəmˈplaɪəns/', 'sự tuân thủ (quy định)', 'Compliance with regulations is mandatory.', 'Việc tuân thủ các quy định là bắt buộc.'],
      ['software', '/ˈsɒftweər/', 'phần mềm', 'The company uses accounting software.', 'Công ty sử dụng phần mềm kế toán.'],
      ['database', '/ˈdeɪtəbeɪs/', 'cơ sở dữ liệu', 'Customer information is stored in the database.', 'Thông tin khách hàng được lưu trong cơ sở dữ liệu.'],
      ['spreadsheet', '/ˈspredʃiːt/', 'bảng tính', 'She created a spreadsheet to track expenses.', 'Cô ấy đã tạo một bảng tính để theo dõi chi phí.'],
      ['document', '/ˈdɒkjumənt/', 'tài liệu', 'Save the document before closing it.', 'Hãy lưu tài liệu trước khi đóng nó.'],
      ['file', '/faɪl/', 'tệp tin', 'Please attach the file to your email.', 'Xin hãy đính kèm tệp tin vào email của bạn.'],
      ['password', '/ˈpɑːswɜːd/', 'mật khẩu', 'Never share your password with others.', 'Đừng bao giờ chia sẻ mật khẩu với người khác.'],
      ['network', '/ˈnetwɜːk/', 'mạng lưới (máy tính)', 'The office network was down this morning.', 'Sáng nay mạng văn phòng bị sự cố.'],
      ['server', '/ˈsɜːvər/', 'máy chủ', 'The server stores all company data.', 'Máy chủ lưu trữ tất cả dữ liệu của công ty.'],
      ['cloud storage', '/klaʊd ˈstɔːrɪdʒ/', 'lưu trữ đám mây', 'We back up files using cloud storage.', 'Chúng tôi sao lưu tệp tin bằng lưu trữ đám mây.'],
      ['email account', '/ˈiːmeɪl əˈkaʊnt/', 'tài khoản email', 'Set up your email account on the first day.', 'Hãy thiết lập tài khoản email vào ngày đầu tiên.'],
      ['video conferencing', '/ˈvɪdiəʊ ˈkɒnfərənsɪŋ/', 'hội nghị truyền hình', 'Video conferencing connects our global teams.', 'Hội nghị truyền hình kết nối các nhóm toàn cầu của chúng tôi.'],
      ['instant messaging', '/ˈɪnstənt ˈmesɪdʒɪŋ/', 'nhắn tin tức thời', 'We use instant messaging for quick questions.', 'Chúng tôi dùng nhắn tin tức thời cho các câu hỏi nhanh.'],
      ['login', '/ˈlɒɡɪn/', 'đăng nhập', 'Enter your login details to access the system.', 'Nhập thông tin đăng nhập để truy cập hệ thống.'],
      ['backup', '/ˈbækʌp/', 'sao lưu', 'Always keep a backup of important files.', 'Luôn giữ một bản sao lưu của các tệp quan trọng.'],
      ['printer driver', '/ˈprɪntər ˈdraɪvər/', 'trình điều khiển máy in', 'Install the printer driver before printing.', 'Hãy cài trình điều khiển máy in trước khi in.'],
      ['firewall', '/ˈfaɪəwɔːl/', 'tường lửa', 'The firewall protects the network from attacks.', 'Tường lửa bảo vệ mạng khỏi các cuộc tấn công.'],
      ['it support', '/aɪ tiː səˈpɔːt/', 'bộ phận hỗ trợ kỹ thuật', 'Contact IT support if your computer crashes.', 'Hãy liên hệ IT support nếu máy tính của bạn bị treo.'],
      ['system update', '/ˈsɪstəm ˈʌpdeɪt/', 'cập nhật hệ thống', 'A system update is scheduled for tonight.', 'Một bản cập nhật hệ thống được lên lịch vào tối nay.'],
      ['application', '/ˌæplɪˈkeɪʃn/', 'ứng dụng (phần mềm)', 'This application helps manage daily tasks.', 'Ứng dụng này giúp quản lý các nhiệm vụ hàng ngày.'],
      ['attachment', '/əˈtætʃmənt/', 'tệp đính kèm', 'Please check the attachment in my email.', 'Xin hãy kiểm tra tệp đính kèm trong email của tôi.'],
      ['work-life balance', '/wɜːk laɪf ˈbæləns/', 'cân bằng công việc - cuộc sống', 'Work-life balance is important for wellbeing.', 'Cân bằng công việc và cuộc sống rất quan trọng cho sức khỏe.'],
      ['work environment', '/wɜːk ɪnˈvaɪrənmənt/', 'môi trường làm việc', 'A positive work environment boosts morale.', 'Môi trường làm việc tích cực giúp nâng cao tinh thần.'],
      ['corporate culture', '/ˈkɔːpərət ˈkʌltʃər/', 'văn hóa doanh nghiệp', 'The corporate culture values honesty and respect.', 'Văn hóa doanh nghiệp coi trọng sự trung thực và tôn trọng.'],
      ['dress code', '/dres kəʊd/', 'quy định trang phục', 'The office has a formal dress code.', 'Văn phòng có quy định trang phục trang trọng.'],
      ['office hours', '/ˈɒfɪs ˈaʊəz/', 'giờ làm việc', 'Office hours are from nine to five.', 'Giờ làm việc là từ chín giờ đến năm giờ.'],
      ['remote work', '/rɪˈməʊt wɜːk/', 'làm việc từ xa', 'Remote work became common after the pandemic.', 'Làm việc từ xa trở nên phổ biến sau đại dịch.'],
      ['work from home', '/wɜːk frəm həʊm/', 'làm việc tại nhà', 'She works from home twice a week.', 'Cô ấy làm việc tại nhà hai lần một tuần.'],
      ['flexible hours', '/ˈfleksəbl ˈaʊəz/', 'giờ làm linh hoạt', 'The company offers flexible hours for staff.', 'Công ty cung cấp giờ làm linh hoạt cho nhân viên.'],
      ['career development', '/kəˈrɪər dɪˈveləpmənt/', 'phát triển sự nghiệp', 'The firm invests in career development programs.', 'Công ty đầu tư vào các chương trình phát triển sự nghiệp.'],
      ['employee morale', '/ɪmˈplɔɪiː məˈrɑːl/', 'tinh thần làm việc của nhân viên', 'Good leadership improves employee morale.', 'Sự lãnh đạo tốt giúp cải thiện tinh thần nhân viên.'],
      ['job satisfaction', '/dʒɒb ˌsætɪsˈfækʃn/', 'sự hài lòng với công việc', 'Job satisfaction increases productivity.', 'Sự hài lòng với công việc giúp tăng năng suất.'],
      ['workplace stress', '/ˈwɜːkpleɪs stres/', 'căng thẳng nơi làm việc', 'Workplace stress can affect health.', 'Căng thẳng nơi làm việc có thể ảnh hưởng đến sức khỏe.'],
      ['burnout', '/ˈbɜːnaʊt/', 'kiệt sức vì công việc', 'He took a break to recover from burnout.', 'Anh ấy đã nghỉ để hồi phục sau khi bị kiệt sức vì công việc.'],
      ['colleague conflict', '/ˈkɒliːɡ ˈkɒnflɪkt/', 'xung đột giữa đồng nghiệp', 'The manager resolved the colleague conflict quickly.', 'Người quản lý đã nhanh chóng giải quyết xung đột giữa đồng nghiệp.'],
      ['office politics', '/ˈɒfɪs ˈpɒlətɪks/', 'đấu đá nội bộ nơi công sở', 'She tries to stay out of office politics.', 'Cô ấy cố gắng tránh xa đấu đá nội bộ nơi công sở.'],
      ['team spirit', '/tiːm ˈspɪrɪt/', 'tinh thần đồng đội', 'Team spirit helped them win the project.', 'Tinh thần đồng đội đã giúp họ thắng dự án.'],
      ['diversity', '/daɪˈvɜːsəti/', 'sự đa dạng (nhân sự)', 'The company promotes diversity in hiring.', 'Công ty thúc đẩy sự đa dạng trong tuyển dụng.'],
      ['work ethic', '/wɜːk ˈeθɪk/', 'đạo đức nghề nghiệp / tinh thần làm việc', 'He is known for his strong work ethic.', 'Anh ấy nổi tiếng với tinh thần làm việc mạnh mẽ.'],
      ['motivation', '/ˌməʊtɪˈveɪʃn/', 'động lực làm việc', 'Bonuses can increase employee motivation.', 'Tiền thưởng có thể tăng động lực làm việc của nhân viên.'],
      ['company policy', '/ˈkʌmpəni ˈpɒləsi/', 'chính sách công ty', 'All staff must follow company policy.', 'Tất cả nhân viên phải tuân theo chính sách công ty.'],
  ],
};
