import { CefrLevel } from '@prisma/client';

export const SPEAKING_SCENARIOS = [
  {
    slug: 'san-bay',
    title: 'Sân bay',
    description: 'Check-in, hỏi cổng và xử lý hành lý tại sân bay',
    icon: 'plane',
    color: 'sky',
    learnerRole: 'Hành khách',
    aiRole: 'Nhân viên sân bay',
    objective: 'Hoàn tất thủ tục check-in và tìm đúng cổng lên máy bay',
    minLevel: CefrLevel.A1,
    maxLevel: CefrLevel.B2,
    openingHint: 'Chào hành khách và hỏi họ cần hỗ trợ gì tại quầy check-in.',
    sortOrder: 1,
  },
  {
    slug: 'nha-hang',
    title: 'Nhà hàng',
    description: 'Gọi món, hỏi thành phần và thanh toán tại nhà hàng',
    icon: 'utensils',
    color: 'orange',
    learnerRole: 'Khách',
    aiRole: 'Phục vụ bàn',
    objective: 'Đặt món phù hợp và hỏi rõ về đồ uống hoặc dị ứng thực phẩm',
    minLevel: CefrLevel.A1,
    maxLevel: CefrLevel.B1,
    openingHint: 'Chào khách, mời ngồi và hỏi họ sẵn sàng gọi món chưa.',
    sortOrder: 2,
  },
  {
    slug: 'khach-san',
    title: 'Khách sạn',
    description: 'Nhận phòng, hỏi tiện nghi và yêu cầu hỗ trợ',
    icon: 'hotel',
    color: 'violet',
    learnerRole: 'Khách lưu trú',
    aiRole: 'Lễ tân khách sạn',
    objective: 'Nhận phòng và hỏi các thông tin cần thiết về khách sạn',
    minLevel: CefrLevel.A1,
    maxLevel: CefrLevel.B2,
    openingHint: 'Chào khách tại quầy lễ tân và hỏi họ có đặt phòng trước không.',
    sortOrder: 3,
  },
  {
    slug: 'phong-van',
    title: 'Phỏng vấn xin việc',
    description: 'Trả lời câu hỏi phỏng vấn và nêu kinh nghiệm',
    icon: 'briefcase',
    color: 'teal',
    learnerRole: 'Ứng viên',
    aiRole: 'Nhà tuyển dụng',
    objective: 'Giới thiệu bản thân và trả lời câu hỏi phỏng vấn tự tin',
    minLevel: CefrLevel.A2,
    maxLevel: CefrLevel.C1,
    openingHint: 'Chào ứng viên, giới thiệu ngắn và hỏi họ tự giới thiệu về bản thân.',
    sortOrder: 4,
  },
  {
    slug: 'mua-sam',
    title: 'Mua sắm',
    description: 'Hỏi giá, size và xin giảm giá khi mua sắm',
    icon: 'shopping-bag',
    color: 'pink',
    learnerRole: 'Khách mua hàng',
    aiRole: 'Nhân viên cửa hàng',
    objective: 'Tìm sản phẩm phù hợp và hỏi rõ giá, size, chính sách đổi trả',
    minLevel: CefrLevel.A1,
    maxLevel: CefrLevel.B1,
    openingHint: 'Chào khách và hỏi họ đang tìm sản phẩm gì.',
    sortOrder: 5,
  },
  {
    slug: 'hoi-duong',
    title: 'Hỏi đường',
    description: 'Hỏi và hiểu chỉ dẫn đường đi trong thành phố',
    icon: 'map-pin',
    color: 'green',
    learnerRole: 'Du khách',
    aiRole: 'Người bản xứ thân thiện',
    objective: 'Hỏi đường đến một địa điểm và xác nhận lại hướng đi',
    minLevel: CefrLevel.A1,
    maxLevel: CefrLevel.A2,
    openingHint: 'Chào du khách và hỏi họ đang tìm nơi nào.',
    sortOrder: 6,
  },
  {
    slug: 'kham-benh',
    title: 'Khám bệnh',
    description: 'Mô tả triệu chứng và hiểu lời khuyên của bác sĩ',
    icon: 'stethoscope',
    color: 'red',
    learnerRole: 'Bệnh nhân',
    aiRole: 'Bác sĩ',
    objective: 'Mô tả triệu chứng rõ ràng và hỏi về cách điều trị',
    minLevel: CefrLevel.A2,
    maxLevel: CefrLevel.B2,
    openingHint: 'Chào bệnh nhân và hỏi họ cảm thấy thế nào hôm nay.',
    sortOrder: 7,
  },
  {
    slug: 'hop-cong-viec',
    title: 'Họp công việc',
    description: 'Thảo luận tiến độ dự án và nêu ý kiến trong cuộc họp',
    icon: 'users',
    color: 'indigo',
    learnerRole: 'Thành viên nhóm',
    aiRole: 'Trưởng nhóm',
    objective: 'Báo cáo tiến độ và trả lời câu hỏi về công việc',
    minLevel: CefrLevel.B1,
    maxLevel: CefrLevel.C1,
    openingHint: 'Mở cuộc họp, chào nhóm và hỏi cập nhật tiến độ dự án.',
    sortOrder: 8,
  },
  {
    slug: 'lam-quen',
    title: 'Làm quen',
    description: 'Trò chuyện xã giao và hỏi đáp về sở thích',
    icon: 'smile',
    color: 'amber',
    learnerRole: 'Người mới gặp',
    aiRole: 'Người bản ngữ thân thiện',
    objective: 'Tự giới thiệu, hỏi sở thích và giữ cuộc trò chuyện tự nhiên',
    minLevel: CefrLevel.A1,
    maxLevel: CefrLevel.B1,
    openingHint: 'Chào thân thiện và hỏi tên cùng lý do họ đến sự kiện này.',
    sortOrder: 9,
  },
  {
    slug: 'goi-dien',
    title: 'Gọi điện',
    description: 'Gọi điện đặt lịch hoặc hỏi thông tin dịch vụ',
    icon: 'phone',
    color: 'blue',
    learnerRole: 'Người gọi',
    aiRole: 'Nhân viên tổng đài',
    objective: 'Nêu rõ mục đích cuộc gọi và đặt lịch hoặc xin thông tin',
    minLevel: CefrLevel.A2,
    maxLevel: CefrLevel.B2,
    openingHint: 'Trả lời điện thoại chuyên nghiệp và hỏi bạn có thể giúp gì.',
    sortOrder: 10,
  },
] as const;
