import { CefrLevel } from '@prisma/client';

const CORE_SPEAKING_SCENARIOS = [
  {
    slug: 'san-bay',
    title: 'Sân bay',
    description: 'Check-in, hỏi cổng và xử lý hành lý tại sân bay',
    icon: 'plane',
    color: 'sky',
    learnerRole: 'Hành khách',
    aiRole: 'Nhân viên sân bay',
    objective: 'Hoàn tất thủ tục check-in và tìm đúng cổng lên máy bay',
    minLevel: CefrLevel.A1,
    maxLevel: CefrLevel.B2,
    openingHint: 'Chào hành khách và hỏi họ cần hỗ trợ gì tại quầy check-in.',
    sortOrder: 1,
  },
  {
    slug: 'nha-hang',
    title: 'Nhà hàng',
    description: 'Gọi món, hỏi thành phần và thanh toán tại nhà hàng',
    icon: 'utensils',
    color: 'orange',
    learnerRole: 'Khách',
    aiRole: 'Phục vụ bàn',
    objective: 'Đặt món phù hợp và hỏi rõ về đồ uống hoặc dị ứng thực phẩm',
    minLevel: CefrLevel.A1,
    maxLevel: CefrLevel.B1,
    openingHint: 'Chào khách, mời ngồi và hỏi họ sẵn sàng gọi món chưa.',
    sortOrder: 2,
  },
  {
    slug: 'khach-san',
    title: 'Khách sạn',
    description: 'Nhận phòng, hỏi tiện nghi và yêu cầu hỗ trợ',
    icon: 'hotel',
    color: 'violet',
    learnerRole: 'Khách lưu trú',
    aiRole: 'Lễ tân khách sạn',
    objective: 'Nhận phòng và hỏi các thông tin cần thiết về khách sạn',
    minLevel: CefrLevel.A1,
    maxLevel: CefrLevel.B2,
    openingHint:
      'Chào khách tại quầy lễ tân và hỏi họ có đặt phòng trước không.',
    sortOrder: 3,
  },
  {
    slug: 'phong-van',
    title: 'Phỏng vấn xin việc',
    description: 'Trả lời câu hỏi phỏng vấn và nêu kinh nghiệm',
    icon: 'briefcase',
    color: 'teal',
    learnerRole: 'Ứng viên',
    aiRole: 'Nhà tuyển dụng',
    objective: 'Giới thiệu bản thân và trả lời câu hỏi phỏng vấn tự tin',
    minLevel: CefrLevel.A2,
    maxLevel: CefrLevel.C1,
    openingHint:
      'Chào ứng viên, giới thiệu ngắn và hỏi họ tự giới thiệu về bản thân.',
    sortOrder: 4,
  },
  {
    slug: 'mua-sam',
    title: 'Mua sắm',
    description: 'Hỏi giá, size và xin giảm giá khi mua sắm',
    icon: 'shopping-bag',
    color: 'pink',
    learnerRole: 'Khách mua hàng',
    aiRole: 'Nhân viên cửa hàng',
    objective: 'Tìm sản phẩm phù hợp và hỏi rõ giá, size, chính sách đổi trả',
    minLevel: CefrLevel.A1,
    maxLevel: CefrLevel.B1,
    openingHint: 'Chào khách và hỏi họ đang tìm sản phẩm gì.',
    sortOrder: 5,
  },
  {
    slug: 'hoi-duong',
    title: 'Hỏi đường',
    description: 'Hỏi và hiểu chỉ dẫn đường đi trong thành phố',
    icon: 'map-pin',
    color: 'green',
    learnerRole: 'Du khách',
    aiRole: 'Người bản xứ thân thiện',
    objective: 'Hỏi đường đến một địa điểm và xác nhận lại hướng đi',
    minLevel: CefrLevel.A1,
    maxLevel: CefrLevel.A2,
    openingHint: 'Chào du khách và hỏi họ đang tìm nơi nào.',
    sortOrder: 6,
  },
  {
    slug: 'kham-benh',
    title: 'Khám bệnh',
    description: 'Mô tả triệu chứng và hiểu lời khuyên của bác sĩ',
    icon: 'stethoscope',
    color: 'red',
    learnerRole: 'Bệnh nhân',
    aiRole: 'Bác sĩ',
    objective: 'Mô tả triệu chứng rõ ràng và hỏi về cách điều trị',
    minLevel: CefrLevel.A2,
    maxLevel: CefrLevel.B2,
    openingHint: 'Chào bệnh nhân và hỏi họ cảm thấy thế nào hôm nay.',
    sortOrder: 7,
  },
  {
    slug: 'hop-cong-viec',
    title: 'Họp công việc',
    description: 'Thảo luận tiến độ dự án và nêu ý kiến trong cuộc họp',
    icon: 'users',
    color: 'indigo',
    learnerRole: 'Thành viên nhóm',
    aiRole: 'Trưởng nhóm',
    objective: 'Báo cáo tiến độ và trả lời câu hỏi về công việc',
    minLevel: CefrLevel.B1,
    maxLevel: CefrLevel.C1,
    openingHint: 'Mở cuộc họp, chào nhóm và hỏi cập nhật tiến độ dự án.',
    sortOrder: 8,
  },
  {
    slug: 'lam-quen',
    title: 'Làm quen',
    description: 'Trò chuyện xã giao và hỏi đáp về sở thích',
    icon: 'smile',
    color: 'amber',
    learnerRole: 'Người mới gặp',
    aiRole: 'Người bản ngữ thân thiện',
    objective: 'Tự giới thiệu, hỏi sở thích và giữ cuộc trò chuyện tự nhiên',
    minLevel: CefrLevel.A1,
    maxLevel: CefrLevel.B1,
    openingHint: 'Chào thân thiện và hỏi tên cùng lý do họ đến sự kiện này.',
    sortOrder: 9,
  },
  {
    slug: 'goi-dien',
    title: 'Gọi điện',
    description: 'Gọi điện đặt lịch hoặc hỏi thông tin dịch vụ',
    icon: 'phone',
    color: 'blue',
    learnerRole: 'Người gọi',
    aiRole: 'Nhân viên tổng đài',
    objective: 'Nêu rõ mục đích cuộc gọi và đặt lịch hoặc xin thông tin',
    minLevel: CefrLevel.A2,
    maxLevel: CefrLevel.B2,
    openingHint: 'Trả lời điện thoại chuyên nghiệp và hỏi bạn có thể giúp gì.',
    sortOrder: 10,
  },
] as const;

type ScenarioTuple = readonly [
  slug: string,
  title: string,
  description: string,
  icon: string,
  color: string,
  learnerRole: string,
  aiRole: string,
  objective: string,
  openingHint: string,
];

function defineLevelScenarios(
  level: CefrLevel,
  firstSortOrder: number,
  items: readonly ScenarioTuple[],
) {
  return items.map(
    (
      [
        slug,
        title,
        description,
        icon,
        color,
        learnerRole,
        aiRole,
        objective,
        openingHint,
      ],
      index,
    ) => ({
      slug,
      title,
      description,
      icon,
      color,
      learnerRole,
      aiRole,
      objective,
      minLevel: level,
      maxLevel: level,
      openingHint,
      sortOrder: firstSortOrder + index,
    }),
  );
}

const ADDITIONAL_SPEAKING_SCENARIOS = [
  ...defineLevelScenarios(CefrLevel.A1, 101, [
    [
      'a1-chao-hoi-lop-hoc',
      'Chào hỏi ở lớp học',
      'Giới thiệu tên, quê quán và làm quen với bạn cùng lớp',
      'school',
      'violet',
      'Học viên mới',
      'Bạn cùng lớp',
      'Chào hỏi và giới thiệu ba thông tin cơ bản về bản thân',
      'Chào người học mới và hỏi tên cùng nơi họ đến.',
    ],
    [
      'a1-mua-ca-phe',
      'Mua cà phê',
      'Gọi một đồ uống đơn giản và chọn kích cỡ',
      'coffee',
      'orange',
      'Khách hàng',
      'Nhân viên quán cà phê',
      'Gọi đúng đồ uống, kích cỡ và xác nhận giá',
      'Chào khách và hỏi họ muốn gọi đồ uống gì.',
    ],
    [
      'a1-hoi-gio',
      'Hỏi giờ',
      'Hỏi thời gian và xác nhận giờ bắt đầu một hoạt động',
      'clock',
      'blue',
      'Người hỏi',
      'Người cung cấp thông tin',
      'Hỏi và hiểu giờ hiện tại cùng thời gian bắt đầu',
      'Chào thân thiện và hỏi người học cần biết thời gian nào.',
    ],
    [
      'a1-di-xe-buyt',
      'Đi xe buýt',
      'Hỏi tuyến xe, điểm dừng và mua vé xe buýt',
      'bus',
      'sky',
      'Hành khách',
      'Tài xế xe buýt',
      'Xác nhận đúng tuyến, điểm xuống và giá vé',
      'Chào hành khách và hỏi họ muốn đi đến đâu.',
    ],
    [
      'a1-noi-ve-gia-dinh',
      'Nói về gia đình',
      'Giới thiệu các thành viên và mối quan hệ trong gia đình',
      'users',
      'pink',
      'Người kể',
      'Người bạn mới',
      'Mô tả ngắn gọn ít nhất ba thành viên gia đình',
      'Hỏi người học gia đình họ có bao nhiêu người.',
    ],
    [
      'a1-thoi-tiet-hom-nay',
      'Thời tiết hôm nay',
      'Nói về thời tiết và chọn một hoạt động phù hợp',
      'cloud-sun',
      'cyan',
      'Người lên kế hoạch',
      'Bạn bè',
      'Mô tả thời tiết và đề xuất một hoạt động đơn giản',
      'Hỏi người học thời tiết hôm nay ở chỗ họ thế nào.',
    ],
    [
      'a1-mua-do-an',
      'Mua đồ ăn',
      'Hỏi giá, số lượng và mua thực phẩm tại cửa hàng',
      'shopping-basket',
      'green',
      'Khách mua hàng',
      'Nhân viên cửa hàng',
      'Mua đủ sản phẩm với đúng số lượng và hiểu tổng tiền',
      'Chào khách và hỏi họ đang tìm loại thực phẩm nào.',
    ],
    [
      'a1-thoi-quen-hang-ngay',
      'Thói quen hằng ngày',
      'Nói về giờ thức dậy, học tập, làm việc và nghỉ ngơi',
      'calendar',
      'indigo',
      'Người chia sẻ',
      'Bạn cùng lớp',
      'Kể một ngày điển hình theo đúng trình tự thời gian',
      'Hỏi người học thường bắt đầu ngày mới lúc mấy giờ.',
    ],
    [
      'a1-so-thich-cuoi-tuan',
      'Sở thích cuối tuần',
      'Chia sẻ sở thích và rủ bạn cùng tham gia',
      'smile',
      'amber',
      'Người rủ',
      'Bạn bè',
      'Nêu sở thích, thời gian và đưa ra một lời mời đơn giản',
      'Hỏi người học thường thích làm gì vào cuối tuần.',
    ],
    [
      'a1-muon-sach',
      'Mượn sách',
      'Tìm một cuốn sách và hỏi thủ tục mượn tại thư viện',
      'book',
      'purple',
      'Bạn đọc',
      'Thủ thư',
      'Tìm đúng khu sách và hiểu thời hạn trả sách',
      'Chào bạn đọc và hỏi họ đang tìm cuốn sách về chủ đề gì.',
    ],
  ] as const),
  ...defineLevelScenarios(CefrLevel.A2, 201, [
    [
      'a2-dat-lich-hen',
      'Đặt lịch hẹn',
      'Chọn ngày giờ và xác nhận một cuộc hẹn phù hợp',
      'calendar',
      'blue',
      'Khách đặt lịch',
      'Nhân viên tiếp nhận',
      'Đặt được lịch và xác nhận đầy đủ ngày, giờ, địa điểm',
      'Chào khách và hỏi họ muốn đặt lịch cho dịch vụ nào.',
    ],
    [
      'a2-thue-xe-dap',
      'Thuê xe đạp',
      'Hỏi giá thuê, thời gian và quy định trả xe',
      'bike',
      'green',
      'Khách thuê xe',
      'Nhân viên cho thuê',
      'Chọn loại xe và hiểu chi phí cùng quy định sử dụng',
      'Chào khách và hỏi họ muốn thuê xe trong bao lâu.',
    ],
    [
      'a2-o-nha-thuoc',
      'Ở nhà thuốc',
      'Mô tả triệu chứng nhẹ và hỏi cách dùng thuốc',
      'stethoscope',
      'teal',
      'Khách mua thuốc',
      'Dược sĩ',
      'Mô tả rõ triệu chứng và nhắc lại đúng hướng dẫn sử dụng',
      'Chào khách và hỏi họ đang gặp triệu chứng gì.',
    ],
    [
      'a2-doi-mon-an',
      'Đổi món ăn',
      'Giải thích vấn đề với món ăn và yêu cầu đổi món lịch sự',
      'utensils',
      'orange',
      'Khách dùng bữa',
      'Phục vụ bàn',
      'Nêu lý do hợp lý và thống nhất món thay thế',
      'Hỏi khách món ăn có vấn đề gì và đề nghị hỗ trợ.',
    ],
    [
      'a2-mua-ve-tau',
      'Mua vé tàu',
      'Chọn chuyến, loại vé và hỏi giờ khởi hành',
      'train',
      'sky',
      'Hành khách',
      'Nhân viên bán vé',
      'Mua đúng chuyến và xác nhận sân ga, thời gian, giá vé',
      'Chào hành khách và hỏi họ muốn đi đến thành phố nào.',
    ],
    [
      'a2-bao-do-that-lac',
      'Báo đồ thất lạc',
      'Mô tả món đồ bị mất và nơi nhìn thấy lần cuối',
      'luggage',
      'indigo',
      'Người mất đồ',
      'Nhân viên hỗ trợ',
      'Cung cấp đủ đặc điểm nhận dạng và thông tin liên hệ',
      'Hỏi người học đã làm mất món đồ gì và ở đâu.',
    ],
    [
      'a2-to-chuc-sinh-nhat',
      'Tổ chức sinh nhật',
      'Lên kế hoạch địa điểm, đồ ăn và danh sách khách mời',
      'cake',
      'pink',
      'Người tổ chức',
      'Bạn hỗ trợ',
      'Thống nhất ba hạng mục chính cho buổi tiệc',
      'Hỏi người học muốn tổ chức sinh nhật vào ngày nào.',
    ],
    [
      'a2-dang-ky-khoa-hoc',
      'Đăng ký khóa học',
      'Hỏi lịch học, học phí và yêu cầu đầu vào',
      'graduation-cap',
      'violet',
      'Học viên',
      'Tư vấn viên',
      'Chọn lớp phù hợp và hiểu các bước đăng ký',
      'Chào học viên và hỏi họ quan tâm khóa học nào.',
    ],
    [
      'a2-sua-thiet-bi',
      'Sửa thiết bị',
      'Mô tả lỗi thiết bị và hỏi thời gian sửa chữa',
      'wrench',
      'amber',
      'Khách sửa đồ',
      'Kỹ thuật viên',
      'Mô tả được lỗi, nhận báo giá và thời gian hoàn thành',
      'Hỏi khách thiết bị đang gặp vấn đề gì.',
    ],
    [
      'a2-hoi-dich-vu-ngan-hang',
      'Hỏi dịch vụ ngân hàng',
      'Hỏi thủ tục mở tài khoản và các loại phí cơ bản',
      'landmark',
      'blue',
      'Khách hàng',
      'Nhân viên ngân hàng',
      'Hiểu giấy tờ cần thiết và chọn loại tài khoản phù hợp',
      'Chào khách và hỏi họ cần hỗ trợ dịch vụ ngân hàng nào.',
    ],
  ] as const),
  ...defineLevelScenarios(CefrLevel.B1, 301, [
    [
      'b1-thuyet-trinh-du-an',
      'Thuyết trình dự án',
      'Trình bày mục tiêu, tiến độ và bước tiếp theo của dự án',
      'presentation',
      'indigo',
      'Người thuyết trình',
      'Quản lý dự án',
      'Trình bày mạch lạc và trả lời câu hỏi về tiến độ',
      'Mời người học bắt đầu phần cập nhật dự án của họ.',
    ],
    [
      'b1-thue-can-ho',
      'Thuê căn hộ',
      'Trao đổi giá thuê, tiện ích và điều khoản hợp đồng',
      'house',
      'orange',
      'Người thuê nhà',
      'Chủ nhà',
      'Làm rõ chi phí, thời hạn và trách nhiệm hai bên',
      'Chào người thuê và hỏi họ đang tìm căn hộ như thế nào.',
    ],
    [
      'b1-khieu-nai-dich-vu',
      'Khiếu nại dịch vụ',
      'Trình bày vấn đề và đề nghị giải pháp phù hợp',
      'message-square-warning',
      'red',
      'Khách hàng',
      'Quản lý dịch vụ',
      'Giải thích sự cố bình tĩnh và thống nhất cách xử lý',
      'Xin lỗi khách và mời họ mô tả chi tiết vấn đề.',
    ],
    [
      'b1-tham-gia-tinh-nguyen',
      'Tham gia tình nguyện',
      'Trao đổi kỹ năng, lịch tham gia và nhiệm vụ phù hợp',
      'heart-handshake',
      'green',
      'Tình nguyện viên',
      'Điều phối viên',
      'Giới thiệu năng lực và chọn công việc phù hợp',
      'Chào tình nguyện viên và hỏi họ muốn hỗ trợ lĩnh vực nào.',
    ],
    [
      'b1-thao-luan-tin-tuc',
      'Thảo luận tin tức',
      'Tóm tắt một bản tin và nêu quan điểm cá nhân',
      'newspaper',
      'sky',
      'Người thảo luận',
      'Bạn học',
      'Tóm tắt ý chính và đưa ra lý do cho quan điểm',
      'Đề cập một bản tin gần đây và hỏi người học nghĩ gì.',
    ],
    [
      'b1-dam-phan-lich-lam-viec',
      'Đàm phán lịch làm việc',
      'Đề xuất thay đổi ca làm và tìm phương án thay thế',
      'calendar-clock',
      'teal',
      'Nhân viên',
      'Quản lý',
      'Trình bày lý do và thống nhất lịch mới hợp lý',
      'Hỏi nhân viên vì sao họ muốn thay đổi ca làm.',
    ],
    [
      'b1-xin-phan-hoi-cong-viec',
      'Xin phản hồi công việc',
      'Hỏi nhận xét và kế hoạch cải thiện hiệu suất',
      'briefcase',
      'violet',
      'Nhân viên',
      'Trưởng nhóm',
      'Tiếp nhận góp ý và xác định hai hành động cải thiện',
      'Mở đầu buổi trao đổi và hỏi nhân viên muốn nhận phản hồi về phần nào.',
    ],
    [
      'b1-lap-ke-hoach-du-lich-nhom',
      'Lập kế hoạch du lịch nhóm',
      'Thống nhất điểm đến, ngân sách và lịch trình',
      'plane',
      'cyan',
      'Thành viên nhóm',
      'Bạn đồng hành',
      'Đề xuất lựa chọn và đạt đồng thuận về kế hoạch chính',
      'Hỏi cả nhóm muốn ưu tiên trải nghiệm nào cho chuyến đi.',
    ],
    [
      'b1-tu-van-khach-hang',
      'Tư vấn khách hàng',
      'Tìm hiểu nhu cầu và giới thiệu giải pháp phù hợp',
      'headset',
      'blue',
      'Nhân viên tư vấn',
      'Khách hàng',
      'Đặt câu hỏi đúng và giải thích lợi ích của giải pháp',
      'Đóng vai khách hàng và mô tả nhu cầu ban đầu.',
    ],
    [
      'b1-phong-van-hoc-bong',
      'Phỏng vấn học bổng',
      'Trình bày mục tiêu học tập và thành tích nổi bật',
      'graduation-cap',
      'purple',
      'Ứng viên học bổng',
      'Thành viên hội đồng',
      'Giải thích động lực, thành tích và kế hoạch tương lai',
      'Chào ứng viên và hỏi vì sao họ đăng ký học bổng này.',
    ],
  ] as const),
  ...defineLevelScenarios(CefrLevel.B2, 401, [
    [
      'b2-tranh-luan-cong-nghe',
      'Tranh luận về công nghệ',
      'Phân tích lợi ích và rủi ro của một công nghệ mới',
      'scale',
      'violet',
      'Người tranh luận',
      'Người phản biện',
      'Bảo vệ quan điểm bằng ví dụ và phản hồi ý kiến đối lập',
      'Đưa ra nhận định rằng công nghệ mới luôn cải thiện cuộc sống và mời phản biện.',
    ],
    [
      'b2-xu-ly-xung-dot-nhom',
      'Xử lý xung đột nhóm',
      'Làm rõ bất đồng và đề xuất phương án hòa giải',
      'users',
      'orange',
      'Trưởng nhóm',
      'Thành viên nhóm',
      'Xác định nguyên nhân và thống nhất nguyên tắc làm việc mới',
      'Mô tả một bất đồng trong nhóm và yêu cầu người học điều phối.',
    ],
    [
      'b2-thao-luan-ngan-sach',
      'Thảo luận ngân sách',
      'Ưu tiên hạng mục và bảo vệ quyết định phân bổ chi phí',
      'chart-pie',
      'blue',
      'Quản lý bộ phận',
      'Giám đốc tài chính',
      'Giải thích ưu tiên và đạt thỏa thuận ngân sách',
      'Thông báo ngân sách bị giảm và yêu cầu người học đề xuất điều chỉnh.',
    ],
    [
      'b2-lam-viec-tu-xa',
      'Làm việc từ xa',
      'Thảo luận hiệu suất, giao tiếp và cân bằng công việc',
      'laptop',
      'indigo',
      'Nhân viên từ xa',
      'Quản lý',
      'Đánh giá khó khăn và đề xuất quy trình phối hợp hiệu quả',
      'Hỏi người học những thách thức lớn nhất khi làm việc từ xa.',
    ],
    [
      'b2-hoi-nghi-quoc-te',
      'Hội nghị quốc tế',
      'Kết nối chuyên môn và trao đổi cơ hội hợp tác',
      'globe',
      'sky',
      'Đại biểu',
      'Đối tác quốc tế',
      'Giới thiệu chuyên môn và mở ra bước hợp tác tiếp theo',
      'Chào đại biểu tại giờ nghỉ và hỏi về lĩnh vực họ đang làm việc.',
    ],
    [
      'b2-bao-ve-moi-truong',
      'Bảo vệ môi trường',
      'Đề xuất giải pháp giảm rác thải trong cộng đồng',
      'leaf',
      'green',
      'Đại diện cộng đồng',
      'Quan chức địa phương',
      'Trình bày vấn đề, tác động và kế hoạch hành động khả thi',
      'Hỏi người học cộng đồng đang gặp vấn đề môi trường nào nghiêm trọng nhất.',
    ],
    [
      'b2-khung-hoang-dich-vu',
      'Khủng hoảng dịch vụ',
      'Trấn an khách hàng và điều phối xử lý sự cố diện rộng',
      'headset',
      'red',
      'Quản lý chăm sóc khách hàng',
      'Khách hàng quan trọng',
      'Giải thích minh bạch và thống nhất phương án khắc phục',
      'Đóng vai khách hàng đang rất không hài lòng vì dịch vụ bị gián đoạn.',
    ],
    [
      'b2-de-xuat-chien-luoc',
      'Đề xuất chiến lược',
      'Trình bày cơ hội, rủi ro và lộ trình triển khai',
      'chart-no-axes-combined',
      'teal',
      'Chuyên viên chiến lược',
      'Ban lãnh đạo',
      'Thuyết phục người nghe bằng lập luận và chỉ số phù hợp',
      'Mời người học trình bày đề xuất chiến lược trong năm phút.',
    ],
    [
      'b2-du-hoc-thich-nghi',
      'Du học và thích nghi',
      'Thảo luận khác biệt văn hóa và cách xây dựng mạng lưới',
      'graduation-cap',
      'purple',
      'Du học sinh',
      'Cố vấn sinh viên',
      'Phân tích khó khăn và lập kế hoạch thích nghi thực tế',
      'Hỏi người học điều gì khiến họ khó thích nghi nhất ở môi trường mới.',
    ],
    [
      'b2-phan-tich-thi-truong',
      'Phân tích xu hướng thị trường',
      'Giải thích dữ liệu và dự đoán thay đổi của khách hàng',
      'chart-line',
      'amber',
      'Chuyên viên phân tích',
      'Giám đốc kinh doanh',
      'Nêu xu hướng chính, nguyên nhân và khuyến nghị hành động',
      'Đưa ra một xu hướng doanh số và yêu cầu người học phân tích nguyên nhân.',
    ],
  ] as const),
  ...defineLevelScenarios(CefrLevel.C1, 501, [
    [
      'c1-dam-phan-hop-dong',
      'Đàm phán hợp đồng',
      'Thương lượng điều khoản, trách nhiệm và phương án dự phòng',
      'file-signature',
      'indigo',
      'Đại diện doanh nghiệp',
      'Đối tác thương mại',
      'Bảo vệ lợi ích cốt lõi và đạt thỏa thuận cân bằng',
      'Nêu một điều khoản chưa thể chấp nhận và mời người học đề xuất phương án.',
    ],
    [
      'c1-dan-dat-thay-doi',
      'Dẫn dắt thay đổi tổ chức',
      'Thuyết phục đội ngũ ủng hộ một chuyển đổi lớn',
      'users',
      'violet',
      'Lãnh đạo chuyển đổi',
      'Quản lý cấp trung',
      'Giải thích tầm nhìn, xử lý lo ngại và tạo cam kết',
      'Đóng vai quản lý hoài nghi và hỏi vì sao thay đổi này cần thiết.',
    ],
    [
      'c1-phan-bien-nghien-cuu',
      'Phản biện nghiên cứu',
      'Đánh giá phương pháp, bằng chứng và giới hạn của nghiên cứu',
      'flask-conical',
      'teal',
      'Nhà nghiên cứu',
      'Phản biện học thuật',
      'Bảo vệ lựa chọn phương pháp và thừa nhận giới hạn hợp lý',
      'Đặt câu hỏi về độ tin cậy của dữ liệu trong nghiên cứu.',
    ],
    [
      'c1-phong-van-truyen-thong',
      'Phỏng vấn truyền thông',
      'Trả lời câu hỏi khó và duy trì thông điệp nhất quán',
      'radio',
      'red',
      'Người phát ngôn',
      'Nhà báo',
      'Trả lời trực tiếp, chuyển tiếp thông điệp và tránh suy đoán',
      'Mở đầu cuộc phỏng vấn bằng một câu hỏi nhạy cảm về quyết định gần đây.',
    ],
    [
      'c1-khung-hoang-doanh-nghiep',
      'Khủng hoảng doanh nghiệp',
      'Điều phối phản ứng và truyền đạt quyết định dưới áp lực',
      'siren',
      'orange',
      'Giám đốc xử lý khủng hoảng',
      'Thành viên ban điều hành',
      'Ưu tiên hành động và xây dựng thông điệp minh bạch',
      'Thông báo một sự cố nghiêm trọng và yêu cầu người học đề xuất phản ứng đầu tiên.',
    ],
    [
      'c1-dao-duc-ai',
      'Tranh luận đạo đức AI',
      'Cân nhắc đổi mới, quyền riêng tư và trách nhiệm xã hội',
      'brain-circuit',
      'purple',
      'Chuyên gia công nghệ',
      'Nhà nghiên cứu đạo đức',
      'Xây dựng lập luận đa chiều và phản hồi phản biện tinh tế',
      'Đặt vấn đề liệu hiệu quả có nên được ưu tiên hơn quyền riêng tư.',
    ],
    [
      'c1-hoach-dinh-chinh-sach',
      'Hoạch định chính sách công',
      'Đánh giá tác động và bảo vệ một đề xuất chính sách',
      'landmark',
      'blue',
      'Cố vấn chính sách',
      'Đại biểu hội đồng',
      'Trình bày bằng chứng, tác động và cơ chế thực thi',
      'Yêu cầu người học giải thích ai sẽ hưởng lợi và ai có thể chịu thiệt.',
    ],
    [
      'c1-goi-von-startup',
      'Gọi vốn cho startup',
      'Thuyết phục nhà đầu tư về thị trường và lợi thế cạnh tranh',
      'rocket',
      'pink',
      'Nhà sáng lập',
      'Nhà đầu tư',
      'Trình bày luận điểm đầu tư và xử lý câu hỏi về rủi ro',
      'Mời nhà sáng lập trình bày vì sao doanh nghiệp này có thể tăng trưởng lớn.',
    ],
    [
      'c1-hoa-giai-tranh-chap',
      'Hòa giải tranh chấp',
      'Tái diễn đạt quan điểm và tìm lợi ích chung giữa hai bên',
      'scale',
      'green',
      'Người hòa giải',
      'Đại diện một bên tranh chấp',
      'Hạ nhiệt căng thẳng và xây dựng phương án hai bên chấp nhận',
      'Trình bày lập trường cứng rắn và yêu cầu người học dẫn dắt hòa giải.',
    ],
    [
      'c1-bai-phat-bieu-chuyen-mon',
      'Bài phát biểu chuyên môn',
      'Trình bày một chủ đề phức tạp cho khán giả đa ngành',
      'podium',
      'amber',
      'Diễn giả',
      'Người điều phối hội thảo',
      'Giải thích rõ ý phức tạp và ứng biến với câu hỏi chuyên sâu',
      'Giới thiệu diễn giả và mời họ mở đầu bài phát biểu chuyên môn.',
    ],
  ] as const),
];

export const SPEAKING_SCENARIOS = [
  ...CORE_SPEAKING_SCENARIOS,
  ...ADDITIONAL_SPEAKING_SCENARIOS,
] as const;
